### ISSUE TITLE
nvcc check does not pass

### ISSUE THREAD

**Issue by RaimondNl** [astra-toolbox/astra-toolbox#10]
We use nvcc version 5.5.0 . 
The configure check does not recognise that nvcc is working. From config.log:

```
configure:15205: checking if nvcc works
configure:15217: /usr/bin/nvcc -c -o conftest.o conftest.cu 
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted
configure:15221: $? = 134
configure: failed program was:
| #include <iostream>
| int main() {
|   std::cout << "Test" << std::endl;
|   return 0;
| }
configure:15247: result: no
```

When compiling the test code as a .cpp file (`nvcc conftest.cpp`), it works fine, however, make will not work.

**Comment by wjp** [comment]
If you compile this test code as a .cu file manually, does nvcc indeed crash with an internal error?

**Comment by PaulVanSchayck** [comment]
Found the problem, this was due to IMOD dumping tools in the PATH that causes the compilation to fail. Not related to astra

**Comment by wjp** [comment]
Glad to hear you've found the cause. Thanks for letting us know.
