### ISSUE TITLE
Code not compiling

### ISSUE THREAD

**Issue by venkat-purdue** [astra-toolbox/astra-toolbox#100]
I tried pulling the latest code from git and trying to compile. I get the following error. 

g++ -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -I/usr/local/cuda/include -DASTRA_CUDA -DASTRA_PYTHON -I/usr/include/python2.7 -I../include -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c /home/usv/code/astra-toolbox/python/astra/algorithm_c.cpp -o /home/usv/code/astra-toolbox/build/linux/python/build/temp.linux-x86_64-2.7/home/usv/code/astra-toolbox/python/astra/algorithm_c.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
/home/usv/code/astra-toolbox/python/astra/algorithm_c.cpp: In function ‘PyObject* __pyx_pf_5astra_11algorithm_c_4get_res_norm(PyObject*, PyObject*)’:
/home/usv/code/astra-toolbox/python/astra/algorithm_c.cpp:1620:28: error: expected type-specifier before ‘CReconstructionAlgorithm2D’
   __pyx_t_2 = dynamic_cast<CReconstructionAlgorithm2D*>(__pyx_v_alg); if (unlikely(__pyx_t_2 == NULL)) __PYX_ERR(0, 84, __pyx_L1_error)
                            ^
/home/usv/code/astra-toolbox/python/astra/algorithm_c.cpp:1620:28: error: expected ‘>’ before ‘CReconstructionAlgorithm2D’
/home/usv/code/astra-toolbox/python/astra/algorithm_c.cpp:1620:28: error: expected ‘(’ before ‘CReconstructionAlgorithm2D’
/home/usv/code/astra-toolbox/python/astra/algorithm_c.cpp:1620:28: error: ‘CReconstructionAlgorithm2D’ was not declared in this scope

The machines I tried were Ubuntu machine with gcc 4.8.4.

**Comment by dmpelt** [comment]
We investigated this a bit on email before: I can reproduce it on my machine, and it could be related to 8de844c3521d9ee54087927923b932e1016c5b90 . Reverting to a commit before that one makes the compilation finish without the error, and it seems that the Travis builds started failing with that commit as well.

**Comment by wjp** [comment]
Should be fixed now; sorry for the oversight.
