### ISSUE TITLE
Can OpTomo scale forward and back projections?

### ISSUE THREAD

**Issue by jsbtic** [astra-toolbox/astra-toolbox#102]
Dear all,
     Sorry for asking something so trivial, but I was wondering how does one achieve to get same voxel value range for original and reconstructed/back projected volume when using OpTomo in python? 

For instance, if I use a test volume with constant voxel values of 1 to create `N_ang = 30` projections, and back project them to a volume, the voxel values increase ~ 1e3, c.f.
```python
import astra
import numpy as np

vx, vy, vz = 50, 50, 50
N = 50
N_ang = 30
det_x, det_y = 1, 1

# configure geometry
angles = np.deg2rad(np.linspace(-90, 90, N_ang))
proj_geom = astra.create_proj_geom('parallel3d', det_x, det_y, N, N, angles)
vol_geom = astra.create_vol_geom(vy, vx, vz)

# projector
proj_id = astra.create_projector('cuda3d', proj_geom, vol_geom)
W = astra.OpTomo(proj_id)

# test volume
v1 = np.ones([vx, vy, vz])

# simulate projections
fp = W*v1

# back projections
bp = W.T*fp

# print min, max and mean of voxel values of original and back projected volume
print "\n%10.2f %10.2f %10.2f" % (np.min(v1), np.max(v1), np.mean(v1))
print "%10.2f %10.2f %10.2f" % (np.min(bp), np.max(bp), np.mean(bp))
```
which gives
```
      1.00       1.00       1.00
    882.67    1676.65    1397.81
```
Naturally the values increase as function of number of projections and volume dimensions, but is there some built-in option in OpTomo to get the same scaling? 

The reasons I'm asking in the first place is, that I'm testing some gradient projection methods, and the different scaling causes some issues.

My best,
     - J.

**Comment by wjp** [comment]
Reconstructions will have the same pixel values, but backprojections won't. You may be implicitly assuming that some norm of $W^TW$ equals 1 (where W is the linear forward projection operator).

**Comment by askorikov** [comment]
Just to re-iterate: it is an expected behavior that backprojection produces voxel intensities that are different from the original reconstruction (with the discrepancy proportional, among other things, to the number of input projections).
