### ISSUE TITLE
Can we change voxel size when createing volume geometries

### ISSUE THREAD

**Issue by aimersq** [astra-toolbox/astra-toolbox#103]
Dear all,
Sorry for asking something so trivial. I knew that when we create  volume geometries using function astra_create_vol_geom, the voxel size is default 1X1X1mm.
I was wondering if we could change the voxel sizes？Just like function astra_create_proj_geom did.

**Comment by wjp** [comment]
This is possible since astra-1.7. The function `astra_create_vol_geom` has a 9-argument form, that lets you specify the total extent of the volume:

    vol_geom = astra_create_vol_geom(row_count, col_count, slice_count, min_x, max_x, min_y, max_y,  min_z, max_z);

Note that the default isn't 1mmx1mmx1mm, but just 1x1x1. It isn't tied to any physical unit.

**Comment by aimersq** [comment]
Thank you for your answer. Could  I understand like that,
when we use  `vol_geom = astra_create_vol_geom(600,600,300);` voxel size is 1x1x1 mm3 
when we use  `vol_geom = astra_create_vol_geom(600,600,300,-150,150,-150,150,-75,75);` voxel size is 0.5x0.5x0.5mm3  because   (150-(-150))/600=0.5mm
min_x or max_x is show in  millimeter(mm)?

**Comment by wjp** [comment]
Yes, that's indeed the right command to get voxels of size 0.5x0.5x0.5. (These numbers aren't tied to any physical unit, but you're free to interpret them as mm.)
