### ISSUE TITLE
Other filters than Ram-Lak in FDK_CUDA

### ISSUE THREAD

**Issue by jakobsj** [astra-toolbox/astra-toolbox#105]
It is not clear from the online documentation of FDK_CUDA which filter is used, but line 233 of fdk.cu indicates it is Ram-Lak applied to each detector line. In FBP_CUDA it is possible to specify other filters. Are there any plans to introduce this also in FDK_CUDA? That would be quite useful!

**Comment by wjp** [comment]
In the current development version of astra it is possible to specify a custom filter.
