### ISSUE TITLE
Build fails on Linux without Cuda

### ISSUE THREAD

**Issue by aa-m-sa** [astra-toolbox/astra-toolbox#107]
Noticed today while installing Astra on a new machine that some of the new changes made to the master made since January break the install script for Linux environments (Ubuntu 16.04.1 LTS) without CUDA.

Running
```
cd build/linux
./autogen.sh
./configure --with-matlab=<path-to-my>/MATLAB/R2016b \
                  --prefix=$HOME/astra \
                  --with-install-type=module
make
```
results in the following error (`./configure` output looks good with option `CUDA  : no`, but `make` fails):
```
mkdir -p matlab/mex/.deps
g++ -Wp,-MMD,"matlab/mex/.deps/astra_mex_algorithm_c.d",-MQ,"matlab/mex/astra_mex_algorithm_c.o",-MP  -g -O3 -Wall -Wshadow  -fopenmp -fPIC -DPIC  -I/home/<path-redacted>/MATLAB/R2016b/extern/include -DMATLAB_MEX_FILE -I./../.. -I./../../include -I./../../lib/include -c ./../../matlab/mex/astra_mex_algorithm_c.cpp -o matlab/mex/astra_mex_algorithm_c.o
In file included from ./../../include/astra/../../cuda/2d/astra.h:31:0,
                 from ./../../include/astra/CudaProjector2D.h:34,
                 from ./../../include/astra/ProjectorTypelist.h:43,
                 from ./../../include/astra/AstraObjectFactory.h:37,
                 from ./../../matlab/mex/astra_mex_algorithm_c.cpp:55:
./../../include/astra/../../cuda/2d/fft.h:31:19: fatal error: cufft.h: No such file or directory
compilation terminated.
Makefile:349: recipe for target 'matlab/mex/astra_mex_algorithm_c.o' failed
make: *** [matlab/mex/astra_mex_algorithm_c.o] Error 1
```

Rolled back to the commit bf5475783f2a1bdcddf8426fea136f3b09c61859 (same as when I installed Astra last time) and compiling without CUDA works without errors.

**Comment by wjp** [comment]
Thank you for the report! This should now be fixed by 1714312d072179b74306c927b25bd01b5056bdf1. I wonder why our Travis setup didn't catch this...

**Comment by wjp** [comment]
Ah, Travis not catching this anymore is an unintentional side effect of a27cb41f2d1dda5df3bf783fc5e2010552eb43be. I'll see if we can improve this.

**Comment by aa-m-sa** [comment]
Can confirm that `make` runs without after errors, and the build seems to work without any issues. Thanks for the fix!

**Comment by wjp** [comment]
I improved our travis config to handle this in PR #108, so any future errors like this should now be caught automatically.
