### ISSUE TITLE
astra.astra.use_cuda() returns True even with no GPU

### ISSUE THREAD

**Issue by adler-j** [astra-toolbox/astra-toolbox#109]
See the title.

Astra was installed via

```
conda install -c astra-toolbox astra-toolbox
```

I get

```
>>> astra.astra.use_cuda()
True
```

**Comment by dmpelt** [comment]
I think the code indeed only checks whether ASTRA was compiled with cuda or not. The conda builds are all compiled with cuda, so will always return true even when there is no cuda-capable gpu available.

The current function name is therefore incorrect. We could fix this in two ways:

* Make the function name correct: e.g. `astra.astra.compiled_with_cuda()` or something. Not very useful, but at least correct.
* Fix the function implementation to only return true if ASTRA was compiled with cuda and a cuda-capable gpu is available. I'm not sure how to do this in the easiest way. I think just calling some cuda code will cause a crash, so we would have to figure out whether a gpu is available in some other way (probably getting the number of cuda-capable GPUs from a cuda library). @wjp do you know the best way to do this?

**Comment by wjp** [comment]
I suppose this function as it is now does indeed make little sense when using pre-built conda packages. One easy way would be checking `availableGPUMemory() > 0`. Something like this maybe: 53ee91a377be6542e27d5cfe04ae2335da0c4e73 . (I can't easily test this right now, though)

**Comment by kohr-h** [comment]
I can test this with my laptop later. There is one peculiar scenario I often encounter on my laptop, which happens when I suspend the machine while there is still a CUDA context open. After resuming CUDA cannot talk to the GPU any more.
Currently in this scenario, running ASTRA CUDA code will cause a crash (I have to check if it's a segfault or something else). If the proposed change could capture that, it would be great.

**Comment by adler-j** [comment]
Could we have an update on this change? Would love to see it.

**Comment by wjp** [comment]
This is now in master; `astra.use_cuda()` now returns True only if cuda is actually available at run-time.
