### ISSUE TITLE
ValueError: Attempted relative import in non-package with Python examples

### ISSUE THREAD

**Issue by jellevlassenbroeck** [astra-toolbox/astra-toolbox#11]
If I open an example from the Python samples (using PyCharm on Windows), and add the python/astra folder as content root (to make 'import astra' work), I get the following error:

> C:\Python27\python.exe C:/astra-toolbox/samples/python/s001_sinogram_par2d.py
Traceback (most recent call last):
  File "C:/astra-toolbox/samples/python/s001_sinogram_par2d.py", line 27, in <module>
    import astra
  File "C:\astra-toolbox\python\astra\astra.py", line 27, in <module>
    from . import astra_c as a
ValueError: Attempted relative import in non-package
Process finished with exit code 1

Any suggestions on how to prevent this from occuring?

**Comment by wjp** [comment]
Does it work if you add the python/ folder as content root? (Instead of the python/astra folder?)

**Comment by jellevlassenbroeck** [comment]
In that case, the error just changes

> C:\Python27\python.exe C:/astra-toolbox/samples/python/s001_sinogram_par2d.py
Traceback (most recent call last):
  File "C:/astra-toolbox/samples/python/s001_sinogram_par2d.py", line 27, in <module>
    import astra
  File "C:\astra-toolbox\python\astra\__init__.py", line 26, in <module>
    from . import matlab as m
  File "C:\astra-toolbox\python\astra\matlab.py", line 38, in <module>
    from . import astra_c
ImportError: cannot import name astra_c

Process finished with exit code 1

I am using Python 2.7, no idea if it would be different in 3 ?

**Comment by dmpelt** [comment]
Indeed, when adding astra as a content root, `python/` should be the correct folder to use, as wjp says.

The second error you get is related to the fact that the python->astra C++ extensions do not seem to be present in the `python/astra` folder.

How did you install the toolbox? And can you show us what is inside the `C:\astra-toolbox\python\astra\` folder?

**Comment by jellevlassenbroeck** [comment]
I downloaded the source and compiled it for 32 bit (after manually upgrading to vc120 and CUDA 6.5), I just wondered whether I might not have copied all DLLs to the Python folder. I don't think it is mentioned in the README for the Python case, but I assume that could be the cause. I will check it again.

**Comment by wjp** [comment]
You can also check with our pre-compiled windows/python 2.7 packages ( http://sourceforge.net/projects/astra-toolbox/files/astra-1.6/astra-1.6-python27-win-x64.zip/download ) to see which files we put in that directory ourselves.

**Comment by dmpelt** [comment]
Apparently, compiled python extension files on Windows have a `.pyd` extension instead of `.dll` (see https://docs.python.org/2/faq/windows.html#is-a-pyd-file-the-same-as-a-dll). So I think copying these compiled files to the `python/astra` folder should work:

* algorithm_c.pyd
* astra_c.pyd
* data2d_c.pyd
* data3d_c.pyd
* extrautils.pyd
* log_c.pyd
* matrix_c.pyd
* projector3d_c.pyd
* projector_c.pyd
* utils.pyd

Furthermore, the compiled astra library and the cuda libraries should be somewhere Python can find them as well.

**Comment by jellevlassenbroeck** [comment]
I checked and all the files are there. I also ran the builder.py file, it compiled some things and returned an error since I did not provide arguments. I also put all the astra libraries (8 in total) in the folder with the python files, and even in the python.exe folder.

Where can I find prebuilt binaries including the python files? And maybe I am missing a howto on how to build for Python?

**Comment by jellevlassenbroeck** [comment]
Nevermind for the download location, I just found it and will first try that package before building myself.

**Comment by jellevlassenbroeck** [comment]
I tried it with the binaries (Python 2.7), put the astra folder in the correct folder of the Python installation (I assume) and ran the sample from the command line to prevent any influence from the PyCharm IDE. This is the result:

![clipboard01](https://cloud.githubusercontent.com/assets/6574926/9600570/137a4068-509c-11e5-8de5-e3d6c560fd7b.jpg)

**Comment by wjp** [comment]
It seems your python distribution doesn't have the 'six' module installed. (Out of curiosity, how did you install python?) You should be able to install this using either your python distribution's package manager, or using 'easy_install six' or 'pip install six'.

**Comment by jellevlassenbroeck** [comment]
I just used a bare bone Python compiler from the Python website together with Pycharm, but since I kept on having issues getting packages I am now switching to Anaconda. 

Now it works with both the precompiled as the manually compiled files. Maybe it could be an idea to also add some suggested IDEs with all preinstalled packages to the homepage?
