### ISSUE TITLE
Unified Memory in CUDA

### ISSUE THREAD

**Issue by seirios** [astra-toolbox/astra-toolbox#113]
In using ASTRA for high-resolution micro-CT reconstructions I'm running out of GPU memory. Would it be possible for you to implement Unified Memory in the CUDA primitives so as to take advantage of the CPU memory?

**Comment by Obi-Wan** [comment]
You say you're using the C++ interface, so if your problem is in 3D, why not using the CompositeGeometryManager? It is supposed to split stuff for you (and possibly even on multiple GPUs) :)

**Comment by seirios** [comment]
Thanks for your suggestion! I'll give it a shot. However there's one question: can I use SIRT3D with the CompositeGeometryManager? Looking at the code it seems like not...

**Comment by seirios** [comment]
Never mind. I've implemented SIRT using the CompositeGeometryManager FP and BP operations plus CPU subtraction and weighting. It's slower, due to the repeated copy of a few GiB between the GPU and CPU memories, but it works and answers my initial question. Thanks!
