### ISSUE TITLE
Python: how to get the projection matrix of 3D (cone)

### ISSUE THREAD

**Issue by AceCoooool** [astra-toolbox/astra-toolbox#115]
The sample of the toolbox:
`vol_geom = astra.create_vol_geom(256, 256)
proj_geom = astra.create_proj_geom('parallel', 1.0, 384, np.linspace(0,np.pi,180,False))
proj_id = astra.create_projector('line', proj_geom, vol_geom)
matrix_id = astra.projector.matrix(proj_id)
W = astra.matrix.get(matrix_id)`

but when I "modify" it to:
`vol_geom = astra.create_vol_geom(350, 350, 140)
angles = np.linspace(0, 2 * np.pi, 360, False)
proj_geom = astra.create_proj_geom('cone', 1, 1, 200, 800, angles, 1000, 500)

proj_id = astra.create_projector('cuda3d', proj_geom, vol_geom)  # also try linear3d and linearcone
matrix_id = astra.projector.matrix(proj_id)
W = astra.matrix.get(matrix_id)`

the error of linear3d and linearcone is `error creating projector3d`, and the error of cuda3d is `projector not initialized`

Thank you for your help

**Comment by PranjalSahu** [comment]
How did you solve this issue ?
I am facing similar issues while using 3D projection matrix in python using astra.
Any suggestions would help.

Thank You
