### ISSUE TITLE
adding a complex data type to fbp cuda

### ISSUE THREAD

**Issue by rshpeley** [astra-toolbox/astra-toolbox#125]
How can I add a complex data type to the fbp cuda algorithm? I need the algorithm to accept complex data and to output complex data after reconstruction.
--

**Comment by wjp** [comment]
Would it suffice for you to run FBP separately on the real and imaginary parts of the data? The FBP algorithm is linear over the reals, so that might do what you want.

**Comment by rshpeley** [comment]
I do a Hilbert transform on real data to get its harmonic conjugate, with the idea that all complex processing in the complex back projection algorithm comes to complete solutions.

I have some data from  the tail end of 2015 for a class project using complex processing in matlab with Bangert's algorithm which he derived from Schlegel and Bille. My data shows increased psnr for complex processing over standard real processing.

In the matlab code using Bangert's algorithm the imaginary reconstructed data with no filter provided a similar reconstruction to the real v-filtered reconstruction. In other words, the Hilbert imaginary data in complex back projection processing provided a high pass function. Now, when I put the Hilbert imaginary data through FBP_CUDA with no filter I don't get a good reconstruction giving an rmse of 0.0672 for 180 projections.

I'm trying to nail down what the original matlab code did and reproduce it in python and ASTRA for a paper I'm working on. One of the ways I can see of doing this is for FBP_CUDA to handle complex data.

**Comment by rshpeley** [comment]
Well, I translated Bangert's code into python/numpy/scipy on a cpu and got a working real valued reconstruction, but the imaginary reconstruction doesn't replicate the matlab/octave code. Now I'll cross-check the data against each other... in the morning.

**Comment by rshpeley** [comment]
Just a bit further to go on the conversion but it's now clear that the real and imag parts cannot be broken out and processed separately. Complex backprojection code creates a properly reconstructed image in the imag part of the reconstruction, but two separated parts do not.

Getting back to my original question, how would you suggest I go about modifying the FBP_CUDA code to get complex processing? Modifying the Bangert cpu code was fairly trivial. I have some gpu programming experience with a background in graphics hardware design so I should be able to handle the conversion.

**Comment by rshpeley** [comment]
Still trying to nail this down. In astra processing re and im in parts doesn't work. In Octave/Matlab it does with standard double datatypes. I'll check back in when I find the solution...

**Comment by rshpeley** [comment]
Closing this issue because I do not need complex processing.
