### ISSUE TITLE
GNU Octave bindings

### ISSUE THREAD

**Issue by kalvdans** [astra-toolbox/astra-toolbox#13]
I have an experimental patch at 0813055bf980a2008b5727e62a5b66fe906e2aa3 that will build .oct files if configure finds the 'octave-config' program. In the current form, it needs you to manually create a symlink octave -> matlab in the astra-toolbox root.

I am not sure we want to support building both Octave and Matlab bindings at the same time. Otherwise we can just re-use the matlab rules and just change some make variables when building the octave variant. What do you think?

**Comment by wjp** [comment]
Which version of Octave are you testing with? I'll try to make time to have a look soon.

Someone also reported a problem with mxCreateSharedDataCopy when building for Octave. Did you see this too?

**Comment by kalvdans** [comment]
I have tested with Octave 3.8.1 and only saw the errors with mxLogical which the patch fixes. I should add that I haven't tried to build Matlab bindings after that change (I have no Matlab license).

**Comment by wjp** [comment]
I quickly tested that, and the mxLogical changes are fine for Matlab too.

**Comment by wjp** [comment]
Closing now that PR #73 has been merged.
