### ISSUE TITLE
Forward Projection Error

### ISSUE THREAD

**Issue by esrasmr** [astra-toolbox/astra-toolbox#131]
Hi,

I want to reconstruct anisotropic phantom on ASTRA but I have error from 'astra_create_sino3d_cuda' forward projection step. Error is 'The dimensions of the data do not match those specified in the geometry'.

My phantom size: 12*120*120. It works for 120*120*12 but I cant get satisfactory results from SIRT in this geom. How can I fix it? 

Thanks for this great toolbox !

**Comment by wjp** [comment]
Please have a look at the s006_3d_data sample script to ensure the axis order is correct.

**Comment by esrasmr** [comment]
In this configuration 'column, row, slice (x, y, z)' ,  but I want to change the axis order 'slice,column,row'. 

Because, the projections does not look great. I dont know where I am wrong but I want to just try this.

Thanks for quick reply.

**Comment by wjp** [comment]
You have to make sure that the dimensions you pass to `astra_create_vol_geom` match too (but the axis order for that call is different for historical reasons).

**Comment by esrasmr** [comment]
OK. I understand. Thanks again.
