### ISSUE TITLE
Estimating FPOs (floating-point operations) with 3D ASTRA projector

### ISSUE THREAD

**Issue by tiagoapcramos** [astra-toolbox/astra-toolbox#133]
Good afternoon all,
Is there any documentation regarding the 3D ASTRA toolbox implementation of parallel beam geometries that allow the estimation of the total number of FPOs?
I would like to know, if there is an expression as function of the volume size, detector size, and number of projections.
Many thanks for your aswer
Tiago

*FPOs- Floating-point operations

**Comment by wjp** [comment]
Hi,

The complexity of the implemented forward projection is O( N * D * L ), where N is the number of projections, D is the number of pixels of the detector, and L is the largest (or average) number of volume pixels crossed by a single line. I can't give you the exact constant factor.

The backprojection is O( N * V ), where N is again the number of projections, and V the total number of voxels in the reconstruction volume.

**Comment by tiagoapcramos** [comment]
Thank you very much!
This is enough for what I require so far.
Best regards
Tiago
