### ISSUE TITLE
Problem building astra pyhton 3.5 from source on windows 

### ISSUE THREAD

**Issue by NathanaelSix** [astra-toolbox/astra-toolbox#135]
Following the exact instructions in the readme.md and running "build_python35.bat" gives the following error:

```
"C:\Users\nsix\Desktop\astra_self_compile\astra_vc14.sln" (astra_vc14 target) (1) ->
"C:\Users\nsix\Desktop\astra_self_compile\astra_vc14.vcxproj" (default target) (2) ->
(ClCompile target) ->
 src\Globals.cpp(29): fatal error C1083: Cannot open include file: 'cuda/2d/astra.h': No such file or directory [C:\Us
ers\nsix\Desktop\astra_self_compile\astra_vc14.vcxproj]
```
The referenced file does however exist.

Through Visual studio it can be seen that it is in "Globals.cpp" that this error occurs, due to the line
``` #include "cuda/2d/astra.h"```

I fixed the issue by copying the entire 'cuda\' folder into 'include\'. Doing this allowed the batch files to run and the correct directory to be created in 'site-packages' from WinPython.
The minimal test is then succesful
```
>>> import astra
>>> astra.test()
Getting GPU info... GPU #0: GeForce GTX 1070, with 8192MB
Testing basic CPU 2D functionality... Ok
Testing basic CUDA 2D functionality... Ok
Testing basic CUDA 3D functionality... Ok 
```

However it seems weird that the copying had to be done in the first place (if it is necessary to have some or all cuda headers in the include directory, it could just be placed there from the start, or copied by one of the batch files).

**Comment by wjp** [comment]
Thanks, this should be fixed by 340bd9f683437006d73d8994176cbd27ae541a02.
