### ISSUE TITLE
No plugins directory in astra-1.8-python35-win-x64

### ISSUE THREAD

**Issue by eliemichel** [astra-toolbox/astra-toolbox#136]
I just downloaded the Python release of astra for Windows and could not run it because of a missing 'plugins' folder:

```
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import astra
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Program Files\Python\Python35\lib\site-packages\astra\__init__.py", line 38, in <module>
    from . import plugins
ImportError: cannot import name 'plugins'
```

I fixed the error by copying the 'plugins' directory from the source tree.

**Comment by wjp** [comment]
Thanks for catching this. The script that prepares this downloadable .zip indeed skips the `plugins` subdirectory. I'll fix this soon.

**Comment by vishalvaza** [comment]
@eliemichel It would be great if you share that folder link in this issue. I also faced same issue but unable to find this folder.

**Comment by eliemichel** [comment]
AFAIK it is https://github.com/astra-toolbox/astra-toolbox/tree/master/python/astra/plugins that must be copied to `C:\Python37\lib\site-packages\astra` (adapt path to your setup).

**Comment by vishalvaza** [comment]
> AFAIK it is https://github.com/astra-toolbox/astra-toolbox/tree/master/python/astra/plugins that must be copied to `C:\Python37\lib\site-packages\astra` (adapt path to your setup).

Thank a lot for sharing this link.
