### ISSUE TITLE
DART algorithm in python

### ISSUE THREAD

**Issue by NathanaelSix** [astra-toolbox/astra-toolbox#137]
As far as I can see, the DART algorithm isn't implemented in the python interface, which is a shame. 
1) are there any plans for implementing it / is it already done just waiting for the final upload
2) if it has not been done yet, wouldn't it be a good idea to implement it as part of the C++ interface, so we could create an instance as astra.algorithm.create('DART', options)

If the algorithm has not been implemented in python yet, and the C++ interface is not priority/feasible, I will be happy to make the python part myself and commit it to the toolbox. Just need to be certain that no double work is being done.

**Comment by FENGSHAN95** [comment]
I am also interested how it solved in the end. I think DART will be helpful especially to get the 3D shape of an object.

**Comment by FENGSHAN95** [comment]
> As far as I can see, the DART algorithm isn't implemented in the python interface, which is a shame.
> 
> 1. are there any plans for implementing it / is it already done just waiting for the final upload
> 2. if it has not been done yet, wouldn't it be a good idea to implement it as part of the C++ interface, so we could create an instance as astra.algorithm.create('DART', options)
> 
> If the algorithm has not been implemented in python yet, and the C++ interface is not priority/feasible, I will be happy to make the python part myself and commit it to the toolbox. Just need to be certain that no double work is being done.

Hello, would it be possible for you to share with your code on DART in python?  That will be really appreciated!

**Comment by vishalvaza** [comment]
Hello, would it be possible for you to share with your code on DART in python? That will be really appreciated!

**Comment by soumyadeep1997** [comment]
Hey I would really like your python code for DART if you made it. Thanks a lot in advance !!

**Comment by askorikov** [comment]
Closing, since we do not plan to support DART further, at least in this repository.
