### ISSUE TITLE
opTomo operators / astra_mex_direct in Matlab not working (3D)

### ISSUE THREAD

**Issue by NathanaelSix** [astra-toolbox/astra-toolbox#145]
Attempted use of a 3D opTomo operator in Matlab results in the error:
```
Error using astra_mex_direct_c
Projector not found.

Error in astra_mex_direct (line 22)
    [varargout{:}] = astra_mex_direct_c(varargin{:});

Error in opTomo/opTomo_intrnl3D (line 249)
                y = astra_mex_direct('FP3D', op.proj_id, x);

Error in opTomo/multiply (line 191)
            y = op.funHandle(op, x, mode);

Error in opSpot/applyMultiply (line 96)
                    y(:,i) = op.multiply(x(:,i), mode);

Error in  *  (line 73)
         y = A.applyMultiply(B,1);

Error in test_3D (line 13)
proj = A*cube(:);
```

Same problem can be replicated purely for the astra_mex_direct function. Minimal example resulting in error:
```
>> vol_geom = astra_create_vol_geom(128, 128, 128);
>> proj_geom = astra_create_proj_geom('parallel3d', 1.0, 1.0, 128, 192, linspace2(0, pi, 180));
>> volume = zeros(128, 128, 128);
>> proj_id = astra_create_projector('cuda3d', proj_geom, vol_geom);
>> sino = astra_mex_direct('FP3D', proj_id, volume);

Error using astra_mex_direct_c
Projector not found.
```

The projector id is however recognized by the astra_mex_projector3d module, in the sense that commands like
```
data = astra_mex_projector3d('get_projection_geometry', proj_id);
```
work perfectly fine.

**Comment by NathanaelSix** [comment]
Quick fix: change the 3D code to mimic the 2D code (as it seems to be implemented in python as well) creating the 'FP3D_CUDA' and 'BP3D_CUDA' algorithms seperately and calling them in opTomo_intrnl3D

**Comment by wjp** [comment]
The astra_mex_direct example you give works for me. With which version of astra are you using?

**Comment by NathanaelSix** [comment]
I'm using astra 1.8, but there was another version (I think 1.6) of the astra toolbox also included on the path from another project. Removing the older version fixes the issue.
