### ISSUE TITLE
Import errors in python3

### ISSUE THREAD

**Issue by moosmann** [astra-toolbox/astra-toolbox#15]
Importing astra in python3 results in the following error message:
```
jmoosmann@moosmann:/usr/bin$ python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import astra
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/astra/python/astra/__init__.py", line 26, in <module>
    from . import matlab as m
  File "/usr/local/astra/python/astra/matlab.py", line 38, in <module>
    from . import astra_c
ImportError: /usr/local/astra/python/astra/astra_c.so: undefined symbol: _Py_ZeroStruct
```

This import error is resolved by exporting `LD_PRELOAD` as:
```
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libpython2.7.so
```

However, then following import error occurs:

```
jmoosmann@moosmann:~$ python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import astra
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/astra/python/astra/__init__.py", line 26, in <module>
    from . import matlab as m
  File "/usr/local/astra/python/astra/matlab.py", line 38, in <module>
    from . import astra_c
ImportError: dynamic module does not define init function (PyInit_astra_c)
```
The second import error is also reproduced on another Linux distribution

**Comment by wjp** [comment]
Did you build astra with the right version of python?

**Comment by dmpelt** [comment]
Indeed, to me it seems like during building, the two versions of Python are somehow mixed together. Could you try a `make distclean` and then a completely clean build + install (or simply clone the repository / download the zip again)? Afterwards, can you give us the output of `ldd /usr/local/astra/python/astra/astra_c.so`? That might help a bit to figure out what went wrong.

**Comment by dmpelt** [comment]
I just noticed that you have to use `python3` to use Python 3 on your system. In this case, you would have to specify `--with-python=python3` in ASTRA's `configure` script. When only specifying `--with-python`, it will use the `python` binary (presumably Python 2) during building, which will result in the type of errors that you have.

How did you specify Python in ASTRA's `configure` script?

**Comment by moosmann** [comment]
I also thought the error is somehow related to a mixing of python versions. However, I specified the `--with-python` option. Here's my `configure` command:
```
./configure --with-cuda=/usr/local/cuda --with-matlab=/usr/local/MATLAB/R2014b --with-python=python3 --prefix=/usr/local/astra
```
What I didn't do before is a `make distclean`. I'm just compiling.

**Comment by moosmann** [comment]
Compilation finished, but error persists. Output of `ldd`:
```
jmoosmann@moosmann:~$ ldd /usr/local/astra/python/astra/astra_c.so
	linux-vdso.so.1 =>  (0x00007ffeeb59a000)
	/usr/lib/x86_64-linux-gnu/libpython2.7.so (0x00007f1a4618d000)
	libastra.so.0 => /usr/local/astra/lib/libastra.so.0 (0x00007f1a459ef000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1a456eb000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1a454d5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1a45110000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1a44ef2000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1a44cd9000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1a44ad5000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f1a448d2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1a445cc000)
	libcudart.so.7.0 => /usr/local/cuda/lib64/libcudart.so.7.0 (0x00007f1a4436f000)
	libcufft.so.7.0 => /usr/local/cuda/lib64/libcufft.so.7.0 (0x00007f1a3f313000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1a468f8000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1a3f10b000)
```

**Comment by dmpelt** [comment]
Ok, so it seems that it is indeed linking to the Python 2 library instead of the Python 3 library. At least that explains the errors!

Could you check whether this is not an old astra installation that was built with Python 2, for example by checking that `/usr/local/astra/python/astra/astra_c.so` was recently created? If not, can you give us the parts of the output of the `./configure` run that are relevant to python? And maybe also the output of one of the compilation calls of the python interface part? If it is easier, you can also dump the entire output of `make clean && ./configure ... && make && make install` at https://gist.github.com/ or something.

**Comment by moosmann** [comment]
Oops. I'm sorry, my fault. I was commenting too fast. I forgot to `install` after the last compilation. Now, it works. Thanks a alot.

**Comment by dmpelt** [comment]
Ok, no problem! I am glad that it is working now.
