### ISSUE TITLE
how to set up the rotation axis 

### ISSUE THREAD

**Issue by maximka48** [astra-toolbox/astra-toolbox#150]
Hi! I am using astra on python but a bit confused on how to set the rotation axis position manually for the FBP reconstruction. 
If it is not possible - what is the automatic algorithm and in which source file I can take a look on it? optomo.py doesn't show it in clear manner.

**Comment by Chris-On-PC** [comment]
Hi, did you manage to find a solution/alternative for this?

**Comment by wjp** [comment]
Closing this as it is an old issue. Please open a new discussion (instead of an issue) if this is still a concern.
