### ISSUE TITLE
How to load data?

### ISSUE THREAD

**Issue by povolann** [astra-toolbox/astra-toolbox#151]
Hi,

I have troubles with loading my projection data (images from MC simulation) to Astra toolbox, because I'm not really sure, how should I do it.
I load the data like this in Matlab:
```
% Load projections
% Determine all available image files
files = dir('D:\Programy\astra-1.8\Hlava\*.png');

% Start loop to load images into MATLAB
projections = zeros(256,8,256);
i=0;
for file = files'
   i=i+1;
   obr = imread(fullfile('Hlava',file.name));
   projections(:,i,:) = obr;
end
IMG = im2double(projections,'indexed');
```
But then I'm not really sure how should I proceed with these projections... Because for the cfg.ProjectionDataId I need Id of the projections and not the data itself...
I will be glad for any clarification/hint! Thanks a lot!

**Comment by povolann** [comment]
Ok, thank you. The proj_geom wasn't such a problem :-)

And just to be sure, is the loading of projections part correct? I wasn't sure which type I should use, so I put there double.

**Comment by wjp** [comment]
You're welcome. As for the type: double is fine, but astra will use single internally.
