### ISSUE TITLE
Radon Transform in Matlab

### ISSUE THREAD

**Issue by shreyas-7** [astra-toolbox/astra-toolbox#153]
What parameters should we choose to get identical sinograms obtained with astra and radon function of Matlab? Can we even do that with astra? 
Does that depend on the image? If yes, can we derive it by knowing the size of the image?

Thank you.

**Comment by shreyas-7** [comment]
I solved it

**Comment by lykim200** [comment]
could you share how you solved it? I am looking to generate sinogram using astra, not with radon function from MATLAB.
