### ISSUE TITLE
how to install ,astra

### ISSUE THREAD

**Issue by aljalali** [astra-toolbox/astra-toolbox#154]
Hello friends
I'm running Open astra_vc14.sln in Visual Studio
I encounter the following error
How to solve it

1>------ Build started: Project: astra_mex (astra_mex\astra_mex), Configuration: Release_CUDA x64 ------
2>------ Build started: Project: astra_mex_algorithm, Configuration: Release_CUDA x64 ------
3>------ Build started: Project: astra_mex_data2d, Configuration: Release_CUDA x64 ------
4>------ Build started: Project: astra_mex_data3d, Configuration: Release_CUDA x64 ------
1>astra_mex_c.cpp
1>mexHelpFunctions.cpp
1>mexInitFunctions.cpp
1>astra_mex_c.cpp(33): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
1>mexInitFunctions.cpp(1): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
1>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexHelpFunctions.h(37): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexHelpFunctions.cpp)
1>Done building project "astra_mex_vc14.vcxproj" -- FAILED.
5>------ Build started: Project: astra_mex_matrix, Configuration: Release_CUDA x64 ------
3>astra_mex_data2d_c.cpp
3>mexHelpFunctions.cpp
3>mexCopyDataHelpFunctions.cpp
3>mexDataManagerHelpFunctions.cpp
3>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexCopyDataHelpFunctions.h(31): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexCopyDataHelpFunctions.cpp)
3>mexInitFunctions.cpp
3>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexDataManagerHelpFunctions.h(31): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexDataManagerHelpFunctions.cpp)
3>astra_mex_data2d_c.cpp(32): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
3>mexInitFunctions.cpp(1): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
2>astra_mex_algorithm_c.cpp
2>mexHelpFunctions.cpp
2>mexInitFunctions.cpp
2>astra_mex_algorithm_c.cpp(32): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
2>mexInitFunctions.cpp(1): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
2>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexHelpFunctions.h(37): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexHelpFunctions.cpp)
2>Done building project "astra_mex_algorithm_vc14.vcxproj" -- FAILED.
6>------ Build started: Project: astra_mex_projector, Configuration: Release_CUDA x64 ------
3>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexHelpFunctions.h(37): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexHelpFunctions.cpp)
4>astra_mex_data3d_c.cpp
5>astra_mex_matrix_c.cpp
4>mexHelpFunctions.cpp
4>astra_mex_data3d_c.cpp(32): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
4>mexCopyDataHelpFunctions.cpp
4>mexDataManagerHelpFunctions.cpp
4>mexInitFunctions.cpp
4>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexDataManagerHelpFunctions.h(31): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexDataManagerHelpFunctions.cpp)
4>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexCopyDataHelpFunctions.h(31): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexCopyDataHelpFunctions.cpp)
4>mexInitFunctions.cpp(1): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
4>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexHelpFunctions.h(37): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexHelpFunctions.cpp)
5>mexHelpFunctions.cpp
5>mexInitFunctions.cpp
5>astra_mex_matrix_c.cpp(32): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
5>mexInitFunctions.cpp(1): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
5>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexHelpFunctions.h(37): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexHelpFunctions.cpp)
5>Done building project "astra_mex_matrix_vc14.vcxproj" -- FAILED.
3>Done building project "astra_mex_data2d_vc14.vcxproj" -- FAILED.
7>------ Build started: Project: astra_mex_projector3d, Configuration: Release_CUDA x64 ------
4>Done building project "astra_mex_data3d_vc14.vcxproj" -- FAILED.
8>------ Build started: Project: astra_mex_log, Configuration: Release_CUDA x64 ------
9>------ Build started: Project: astra_mex_direct, Configuration: Release_CUDA x64 ------
6>astra_mex_projector_c.cpp
6>mexHelpFunctions.cpp
6>mexInitFunctions.cpp
6>mexInitFunctions.cpp(1): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
6>F:\astra-1.8\astra\astra-1.8\include\astra/Globals.h(56): fatal error C1083: Cannot open include file: 'boost/static_assert.hpp': No such file or directory (compiling source file astra_mex_projector_c.cpp)
6>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexHelpFunctions.h(37): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexHelpFunctions.cpp)
6>Done building project "astra_mex_projector_vc14.vcxproj" -- FAILED.
8>astra_mex_log_c.cpp
9>astra_mex_direct_c.cpp
9>mexHelpFunctions.cpp
7>astra_mex_projector3d_c.cpp
7>mexHelpFunctions.cpp
7>mexInitFunctions.cpp
8>mexHelpFunctions.cpp
8>mexInitFunctions.cpp
8>astra_mex_log_c.cpp(32): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
8>mexInitFunctions.cpp(1): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
8>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexHelpFunctions.h(37): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexHelpFunctions.cpp)
7>astra_mex_projector3d_c.cpp(33): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
7>mexInitFunctions.cpp(1): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
7>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexHelpFunctions.h(37): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexHelpFunctions.cpp)
9>mexCopyDataHelpFunctions.cpp
9>mexDataManagerHelpFunctions.cpp
9>astra_mex_direct_c.cpp(32): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
9>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexDataManagerHelpFunctions.h(31): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexDataManagerHelpFunctions.cpp)
9>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexCopyDataHelpFunctions.h(31): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexCopyDataHelpFunctions.cpp)
9>mexInitFunctions.cpp
9>mexInitFunctions.cpp(1): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory
9>f:\astra-1.8\astra\astra-1.8\matlab\mex\mexHelpFunctions.h(37): fatal error C1083: Cannot open include file: 'mex.h': No such file or directory (compiling source file mexHelpFunctions.cpp)
8>Done building project "astra_mex_log_vc14.vcxproj" -- FAILED.
7>Done building project "astra_mex_projector3d_vc14.vcxproj" -- FAILED.
9>Done building project "astra_mex_direct_vc14.vcxproj" -- FAILED.
========== Build: 0 succeeded, 9 failed, 0 up-to-date, 0 skipped ==========

**Comment by wjp** [comment]
Do you want to build the matlab interface? If so, have you set up MATLAB_ROOT as described on http://astra-toolbox.com/docs/install.html#windows-from-source-using-visual-studio-2015 ?

**Comment by blauyang** [comment]
> Do you want to build the matlab interface? If so, have you set up MATLAB_ROOT as described on http://astra-toolbox.com/docs/install.html#windows-from-source-using-visual-studio-2015 ?

hello wjp, 

I had the same problem as above when I installed the toolbox. I don't really understand the first few sentences inside the installation instructions." Copy boost headers to lib\include\boost, and boost libraries to lib\x64." I don't understand exactly where to perform these operations. Can you give a detailed version?

Thanks a lot. 

blau

**Comment by wjp** [comment]
These directories `lib\include\boost` and refer to `lib\x64` refer to subdirectories of the ASTRA source tree. The `lib\include` directory already exists, but the `lib\x64` may not.
