### ISSUE TITLE
bugs in

### ISSUE THREAD

**Issue by kackers** [astra-toolbox/astra-toolbox#159]
Dear colleagues,

I am using BP3D_CUDA for backprojection. 
The same code runs well on workstation, but runs strange on my Laptop.(core i7-7820hq,  nvidia quadro m1200, single GPU)
It shows 4 partially reconstructed volumes along Z axis, instead of one completely reconstructed volume.
Maybe ASTRA doesn't support this GPU?
I attached a video of the reconstructed volume for your review.
[reconstruction.zip](https://github.com/astra-toolbox/astra-toolbox/files/2185421/reconstruction.zip)

Problems solved by running the same code in Ubuntu.

Good luck.

**Comment by askorikov** [comment]
Closing as stale. Let us know if that's still relevant.
