### ISSUE TITLE
Visualization of the geometry

### ISSUE THREAD

**Issue by povolann** [astra-toolbox/astra-toolbox#165]
Is there some option how to display the current geometry/set up of source and detector? Something like the picture at slide 10 here http://www.imm.dtu.dk/~pcha/HDtomo/astra-topics.pdf
I'm trying to reconstruct CBCT projections from Varian, but I'm not sure if I am putting there the right shift for the detector...

**Comment by wjp** [comment]
If you are using Matlab, the command `astra_geom_visualize` will give a graphical representation of a geometry. The pictures on that slide were generated in a different way, by creating the forward projection of a cube (or possibly a hollow cube).

**Comment by povolann** [comment]
Oh, thank you! Actually, I didn't have this command in my tools file...
