### ISSUE TITLE
2d projections to 3d volume

### ISSUE THREAD

**Issue by Dacastror** [astra-toolbox/astra-toolbox#166]
Hello everyone,
Currently I am trying to reconstruct a 3d volume from multiple 2d oblique projections, the geometry of my experimental system can not be described with parallel3d, to describe the experimental setup parallel3d_vec is suitable.

The problem is that I do not know how to use Astra to reconstruct a 3d volume from multiple 2d projections. I have the projections stored in a matrix of size [sizex, sizey, num_proyections]. I studied all the examples and documentation that your software provides, but I have not been able to understand how to do what I need. I would be very grateful if you could provide me with a sample code fragment of matlab., in advance I appreciate your help.

**Comment by povolann** [comment]
Hi,

this is how I load 2D pictures to Matlab for the 3D reconstruction.

```
% Load projections
% Determine all available image files
file = dir('D:\Programy\astra-1.8\Fantom\*.png');

% Start loop to load images into MATLAB
i=0;
proj_num = 100;     % number of used projections
krok = 900/proj_num;
% Preparing space for projections
% Coordinate order: column (u), angle, row (v)
projections = zeros(1024,proj_num,768);
for i = 1:krok:900
    obr = imread(fullfile('Fantom',file(i).name)).'; % You need to transpose the projections! Load (rows, columns).
    projections(:,(i+8)/9,:) = -obr;                       % See load proj_data in sample s006
end
IMG = im2double(projections,'indexed'); % Convert Image to Double Precision 
```
And this is how you tell Astra that you want to reconstruct from the loaded images.
```
% Parameters: #rows, #columns, vectors
proj_geom = astra_create_proj_geom('cone_vec', 768, 1024, vectors);
% The matrix must be of size (u,angles,v), where u is the number of columns of the detector
% and v the number of rows as defined in the projection geometry.
proj_id = astra_mex_data3d('create', '-proj3d', proj_geom, IMG);
```
Did it answer your question?
