### ISSUE TITLE
FBP Cuda: Implementation yields wrong values for N>2047 angles

### ISSUE THREAD

**Issue by eboigne** [astra-toolbox/astra-toolbox#167]
Hello,

Interested by using a large number of angles for my application, I have been trying to use the toolbox to reconstruct datasets acquired with up to 3,938 angles. However, I have found that the Cuda implementation of the FBP yields weird values for number of angles higher than 2047. Below is a python code highlighting this.
	
	import numpy as np
	import astra

	pixel_width = 1e-3 #[cm]

	# Define an original phantom of a square of attenuation 1 /cm
	img_original = np.zeros([2500, 2500]).astype('float32')
	img_original[1000:1500, 1000:1500] = 1

	# Compute the Radon transform with 2047 and 2048 angles
	proj_1 = forwardProjection(img_original, 2047)
	proj_2 = forwardProjection(img_original, 2048)

	# Comptue the FBP of the computed projections
	img_1 = backwardProjection(proj_1)
	img_2 = backwardProjection(proj_2)

	# Compare the linear attenuation obtained within the square and the flat part of the image.
	print('Original image values: \t\tsquare - {:+.2f} \tflat - {:+.2f}'.format(img_original[1005,1250],img_original[995,1250]))
	print('Sinogram (N=2047) values:  \tsquare - {:+.2f} \tflat - {:+.2f}'.format(proj_1[1024,1005],proj_1[1024,995]))
	print('Sinogram (N=2048) values:  \tsquare - {:+.2f} \tflat - {:+.2f}'.format(proj_2[1024,1005],proj_2[1024,995]))
	print('FBP image (N=2047) values: \tsquare - {:+.2f} \tflat - {:+.2f}'.format(img_1[1005,1250],img_1[995,1250]))
	print('FBP image (N=2048) values: \tsquare - {:+.2f} \tflat - {:+.2f}'.format(img_2[1005,1250],img_2[995,1250]))

This yields the following output:
	
	Original image values: 		square - +1.00 	flat - +0.00
	Sinogram (N=2047) values:  	square - +0.50 	flat - +0.00
	Sinogram (N=2048) values:  	square - +0.50 	flat - +0.00
	FBP image (N=2047) values: 	square - +1.00 	flat - -0.00
	FBP image (N=2048) values: 	square - +8179.57 	flat - -10.98`

With N=2048 angles, the reconstruction values are off, whereas they are correct when N=2047. I am not sure where this is coming from. Has anyone encountered this elsewhere? Astra version is 1.8.3, python one is 2.7.13.

The functions used to obtain the forward and backward projection are defined as 

	def backwardProjection(sinogram):
		# Compute the FBP of a sinogram using the CUDA implementation and ram-lak filter

		n_angles, n_rays = sinogram.shape
		angles = np.linspace(0, np.pi, n_angles, False)

		proj_geom = astra.create_proj_geom('parallel', 1, n_rays, angles)
		vol_geom = astra.create_vol_geom(n_rays, n_rays, -n_rays/2, n_rays/2, -n_rays/2, n_rays/2)

		rec_id = astra.data2d.create('-vol', vol_geom)
		proj_id = astra.data2d.create('-sino', proj_geom)

		cfg = astra.astra_dict('FBP_CUDA')
		cfg['FilterType'] = 'ram-lak'
		cfg['ReconstructionDataId'] = rec_id
		cfg['ProjectionDataId'] = proj_id

		astra.data2d.store(proj_id, sinogram)

		alg_id = astra.algorithm.create(cfg)
		astra.algorithm.run(alg_id)

		rec = astra.data2d.get(rec_id)
		rec = rec / pixel_width

		astra.algorithm.delete(alg_id)
		astra.data2d.delete(rec_id)
		astra.data2d.delete(proj_id)

		return rec

	def forwardProjection(phantom, n_angles):
		# Compute the Radon transform of the phantom with $n_angles angle increments.

		n_rays = phantom.shape[0]
		angles = np.linspace(0, np.pi, n_angles, False)

		vol_geom = astra.create_vol_geom(n_rays, n_rays)
		proj_geom = astra.create_proj_geom('parallel', 1, n_rays, angles)
		proj_id = astra.create_projector('cuda',proj_geom,vol_geom)

		sino_id, sino = astra.create_sino(phantom*pixel_width, proj_id)

		astra.projector.delete(proj_id)

		return sino

Any help on this would be appreciated.

**Comment by wjp** [comment]
I am unable to reproduce this with the current version 2.0. Please feel free to re-open this issue if it still occurs for you.
