### ISSUE TITLE
FBP GPU-based algorithm reconstructs properly, FBP CPU-based algorithm does not

### ISSUE THREAD

**Issue by physlin** [astra-toolbox/astra-toolbox#168]
I've reconstructed a data set using both the CPU-based and GPU-based FBP algorithms, and the CPU-based one gives artefacts that look very much like those caused by wrapping the sinogram when shifting for a large centre-of-rotation offset. This is definitely not the cause of these artefacts, given the differences between the two algorithms and the very small COR offset. I've attached an image showing the differences between the two algorithms, for the greyscale palette of the full image and also for the greyscale palette around the background region. The images just show a region of the sample container containing only agarose. Reconstructions were done using ASTRA 1.8 in python via TomoPy 1.0.0. CentOS Linux, version 6.5.

![diffcpugpu](https://user-images.githubusercontent.com/23445312/45474152-49653f80-b77c-11e8-8852-6ad7030c67be.png)

**Comment by wjp** [comment]
I am unable to reproduce this with the current version 2.0. Please feel free to re-open this issue if it still occurs for you.
