### ISSUE TITLE
Building astra in Mac OS X

### ISSUE THREAD

**Issue by ProfFan** [astra-toolbox/astra-toolbox#17]
Hi,

I tried building astra in Mac OS X, but it fails with:

```
 linux git:(master) make
cd ../../python; CPPFLAGS=" -I../.. -I../../include -I../../lib/include -stdlib=libstdc++ -mmacosx-version-min=10.6 -DASTRA_PYTHON -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7  -I../include" LDFLAGS=" -g -L/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib  -L../build/linux/.libs" python builder.py install \
    --install-base=./finalbuild --install-headers=./finalbuild --install-purelib=./finalbuild \
    --install-platlib=./finalbuild --install-scripts=./finalbuild --install-data=./finalbuild
running install
error: must supply either prefix/exec-prefix/home or install-base/install-platbase -- not both
make: *** [py] Error 1
```

I tried removing the `prefix` and `exec-prefix` variables from the Makefile with no luck.

Do you have any ideas on this issue?

**Comment by dmpelt** [comment]
First of all, sorry for the late reply!

It seems that in some configurations (maybe OSX), distutils uses a preset global `install.prefix` setting that might be interfering here (see https://github.com/pynbody/pynbody/issues/68). Getting rid of this global setting temporarily might solve the problem. Another possibility would be to use the undocumented `make python-root-install` option of the ASTRA toolbox, which will try to install the python interface to the system python installation (i.e. use something like `python setup.py install`). You may need root access for this option, depending on how Python was installed.

**Comment by ProfFan** [comment]
Thank you very much :) I finally decided to go to linux and everything's fine then.

**Comment by ProfFan** [comment]
So after a whole year I am here to share my latest results. On my machine with CUDA and python 2.7, I need to do the following to make ASTRA work:

1. `ln -s /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy /usr/local/include` to make numpy headers available to ASTRA;
2. `./configure --with-python --with-install-type=module --with-cuda=/Developer/NVIDIA/CUDA-8.0`;
3. `make` and `make install`;
4. Test. If it complains about missing library, symbolic link the corresponding files.

**Comment by wjp** [comment]
Thank you for the report.

On our side I've borrowed a MacBook a few weeks ago, and managed to build experimental conda python packages for macOS (cuda + python 3.5 for now): see PR #92 .

**Comment by ProfFan** [comment]
Excellent work! Maybe numpy include path could be automatically detected using autotools?
