### ISSUE TITLE
Problem building with custom python location

### ISSUE THREAD

**Issue by meetaig** [astra-toolbox/astra-toolbox#172]
I am facing a problem when trying to install from source to my anaconda python. I am aware of the `conda` channel install, but I want to install from source for possible customization in the future. 
I think what is happening is that the path to the python3.7m library is not parsed correctly. Below a snippet from the command line output when trying to build (I am running Linux Mint 18.1 and am installing with CUDA 9.2) 
```
g++ -Wp,-MMD,"matlab/mex/.deps/astra_mex_plugin_c.d",-MQ,"matlab/mex/astra_mex_plugin_c.o",-MP  -g -O3 -Wall -Wshadow  -fopenmp -fPIC -DPIC  -I/usr/local/cuda-9.2/include -DASTRA_CUDA -I/usr/local/MATLAB/R2017b/extern/include -DMATLAB_MEX_FILE -DASTRA_PYTHON -I/home/tim/anaconda3/include/python3.7m -I./../../include -I./../../lib/include -c ./../../matlab/mex/astra_mex_plugin_c.cpp -o matlab/mex/astra_mex_plugin_c.o
/usr/local/MATLAB/R2017b/bin/mex LDFLAGS="\$LDFLAGS  -g  -L/usr/local/cuda-9.2/lib64 -fopenmp -L/mnt/LinuxData/astra-public/build/linux/.libs -Wl,-rpath,'\$ORIGIN'" -cxx -DASTRA_CUDA  -lpthread -lcudart -lcufft -lut -l`basename /home/user/anaconda3/include/python3.7m` -lastra -output matlab/mex/astra_mex_plugin_c matlab/mex/astra_mex_plugin_c.o matlab/mex/mexHelpFunctions.o matlab/mex/mexCopyDataHelpFunctions.o matlab/mex/mexInitFunctions.o matlab/mex/mexDataManagerHelpFunctions.o
```
The crucial part being: -l\`basename /home/user/anaconda3/include/python3.7m\` where the path to the python lib is pasted after a `-l`, which seems to indicate the path is not parsed correctly. I use the following configuration command:
```
./configure \
    --with-cuda=/usr/local/cuda-9.2\
    --with-matlab=/usr/local/MATLAB/R2017b\
    --with-python=/home/user/anaconda3/bin/python\
    --prefix=$HOME/astra\
    --with-install-type=module
```
I am unfortunately not super familiar with autoconf and related tools, so I am having a hard time looking for the part where the path is parsed. Is there a way of correcting this?

Any help would be appreciated!
Thanks in advance.

**Comment by meetaig** [comment]
/usr/local/MATLAB/R2017b/bin/mex LDFLAGS="\$LDFLAGS  -g  -L/usr/local/cuda-9.2/lib64 -fopenmp -L/mnt/LinuxData/astra-public/build/linux/.libs -Wl,-rpath,'\$ORIGIN'" -cxx -DASTRA_CUDA  -lpthread -lcudart -lcufft -lut -l`basename /home/user/anaconda3/include/python3.7m` -lastra -output matlab/mex/astra_mex_plugin_c matlab/mex/astra_mex_plugin_c.o matlab/mex/mexHelpFunctions.o matlab/mex/mexCopyDataHelpFunctions.o matlab/mex/mexInitFunctions.o matlab/mex/mexDataManagerHelpFunctions.o
Building with 'g++'.
/usr/bin/ld: cannot find -lpython3.7m
collect2: error: ld returned 1 exit status

**Comment by wjp** [comment]
It looks like I forgot to add a `-L` option for the python library. I've just added this to master (commit f84f0c623cd2652fcf80ec47cb287cc29fd430c5 ). I do wonder if this will also need an extra rpath on your setup, so it might not work directly. Please let me know what happens.

**Comment by meetaig** [comment]
I just ran the compile and it seems like that was indeed the problem. The build ran through without troubles. Tests are successful:
```
import astra
astra.test_CUDA()
Getting GPU info... GPU #0: GeForce GTX 1080 Ti, with 11175MB
Testing basic CPU 2D functionality... Ok
Testing basic CUDA 2D functionality... Ok
Testing basic CUDA 3D functionality... Ok
```
