### ISSUE TITLE
CUDA version dependancy

### ISSUE THREAD

**Issue by llionevans** [astra-toolbox/astra-toolbox#176]
I'm trying to setup a few things using conda on ubuntu 18.04

I have installed astra-toolbox using `conda install -c astra-toolbox astra-toolbox` to do reconstructions.
For CT segmentation I'm now also trying to install SuRVoS using `conda install -c conda-forge -c numba -c ccpi survos`

I get the following error
`Solving environment: failed`
`UnsatisfiableError: The following specifications were found to be in conflict:`
`  - libastra -> cudatoolkit=8.0`
`  - survos -> cudatoolkit==9.0`

The version of CUDA installed is 9.0, so astra-toolbox seemingly works with it fine with it. Is there a way of overriding this, or changing a parameter in libastra to say that CUDA 9.0 is fine?

Thanks in advance for your help.

**Comment by llionevans** [comment]
Ah, I see that the nvidia CUDA toolkit (v9) is a different thing to the CUDA toolkit installed by anaconda (v8). So astra-toolbox isn't using CUDAv9. Does this mean that I can't have astra-toolbox and SuRVoS in the same conda environment?

**Comment by meetaig** [comment]
I don't exactly know what is contained in the conda package, but I have astra running with CUDA 9.1, so it definitely can work. Have you tried installing from source? Then you can customize the cuda library and which python interpreter is used. If you want to install it to your conda environment, you can provide the path to the interpreter to the `--with-python` option.

**Comment by llionevans** [comment]
I'd rather not use conda at all. I'm now trying to install from source (which is my preferred method in any case) but I get the error below when I run 'make'.

I changed `--with-cuda=/usr/local/cuda` to `--with-cuda=/usr/bin/nvcc` because that's the output of `what nvcc`.

This should really be a new issue, please let me know if you want me to create a new one rather than continue here.

```
mkdir -p src/.deps
./libtool --mode=compile --tag=CXX g++ -Wp,-MMD,"src/.deps/Algorithm.d",-MQ,"src/Algorithm.lo",-MP  -g -O3 -Wall -Wshadow   -I/usr/bin/nvcc/include -DASTRA_CUDA -DASTRA_PYTHON -I/usr/include/python2.7 -I./../../include -I./../../lib/include -c ./../../src/Algorithm.cpp -o src/Algorithm.o
libtool: compile:  g++ -Wp,-MMD,src/.deps/Algorithm.d,-MQ,src/Algorithm.lo,-MP -g -O3 -Wall -Wshadow -I/usr/bin/nvcc/include -DASTRA_CUDA -DASTRA_PYTHON -I/usr/include/python2.7 -I./../../include -I./../../lib/include -c ./../../src/Algorithm.cpp  -fPIC -DPIC -o src/.libs/Algorithm.o
cc1plus: error: /usr/bin/nvcc/include: Not a directory
Makefile:366: recipe for target 'src/Algorithm.lo' failed
make: *** [src/Algorithm.lo] Error 1
```

**Comment by wjp** [comment]
The argument to `--with-cuda` should be the prefix for cuda (usually `/usr/local/cuda`). If `nvcc` is `/usr/bin/nvcc`, you possibly need `--with-cuda=/usr`, but it does depend on where the cuda headers are installed on your system.

P.S. The astra development conda packages available from the `astra-toolbox/label/dev` channel do have versions for cudatoolkit==9.0. (`conda install -c astra-toolbox/label/dev astra-toolbox`)

**Comment by llionevans** [comment]
I think `make` worked, but it stopped at `make install`

Here's the last part of the output. Why is it referring to python2.7 when I only have python3 installed? Do I need to change something in the configure stage to point at python3?

```
running build
running build_py
running build_ext
running install
running install_lib
creating /usr/local/lib/python2.7/dist-packages/astra
error: could not create '/usr/local/lib/python2.7/dist-packages/astra': Permission denied
Makefile:509: recipe for target 'install-python-site-packages' failed
make: *** [install-python-site-packages] Error 1
```

**Comment by wjp** [comment]
Did you have the right conda environment activated throughout the build process (during configure, make, and make install)?

The configure process detects which python binary to use (by default just `python`, which then depends on your `$PATH`). You can see the result near the end of the configure run (`checking for python... python`).

Are you maybe using root/sudo to run `make install`? That might cause unintended side-effects, and is unnecessary if you're installing astra into a conda environment.

**Comment by llionevans** [comment]
I'm trying to do this without conda. conda causes all sorts of problems with other packages.

Ok, somehow python2.7 got installed (which I don't want). I've now removed it.

When I do configure again I get `checking for python... configure: error: Python binary not found
`
How do I point it to python3?

**Comment by wjp** [comment]
If your python 3 binary is called `python3`, you can use `--with-python=python3` .

**Comment by llionevans** [comment]
Thanks, that got it to point to the right python. I'm now back at the permission error. I'm not using sudo

```
running build
running build_py
running build_ext
running install
running install_lib
creating /usr/local/lib/python3.6/dist-packages/astra
error: could not create '/usr/local/lib/python3.6/dist-packages/astra': Permission denied
Makefile:509: recipe for target 'install-python-site-packages' failed
make: *** [install-python-site-packages] Error 1
```

**Comment by llionevans** [comment]
should it maybe be installed under /usr/lib/python3/dist-packages ?
Because there are lots of stuff already in that directory but nothing in /usr/local/lib/python3.6/dist-packages/

**Comment by wjp** [comment]
If you want to install it system-wide, you should in fact be using sudo, since that does require root permissions. (Sorry for the confusion; I was assuming you wanted to install it into a conda environment because of the very first post.)

The location should be correct, but you can double-check by running `python3 -c 'import sys; print(sys.path)'` to see if it is in python's search path.

**Comment by sharatha23** [comment]
Is there any way that we could use ASTRA toolbox on laptops with windows 10 and no CUDA support? Because I have got a Radeon Graphics Card on my system.
