### ISSUE TITLE
ASTRA crash at: vol_id = astra_mex_data3d('create','-vol',vol_geom,0);

### ISSUE THREAD

**Issue by bmuralik1** [astra-toolbox/astra-toolbox#181]
hi

I am new to ASTRA and am trying to get my code to run on the GPU. I am attaching a code snippet here:

    vol_geom = astra_create_vol_geom(numel(crop_w),numel(crop_w),numel(crop_h));
    proj_geom = astra_create_proj_geom('cone', 1, 1, numel(crop_h), numel(crop_w), angles_final, source_origin/pix_eff, 0);
    proj_id = astra_mex_data3d('create','-proj3d', proj_geom, I_3D);  
    vol_id = astra_mex_data3d('create','-vol',vol_geom,0); 

Matlab crashes on the last line - but not always. Out of possibly 30 tries, the code has run maybe once or twice, but crashes the rest of the time. I would appreciate any help please.

thanks.
bala

**Comment by wjp** [comment]
I am unable to reproduce this with the current version 2.0. Please feel free to re-open this issue if it still occurs for you.
