### ISSUE TITLE
Conda package does not include geom_size

### ISSUE THREAD

**Issue by 3cHeLoN** [astra-toolbox/astra-toolbox#185]
I installed astra using "conda install -c astra-toolbox astra-toolbox", however, when I use "astra.geom_size" I get an error message saying that module 'astra' has no attribute 'geom_size'.

**Comment by LongHanVisazure** [comment]
conda will install astra-toolbxo @v1.8.3, it comes out with a different grammar of geom_size. astra.geom_size is new grammar in v1.9.0
