### ISSUE TITLE
import **_c Problem

### ISSUE THREAD

**Issue by FENGSHAN95** [astra-toolbox/astra-toolbox#186]
After conda install, there is a problem to import a set of **_c, for example astra_data2d_c.
Is it due to the transfer from C++ to Python?

**Comment by FENGSHAN95** [comment]
After conda install, there is a problem to import a set of **_c, for example astra_data2d_c.
Is it due to the transfer from C++  to Python?

**Comment by wjp** [comment]
Please give the full error message you're getting.
