### ISSUE TITLE
Error messages when performing reconstruction

### ISSUE THREAD

**Issue by kabukii93** [astra-toolbox/astra-toolbox#187]
Hey everyone,

I have troubles performing a recontruction with the  ASTRA toolbox in MATLAB.
The projection data id I define as

`proj_id = astra_mex_data3d('create','-proj3d',proj_geom,stack);`

where `stack` is a 256x256x72 image stack of my experimental data loaded into MATLAB and proj_geom is defined as

`proj_geom = astra_create_proj_geom('parallel3d',1,1,256,256,tilt_angles);`

where `tilt_angles` are my 72 experimental tilt angles loaded into MATLAB.

The rest of my code ist exactly as shown in the video tutorial for the ASTRA toolbox.

However when I run this code I get the following error messages:

`Error using astra_mex_data3d_c
The dimensions of the data do not match those specified in the
geometry.`

`Error in astra_mex_data3d (line 22)
    [varargout{:}] = astra_mex_data3d_c(varargin{:});`

`Error in astra_reconstruction3D (line 34)
proj_id = astra_mex_data3d('create','-proj3d',proj_geom,stack);`

As I am new to the ASTRA toolbox I have no idea how to solve this problem.
I will be glad for any help! Thanks a lot in advance!

**Comment by wjp** [comment]
Hi,

ASTRA has the projection index as the middle coordinate, so your stack should be 256x72x256.

**Comment by kabukii93** [comment]
Thanks a lot! Now it is working.
I was not expecting that the problem can be solved so easily :)

**Comment by wjp** [comment]
Glad to hear it. You're welcome.
