### ISSUE TITLE
Unable to create 'fanflat' geometry projector

### ISSUE THREAD

**Issue by chernyz** [astra-toolbox/astra-toolbox#188]
I am now experimenting with the package (and it's kind great!).
But I can't create a projector that uses 'fanflat' projection, I just get the exception:
`astra/projector_c.pyx in astra.projector_c.create()`
`Exception: Unable to initialize Projector2D.`

The code that generates the error is:

import astra
import numpy as np

n_x, n_y = (256,256) 
vol_geom = astra.create_vol_geom(n_x, n_y, -0.5, 0.5, -0.5, 0.5) 
proj_geom = astra.create_proj_geom('fanflat', 0.01, 10, np.linspace(0,2*np.pi,4,False) + 0.1, 2, 2)
proj_id = astra.create_projector('line', proj_geom, vol_geom)

Thanks for the great module!

**Comment by meetaig** [comment]
Hi, glad the toolbox is working for you!
For the `fanflat` geometry, you have to use a separate line projector. For parallel beam you use `line`, if you're using `fanflat` change it to `line_fanflat`. On my machine changing the type to that makes the code run without errors. 
If you want to try out more projectors and such, feel free to look around in the documentation:
http://astra-toolbox.com/docs/proj2d.html

Let me know if that helped! :)

**Comment by chernyz** [comment]
That did the trick! thanks!

**Comment by meetaig** [comment]
You're welcome!
