### ISSUE TITLE
How to load a dataset of real projections to reconstruct in Python?

### ISSUE THREAD

**Issue by liebertrj** [astra-toolbox/astra-toolbox#189]
Can someone help me with an example of how to load my real projection dataset, which are TIF images, instead of a phantom using python?

**Comment by meetaig** [comment]
Hello,
you can load your data into a numpy array and then pass it into one of the data classes of ASTRA (i.e., `astra.data3d`). The reconstruction depends on the geometry parameters of the real data that you took. If you can define the geometry, you can in theory use any reconstruction algorithm in ASTRA.
