### ISSUE TITLE
Specify CUDA host compiler during build

### ISSUE THREAD

**Issue by kohr-h** [astra-toolbox/astra-toolbox#19]
My problem is that I installed Fedora on my machine, where GCC 5.x is the standard since quite a while. Unfortunately, CUDA won't cooperate with it, and I have no idea of their plans to make it compatible.

Therefore, it would be nice if one could specify the compiler that should be used by `nvcc` as host compiler. The environment variable `CC` is happily ignored, so that doesn't help. However, `nvcc` takes an option `--compiler-bindir` where the location of a host compiler different from the default one can be specified. I guess that's how CMake solves this issue, there one can define a variable `CUDA_HOST_COMPILER` to work around this issue.

Would be cool if there was a config option like `--cuda-host-compiler-bindir` which would simply redefine `$NVCC` as `$NVCC --compiler-bindir <bindir>`. Way better than my current hacky solution to replace `/usr/local/cuda/bin/nvcc` by a script injecting that option with hard-coded path into the call to the real `nvcc`.

**Comment by kohr-h** [comment]
Or, even better, use the path of `CC`.

**Comment by wjp** [comment]
Would it work for you if I add the option of specifying NVCCFLAGS to configure, similar to how you can specify CXXFLAGS?

**Comment by kohr-h** [comment]
That should definitely work!

**Comment by kohr-h** [comment]
Replacing the empty `NVCCFLAGS` in `configure.ac` with `NVCCFLAGS="--compiler-bindir $CC"` also works, I just tested it. Is there any reason to specify `CC` and the CUDA host compiler separately? Would that even make sense? If not, than that's my suggested solution.

**Comment by kohr-h** [comment]
Patch comes here, just in case:
```diff
diff --git a/build/linux/configure.ac b/build/linux/configure.ac
index 85e4324..6da8e45 100644
--- a/build/linux/configure.ac
+++ b/build/linux/configure.ac
@@ -124,7 +124,7 @@ if test x"$NVCC" != xno; then
   AC_SUBST(NVCC)
 fi
 
-NVCCFLAGS=""
+NVCCFLAGS="--compiler-bindir $CC"
 if test x"$HAVECUDA" = xyes; then
   AC_MSG_CHECKING([if nvcc works])
   ASTRA_CHECK_NVCC(HAVECUDA,NVCCFLAGS)
```

**Comment by wjp** [comment]
I'm a bit hesitant to change that, since I can't see if that will have any unexpected side effects.

In any case, user-specified NVCCFLAGS are now accepted by configure ( 34bab2b0caa6ee955d5d2f7882a6cd36cf142536 ).

**Comment by kohr-h** [comment]
Fine with me!
