### ISSUE TITLE
Exception: Unable to initialize Algorithm.

### ISSUE THREAD

**Issue by lxaibl** [astra-toolbox/astra-toolbox#190]
Hi,

I am trying to use FDK algorithms. Part of the codes are look like this:
angles=np.linspace(0, 10/9*np.pi, 367, False)
proj_geom=astra.create_proj_geom('cone',30/192,40/256,192,256,angles,100,50)#cm
vol_geom=astra.create_vol_geom(470,290,65)
proj_id=astra.data3d.create('-proj3d',proj_geom,y_arr)
rec_id=astra.data3d.create('-vol',vol_geom)
cfg=astra.astra_dict('FDK_CUDA')
cfg['ReconstructionDataID']=rec_id
cfg['ProjectionDataId']=proj_id
alg_id=astra.algorithm.create(cfg)

But it causes an error "Exception: Unable to initialize Algorithm." from the last code. 
Any idea?

**Comment by PranjalSahu** [comment]
I am facing the same error. Please help !

**Comment by wjp** [comment]
Above the exception ASTRA should in theory have printed an error message describing the issue. In this case there is a typo in `ReconstructionDataId`. (`ID` instead of `Id`).
