### ISSUE TITLE
Inconsistent result of line and strip model in forward projection of fan beam CPU

### ISSUE THREAD

**Issue by jakeoung** [astra-toolbox/astra-toolbox#191]
I use the developer version from conda. When I use the forward projection of fan beam in CPU, its results have different orientation, depending on the line or strip model:

This is the result of line model:
![line model](https://d2mxuefqeaa7sj.cloudfront.net/s_446BEE12BC9C367F19F9D1DADD7B58F67EC03688CAC8376743C99398FF027366_1552843258863_recon.png)

This is the result of strip model:
![strip model](https://d2mxuefqeaa7sj.cloudfront.net/s_446BEE12BC9C367F19F9D1DADD7B58F67EC03688CAC8376743C99398FF027366_1552843653659_recon.png)

**Comment by wjp** [comment]
Thanks for catching this. I missed the fan strip projector when fixing fan beam code consistency earlier.

I've flipped the detector orientation for this projector (138aab6a3760c504d032717dfd2b64fd321418e8), and have also added unit tests for the entire strip projector family (4b9bc545e0b22188fb2c39f5981935a96a0bbfe9).

The fan strip unit tests still fail with a few slightly too large numerical deviations that I need to investigate further.

**Comment by wjp** [comment]
It appears there's a missing weighting factor in fan/strip that will cause deviations, especially for larger fan angles. I hope to fix this soon.

**Comment by wjp** [comment]
That's now fixed too by 667a390d94ad3b3ee706f9598a707376d9604810.
