### ISSUE TITLE
SIRT 2D and SIRT 3D

### ISSUE THREAD

**Issue by ercius** [astra-toolbox/astra-toolbox#192]
I have a questions regarding a comparison between the SIRT 2D and SIRT 3D CUDA implementations.

When I compare reconstructions of these two algorithms I see some small (but not tiny) differences in the final reconstruction of the exact same slices. It could just be precision of the calculation or something else insignificant, but I wanted to inquire regarding the implementation of these two algorithms.

Ultimately, I want to use the 3D algorithm to reconstruct a large dataset which can not fit into the GPU memory. Im worried that at the borders of the chunks reconstructed using the 3D case would cause some issues.

1) Are the 2D and 3D algorithms identical and the 3d version is only mean to transfer the data all at once to the GPU to make it faster? It is definitely faster.
Or
2) Are the algorithms fundamentally different in that the 3D will take into account all data in the set of sinograms? Thus, reconstructing subsets and merging them is not recommended.

**Comment by wjp** [comment]
Dear Peter,

The 2D and 3D SIRT CUDA algorithms are in some sense identical, but the 3D version does take into account all data. Apart from the data transfer issue, the main purpose of the 3D algorithm is to also allow reconstructions for geometries that can not be split into slices, such as cone beam or laminography.

In more detail, the 3D SIRT CUDA algorithm processes the full 3D data set, and for the forward projection step does interpolation in the full 3D volume, and for the backprojection step interpolation in full projection images. That said, if the detector rows are perfectly aligned with slices of the reconstruction volume, this interpolation is effectively the same as the interpolation done by the 2D SIRT CUDA algorithm, and any differences in the output should be limited to numerical issues.

**Comment by ercius** [comment]
Thanks for the information! I'll try chunking the data and see if there are any noticable errors are the boundary. I guess I really just need a bigger graphics card 😀
