### ISSUE TITLE
astra on google colab

### ISSUE THREAD

**Issue by adler-j** [astra-toolbox/astra-toolbox#194]
Google colab is an online jupyter notebook-like service that runs in the cloud and allows users _free_ access to a GPU. For obvious purposes this is quite useful as a learning tool and to let users access code that needs a GPU even when they don't personally own one.

It seems that pip installable libraries can be trivially installed, see e.g.

```
!pip install git+https://github.com/odlgroup/odl.git
```

On the other hand conda is not supported (out of the box).

Has anyone been able to install astra in colab? In that case, how?

Edit: Link for convenience https://colab.research.google.com

**Comment by dmpelt** [comment]
We used to have a pip package for astra for a while, but I'm not sure what the current status of that is... 

Is it easy to figure out cuda versions and library locations etcetera in colab so that we can use them during compilation? If so, it might not be too difficult to create a pip package (or just a set of commands) to install astra with...

**Comment by adler-j** [comment]
> Is it easy to figure out cuda versions and library locations etcetera in colab so that we can use them during compilation?

It is easy to figure out but knowing google the risk is that they will update cuda etc quite often, so it would be nice to have a long-term stable package for this.

With that said this might be a reasonably workable short term solution. Another option would be to somehow hack an install from conda. I tried just downloading the zipped sources from conda but got weird errors sadly, probably due to version miss-matches.

**Comment by wjp** [comment]
This looks pretty nice; thanks for pointing it out. It seems their system currently at least has nvcc and gcc binaries in PATH (and compatible versions of both too), so there's a chance a pip source package will build ok there. Sounds like we should try to get this pip package up to date.

**Comment by adler-j** [comment]
Obviously building it directly in colab would be the most long-term stable solution. Do you think this would be doable?

I think getting astra up on colab could realy help adoption, especially in e.g. university courses.

**Comment by adler-j** [comment]
Related to this, I've managed to get CUDA accelerated ASTRA to run on Kaggle:

https://www.kaggle.com/jonasadler/odl-tomography-example

**Comment by adler-j** [comment]
I was doing something totally unrelated, and stumbled [upon this link](https://facebookresearch.github.io/TensorComprehensions/installation_colab_research.html) which shows that astra can be installed in coda as such:

```
!wget -c https://repo.continuum.io/archive/Anaconda3-5.1.0-Linux-x86_64.sh
!chmod +x Anaconda3-5.1.0-Linux-x86_64.sh
!bash ./Anaconda3-5.1.0-Linux-x86_64.sh -b -f -p /usr/local
!conda install -q -y --prefix /usr/local -c astra-toolbox/label/dev astra-toolbox

import sys
sys.path.append('/usr/local/lib/python3.6/site-packages/')
```

Example Colab here:

https://colab.research.google.com/drive/1wsHNyuK0GAM8sh9kBTzwh8t6Kuivj1KW

As I see it, this is a rather huge win since now you can simply refer e.g. students to run any ASTRA course online using Google GPUs. Maybe you should add it to the instructions somewhere, I might add it to ODL.

**Comment by askorikov** [comment]
Thanks for the useful tip! The only thing: currently, the latest development version of Astra depends on Python 3.7, whereas Google Colab runs Python 3.6. I had to modify the code snippet to explicitly specify the needed Python version in the following way:
```
!wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!chmod +x Miniconda3-latest-Linux-x86_64.sh
!bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/local -f
!conda install -q -y -c astra-toolbox/label/dev astra-toolbox python=3.6
import sys
sys.path.append('/usr/local/lib/python3.6/site-packages')
```

**Comment by askorikov** [comment]
Also, after installing the missing `automake` and `libtool` dependencies, it turns out to be possible to install Astra with `pip`:
```
!apt-get install automake libtool
!pip install astra-toolbox
```
and build it from source:
```
!apt-get install automake libtool
!git clone https://github.com/astra-toolbox/astra-toolbox
%cd astra-toolbox/build/linux
!./autogen.sh
!./configure --with-cuda=/usr/local/cuda \
             --with-python \
             --with-install-type=module
!make -j2
!make install
```
Installing pre-built binaries with Conda is still the fastest solution though.

**Comment by adler-j** [comment]
Thanks for the excellent update, that looks like a good solution. Overall I'm quite optimistic about having colab as officially supported. It helps so much, especially for students and new starters.

**Comment by I0x0I** [comment]
I have Astra run in Colab with the following setup
```python
# Install conda
!pip install -q condacolab
import condacolab
condacolab.install()
# Install astra-toolbox
!conda install -c astra-toolbox astra-toolbox
# Install odl
!pip3 install https://github.com/odlgroup/odl/archive/master.zip
```

**Comment by wjp** [comment]
For the latest astra 2.2.0 we've uploaded binary wheels to PyPI, so this should now work too:
```
!pip3 install astra-toolbox
```
