### ISSUE TITLE
Compiling issues with newer MATLAB versions > R2017b

### ISSUE THREAD

**Issue by n1kt0** [astra-toolbox/astra-toolbox#197]
Hello,
The mex interfaces changed at least since MATLAB R2018b, didn't test with R2018a. This causes the compiling of mex interfaces to fail. I tried to introduce the flag "-R2017b" proposed by the compiler to compile to compile against the old interfaces but this didn't help, although the flag is visible in the output of the compiling step.

**Comment by PavelParamonov** [comment]
Hi @n1kt0 
check out please #149 issue. In short, you need to add -DMATLAB_MEXCMD_RELEASE=700 compilation flag.

**Comment by n1kt0** [comment]
Thanks for pointing out, should have searched better the issue list.
