### ISSUE TITLE
Issue with astra compiled for MATLAB R2019a -> findOrFail: no active context for type 'std::shared_ptr<InterruptStateData>'

### ISSUE THREAD

**Issue by n1kt0** [astra-toolbox/astra-toolbox#198]
Hello again,
Some days ago I tried to get the astra-toolbox working for MATLAB R2018b and R2019a on CentOS Linux release 7.6.1810 (Core) and experienced some compiling issue which can be sorted out via [#149](https://github.com/astra-toolbox/astra-toolbox/issues/149) for the mentioned MATLAB versions. 

I did tests before in MATLAB R2017b with a 2d reconstruction script from the samples folder which I also ran after compilation for the newer MATLAB versions (R2018b, R2019a). For R2018b this script was also working but running this script with R2019a throws an error which I pasted below.

`--------------------------------------------------------------------------------
              Assertion detected at Fri Apr 26 14:53:07 2019 +0200
--------------------------------------------------------------------------------

Configuration:
  Crash Decoding           : Disabled - No sandbox or build area path
  Crash Mode               : continue (default)
  Default Encoding         : UTF-8
  Deployed                 : false
  Desktop Environment      : KDE
  GNU C Library            : 2.17 stable
  Graphics Driver          : Unknown hardware 
  Graphics card 1          : 0x8086 ( 0x8086 ) 0x3e9b Version 0.0.0.0 (0-0-0)
  Graphics card 2          : 0x10de ( 0x10de ) 0x1c8c Version 418.56.0.0 (0-0-0)
  Java Version             : Java 1.8.0_181-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  MATLAB Architecture      : glnxa64
  MATLAB Entitlement ID    : 4671014
  MATLAB Root              : /usr/local/MATLAB/R2019a
  MATLAB Version           : 9.6.0.1072779 (R2019a)
  OpenGL                   : hardware
  Operating System         : "CentOS Linux release 7.6.1810 (Core) "
  Process ID               : 16877
  Processor ID             : x86 Family 6 Model 158 Stepping 10, GenuineIntel
  Session Key              : 80e9f1dc-ba4b-46a0-b828-6821db1c90c9
  Static TLS mitigation    : Enabled: Full
  Window System            : The X.Org Foundation (12001000), display :0

Fault Count: 1

Assertion in findOrFail at management.cpp line 721:
findOrFail: no active context for type 'std::shared_ptr<InterruptStateData>'

Register State (captured):
  RAX = 00ff00000000ff00  RBX = 00007fcc458fed08
  RCX = 0000000000000000  RDX = 00007fcc458efe00
  RSP = 00007fca3c5d9ec0  RBP = 00007fca3c5da280
  RSI = 00007fcc458b73c6  RDI = 00007fca3c5d9ed0

   R8 = 00007fca3c5da195   R9 = 00007fca3c5da195
  R10 = 00007fcc2bc39b33  R11 = 0000001000000006
  R12 = 00007fcc4590ed98  R13 = 00007fca3c5dac60
  R14 = 00007fcc48b2b86c  R15 = 00007fcc48b2c7c0

  RIP = 00007fcc458071ae  EFL = 0000000000000000

   CS = 0000   FS = 0000   GS = 0000

Stack Trace (captured):
[  0] 0x00007fcc457fe713    /usr/local/MATLAB/R2019a/bin/glnxa64/libmwfl.so+00829203
[  1] 0x00007fcc457fe90c    /usr/local/MATLAB/R2019a/bin/glnxa64/libmwfl.so+00829708 _ZN10foundation4core4diag15stacktrace_base7captureEm+00000028
[  2] 0x00007fcc4580353f    /usr/local/MATLAB/R2019a/bin/glnxa64/libmwfl.so+00849215
[  3] 0x00007fcc458036a0    /usr/local/MATLAB/R2019a/bin/glnxa64/libmwfl.so+00849568
[  4] 0x00007fcc48b1b5ce /usr/local/MATLAB/R2019a/bin/glnxa64/libmwfoundation_usm.so+00075214
[  5] 0x00007fcc48b29e56 /usr/local/MATLAB/R2019a/bin/glnxa64/libmwfoundation_usm.so+00134742 _ZN10foundation3usm6DetailINS0_5scope3MvmEE10findOrFailEmRKSt9type_info+00000150
[  6] 0x00007fcc45991d64      /usr/local/MATLAB/R2019a/bin/glnxa64/libut.so+00531812 _Z23utGetInterruptStateDatav+00000052
[  7] 0x00007fcc45991df9      /usr/local/MATLAB/R2019a/bin/glnxa64/libut.so+00531961 _ZN16utInterruptState18IsInterruptPendingEv+00000009
[  8] 0x00007fca33d77814 /home/nibalysc/Programs/astra_R2019a/matlab/mex/astra_mex_algorithm_c.mexa64+00026644
[  9] 0x00007fcc47be5dd5                             /lib64/libpthread.so.0+00032213
[ 10] 0x00007fcc47376ead                                   /lib64/libc.so.6+01040045 clone+00000109
[ 11] 0x0000000000000000                                   <unknown-module>+00000000
`

**Comment by dahaen** [comment]
Hi,

I experience exactly the same behaviour for MATLAB R2019a on Ubuntu 18.04.
I compiled successfully with gcc-7.4 (default for Ubuntu 18.04) and gcc-6.5 (in the Ubuntu 18.04 repositories), also first facing the compiler issues described and solved in #149. Running the astra_test script leads to the same error as described above ("Assertion in findOrFail at management.cpp line 721:
findOrFail: no active context for type 'std::shared_ptr'".

One may try to install the gcc version officially supported by MATLAB R2019a, which is gcc 6.3.x, however this version is not provided in the Ubuntu repositories and would mean some more work to compile from sources. However, since above is reported that for MATLAB 2018b (with the same gcc compatibility, i.e. 6.3.x) this problem does not occur, downgrading to gcc 6.3.x appears little promising for R2019a.

Did anyone else face this issue? Any recommendations where to continue searching (except downgrading to MATLAB R2018b)?

**Comment by wjp** [comment]
We've also had a report about this happening in Windows this week, so it appears to be a broader R2019a issue. A workaround is removing the line ```#define USE_MATLAB_UNDOCUMENTED``` from `matlab/mex/mexHelpFunctions.h`. This disables a few uses of undocumented matlab functions. The one responsible for this particular crash seems to be `utIsInterruptPending()` which we use for catching Ctrl-C ( https://undocumentedmatlab.com/blog/mex-ctrl-c-interrupt )

**Comment by dahaen** [comment]
This worked also in my case, thank you!
Are there any side effects of disabling the use of the undocumented matlab funtions on the core functionality of the toolbox to be exptected?

**Comment by wjp** [comment]
The `astra_mex_data3d('link', ...)` function will be disabled, as well as the Ctrl-C handling.

**Comment by wjp** [comment]
It appears that calling `utIsInterruptPending()` from outside of the main thread will now crash. I've adapted the Ctrl-C handling in d9261bdb05cd0863a2c3747c812871dbb851646e accordingly, and this functionality now works in R2019a again.
