### ISSUE TITLE
Simple Shepp-Logan 3D phantom projection and back projection in Python

### ISSUE THREAD

**Issue by Intfloatbyte** [astra-toolbox/astra-toolbox#199]
Hello everyone,

I'm a new user of the astra toolbox. I'm working on a project using python and I have been trying to do a simple projection/backprojection of a 3D Shepp-Logan Phantom without succeeding.

Can you please help me ? 

Thank you in advance.

**Comment by wjp** [comment]
Closing this as it is an old issue. Please open a new discussion (instead of an issue) if this is still a concern.
