### ISSUE TITLE
Installation worked without Cuda

### ISSUE THREAD

**Issue by zaccharieramzi** [astra-toolbox/astra-toolbox#200]
I don't have an nvidia GPU on my machine so I don't have cuda installed. However I managed to install `astra` for python as opposed to what the [requirements listed in the docs](https://github.com/astra-toolbox/astra-toolbox#for-python) might imply.

Maybe the docs need some change.

**Comment by paskino** [comment]
Building without CUDA can be achieved by removing `--with-cuda=<cuda_sdk_path>` from the configure script.

Also it is possible to point the configure script to a different python than the default one with `--with-python=<python_executable>`

**Comment by sharatha23** [comment]
Is there any way that we could use ASTRA toolbox on laptops with windows 10 and no CUDA support? Because I have got a Radeon Graphics Card on my system. On Linux based systems, we would use the build option and enter without CUDA. How about Windows??
