### ISSUE TITLE
SIRT::doSlabCorrections not exposed?

### ISSUE THREAD

**Issue by kohr-h** [astra-toolbox/astra-toolbox#201]
I tried to find out out whether the SIRT option for slab correction is accessible from Python. I did the most primitive thing, a repo search for "slab", and only got [2 hits](https://github.com/astra-toolbox/astra-toolbox/search?q=slab&unscoped_q=slab), one for declaration and one for implementation.

Is there any code path to that method, i.e., for some specific configuration? The search may have missed it.

**Comment by wjp** [comment]
No, it indeed isn't exposed. (Only via the internal C++/CUDA interface that you directly call.)

**Comment by kohr-h** [comment]
Okay, thanks for the quick answer @wjp. It's not so hard to implement outside, so there's no huge reason to expose it, I guess.
