### ISSUE TITLE
Get Projector matrix for 3D Cone geometry

### ISSUE THREAD

**Issue by PranjalSahu** [astra-toolbox/astra-toolbox#203]
I am facing the same issue as in https://github.com/astra-toolbox/astra-toolbox/issues/115
The author of the issue closed it without mentioning the solution.
Can someone please help me in this regard.

Can a sample code be added to obtain the Projection matrix for 3d cone geometry.

Thanks

**Comment by wjp** [comment]
The projection matrix in ASTRA is computed on-the-fly as needed. We currently provide no functionality to obtain the matrix for 3D projections. You can of course form it explicitly one column at a time by projecting unit vectors.
