### ISSUE TITLE
import astra_c : Import error  : DLL Load failes

### ISSUE THREAD

**Issue by raghusharma87** [astra-toolbox/astra-toolbox#204]
![astra path](https://user-images.githubusercontent.com/40260752/59960310-5752a880-94e4-11e9-8668-724389b08bb1.jpg)
![Import astra](https://user-images.githubusercontent.com/40260752/59960311-5752a880-94e4-11e9-90a2-363b05a3717a.jpg)
I am using astra-1.6-python34-win-x64 along with WinPython-64bit-3.4.2.2.
I have copied the astra folder in sitepackages in Python directory. as shown in the screenshot.
When I try to import astra using command prompt I get the error :
form . import astra_c
ImportError: DLL load failed : the specified module could not be found

**Comment by raghusharma87** [comment]
I have resolved the issue.

1.6-python34-win-x64  requires Microsoft Visual C++ 2012 Redistributable Package

**Comment by meetaig** [comment]
please close the issue, if it is resolved.
