### ISSUE TITLE
Documentation for algorithm.get_res_norm

### ISSUE THREAD

**Issue by AndrewHerzing** [astra-toolbox/astra-toolbox#209]
Can someone explain what `algorithm.get_res_norm` is returning?  I assumed it was the sum of the squared difference between the forward-projected reconstruction and the input sinogram, but this does not appear to be the case.

**Comment by wjp** [comment]
It returns the square root of that.

**Comment by AndrewHerzing** [comment]
Simple enough.  Thanks.
