### ISSUE TITLE
No GPU support available 

### ISSUE THREAD

**Issue by vishalvaza** [astra-toolbox/astra-toolbox#210]
Hello,

I installed an astra-toolbox in my 64 bit Windows OS using "conda install -c astra-toolbox astra-toolbox" command and it was done successfully. I have GeForce GT 710 Nvidia graphic card install in my system. Now when i was trying to run project given below 
**import astra as a
a.test()**
shows me a error like 
**No GPU support available
Testing basic CPU 2D functionality... Ok**

can you tell me why it has not having a support of GPU?

**Comment by wjp** [comment]
Hi,

Unfortunately the GT710 does not seem to support CUDA; it is not listed on https://developer.nvidia.com/cuda-gpus .

**Comment by vishalvaza** [comment]
> Hi,
> 
> Unfortunately the GT710 does not seem to support CUDA; it is not listed on https://developer.nvidia.com/cuda-gpus .

 I replace other CUDA supported card and it is working fine now. Thanks @wjp for your quick support.

**Comment by hrashidykanan** [comment]
Hello all,

I tried to install the Astra package via Conda on our Linux server using conda install -c "astra-toolbox/label/dev" astra-toolbox command. Installation was successful. However, when I tested it using astra.test(), I got the following message:

No GPU support available
ASTRA Toolbox v2.1.3
Testing basic CPU 2D functionality... Ok

We have Tesla K80 Nvidia graphic card on our server.

I want to use GPU ability of Astra package.

Could you please assist me in this matter.
Thank you very much.

Hamidreza
