### ISSUE TITLE
Question: Fast GPU project as function of input and 1 angle

### ISSUE THREAD

**Issue by nabriis** [astra-toolbox/astra-toolbox#215]
Hi,

I hope someone can give some insight here. I am trying to use ASTRA for running block-wise updates in an iterative algorithm, where each block correspond to a single view angle. 

My code for this is currently to use astra_create_sino. This has some serious overhead when comparing a projection on for example a 1024 x 1024 image with 2048 detector pixels and 90 angles, with 90 projections on 1024 x 1024 image with 2048 detector pixels and 1 single angle each.

Currently my code runs about the same speed on CPU, but on GPU the block version runs 60 times slower. How can I make the block version run faster?

edit: After some testing I found that the main computation time is in astra_mex_algorithm('iterate', alg_id);. I think this means the the overhead is located in the mex file and there is not much I can do.

My code looks something like this:

> clc; clear; close all;
>
> addpath(genpath('astra-1.9.0.dev11'))
>
>N = 1024; p = 2048;
>det_type = 'fanflat';
>proj_type = 'cuda';
>stc = 50; ctd = 50; dew = 1;
> 
> % Phantom
> x = phantom(N);
> 
> % angles
> theta = (0:1:89)*(pi/180);
> 
> % object dimensions
> 
> vol_geom  = astra_create_vol_geom(N,N);
> 
> % projection geometry
> proj_geom = astra_create_proj_geom(det_type,dew,p,theta,stc,ctd);
> 
> % Projection ID
> proj_id = astra_create_projector(proj_type, proj_geom, vol_geom);
> 
> tic
> b = astra_create_sino(x, proj_id);
> toc
> 
> %Generate projection IDs for each block
> for i =1:length(theta)
>            % projection geometry
>            proj_geom_block = astra_create_proj_geom(det_type,dew,p,theta(i),stc,ctd);
>            % Projection ID
>            proj_id_block(i) = astra_create_projector(proj_type, proj_geom_block, vol_geom);
> end
> 
> b2 = zeros(90,2048);
> tic
> for i =1:length(theta)
>     b2(i,:) = astra_create_sino(x, proj_id_block(i));
> end
> toc

**Comment by wjp** [comment]
Creating the structures and the projector is definitely a part of the overhead. This can be somewhat mitigated by creating them once and then re-using them, but how much that helps will of course depend on how often you re-use them.

Copying the data to the GPU and back also introduces extra delay for every operation.

Another (probably larger) source of relative slowdown is that processing only a single angle reduces the opportunities for parallelizing the computation on the GPU. The effect is that the GPU's processing power will be under-utilized if you only (back/forward) project a single angle.

**Comment by JohnEU** [comment]
That makes sense. It was indeed that the GPU is simply under-utilized for the 2D problems with only 1 angle. Thanks.
