### ISSUE TITLE
Question: What is the numbering convention of the SIRT algorithm?

### ISSUE THREAD

**Issue by AndrewHerzing** [astra-toolbox/astra-toolbox#216]
If the SIRT algorithm is run with the number of iterations set to '1', is this equivalent to a simple backprojection or is it equivalent to a backprojection plus one SIRT refinement operation?

**Comment by wjp** [comment]
This is mostly equivalent to a single backprojection. I say mostly because it does also scale the result with the inverse column weights of the system matrix.
