### ISSUE TITLE
2D projections to 3D volume to Astra

### ISSUE THREAD

**Issue by raghusharma87** [astra-toolbox/astra-toolbox#218]
I have total  16 ,2D images taken on cone beam vector geometry.I read those images in Numpy array of size (16(number of slices),detector_rows(3584),detector_cols(2816)). The width and height of the images are in pixels.
Now I have two queries:
1. Is the volume geometry the dimensions(X,Y,Z) of my body part being scanned? Do I have to insert the value in mm?

**Comment by meetaig** [comment]
Hi,
in general, I would recommend setting your geometry up in mm or another unit, as long as it is coherent. But note that before creating the geometry, you have to express every unit as a multiple of the voxelsize, as ASTRA assumes that a voxel is a cube with unit length.

Another small note is that your projection data needs to be stored with the number of projecions in the middle coordinate. (Like: (x, angles, y) or as it is in the documentation (u, angles, v)

> id = astra_mex_data3d('create', '-proj3d', proj_geom, initializer);
>
>This creates an initialized 3D projection data object for the geometry proj_geom.
>
>Initializer may be:
> -   a scalar: the object is initialized with this constant value.
>  -  a matrix: the object is initialized with the contents of this matrix. The matrix must be of size (u,angles,v), where u is the number of columns of the detector and v the number of rows as defined in the projection geometry. It must be of class single, double or logical.

Hope that helped!

**Comment by 212414154** [comment]
> Hi,
> in general, I would recommend setting your geometry up in mm or another unit, as long as it is coherent. But note that before creating the geometry, you have to express every unit as a multiple of the voxelsize, as ASTRA assumes that a voxel is a cube with unit length.
> 
> Another small note is that your projection data needs to be stored with the number of projections in the middle coordinate. (Like: (x, angles, y) or as it is in the documentation (u, angles, v):
> 
> > id = astra_mex_data3d('create', '-proj3d', proj_geom, initializer);
> > This creates an initialized 3D projection data object for the geometry proj_geom.
> > Initializer may be:
> > 
> > * a scalar: the object is initialized with this constant value.
> > * a matrix: the object is initialized with the contents of this matrix. The matrix must be of size (u,angles,v), where u is the number of columns of the detector and v the number of rows as defined in the projection geometry. It must be of class single, double or logical.
> >   )
> 
> Hope that helped!

**Comment by 212414154** [comment]
which function i can use in astra toolbox to compute sinogram from real projections ?
