### ISSUE TITLE
Is there any algorithm available for reconstruction of SPECT system with multipinhole arrays as collimators?

### ISSUE THREAD

**Issue by efmanu** [astra-toolbox/astra-toolbox#223]
Hi,

   I am working with SPECT imaging. The collimator is used in this system is multi-pinhole arrays. Is there any specific algorithm available for reconstruction of this setup?

Regards,
Manu

**Comment by wjp** [comment]
Hi, unfortunately SPECT is outside of the scope of ASTRA.
