### ISSUE TITLE
Offset in reconstructed attenuation coefficient

### ISSUE THREAD

**Issue by aziabari** [astra-toolbox/astra-toolbox#229]
Hi, I have an issue with a simple FDK recon using astra.
I have 3D volume with the size (1636, 768, 768).
The detector size is 1700x1700 and number of views are 2000.
The attenuation coefficient of the Ground Truth volume is ~0.25.

I performed a simple FDK reconstruction of the projected volume without any noise and artifacts, and it seems the reconstructed values doesn't match the ground truth and there is an offset (not exactly the same offset everywhere).

A cross section comparison is done in the attached figure where blue is the ground truth (GT) and orange is the FDK reconstructed values.
In addition a second figure shows the difference between Ground Truth (GT) attenuation coefficient and the FDK recon.

Please let me know if you have any suggestion/comments to resolve this.

<img width="587" alt="Screen Shot 2020-03-24 at 7 05 21 PM" src="https://user-images.githubusercontent.com/31284041/77485209-f5242c80-6e02-11ea-8d02-fcec15ac9110.png">

<img width="589" alt="Screen Shot 2020-03-24 at 7 08 56 PM" src="https://user-images.githubusercontent.com/31284041/77485214-f6555980-6e02-11ea-8280-6493f6eafc64.png">

**Comment by askorikov** [comment]
This should be addressed now. Let us know if you still observe this discrepancy.
