### ISSUE TITLE
Resolution of reconstructed image using SIRT3D_CUDA

### ISSUE THREAD

**Issue by raghusharma87** [astra-toolbox/astra-toolbox#233]
I have 16 -2D projections of size 3584x2816 @ 0.083mm of pixel size.the height of the object is 40mm.

Then I created a vol_geom = astra.create_vol_geom(298,234,40);(considering 1 mm voxel size)**.Is this correct?**

Then I created the projection geometry passing the vector geometry of cone beam  as follows:
proj_geom = astra.create_proj_geom('cone_vec',2816,3584, geometry);

Then the algo:
cfg = astra.astra_dict('SIRT3D_CUDA')
cfg['ReconstructionDataId'] = rec_id
cfg['ProjectionDataId'] = proj_id
cfg['option']={}
cfg['option']['MinConstraint'] = 0
cfg['option']['MaxConstraint'] = 65535
cfg['option']['DetectorSuperSampling'] = 4

After this saved the reconstructed images :rec = astra.data3d.get(rec_id)
for x in range(0,40,1):
    (rec[x,:,:]).astype('uint16').tofile("D:\\Images\\Abc"+str(x)+".raw");

I have attached the screenshots of the results I get when I use 2 iterations in SIRT and 100 iterations in SIRT.
My reconstructed image has loss in image data when I use 2 iteration.
My reconstructed image has a lot of loss in image data when I use 100 iteration.
Please guide How can I increase the resolution of reconstructed image:

![2_iterations vs 100_iterations](https://user-images.githubusercontent.com/40260752/79716419-41746680-82f4-11ea-9a62-1b59eca43a47.jpg)

**Comment by rossha46** [comment]
I'm new to the astra toolbox, so i may be wrong on this. 

If you use the following two lines, it gives a reconstruction volume equal to what i think your expecting.

`
S2O = 573.811447143555;     % source to object distance
S2D = 1147.789;                     % source to detector distance
O2D = S2D - S2O;                  % object to detector distance

vol_geom = astra_create_vol_geom(3584, 2816, 482);

proj_geom = astra_create_proj_geom('cone', 0.083, 0.083, 3584, 2816, angles, S2O, (O2D));
`
This seems to give the reconstruction volume your looking for, and has the same syntax as in the documentation.

`proj_geom = astra_create_proj_geom('cone',  det_spacing_x, det_spacing_y, det_row_count, det_col_count, angles, source_origin, origin_det);`

hope this helps
