### ISSUE TITLE
Incorrect attenuation coefficients using SIRT_CUDA, SART_CUDA and CGLS_CUDA for undersampled data

### ISSUE THREAD

**Issue by idaaspro123** [astra-toolbox/astra-toolbox#236]
I am reconstructing a phantom using iterative methods SIRT_CUDA, SART_CUDA and CGLS_CUDA.

The reconstructed data set has projections removed from a wedge geometry;

90 wedge- projetions 90-180 and 180-270 removed
60 wedge -  projections 90-150, 180-240 removed
30 wedge -  projections 90-120, 180-210  removed

Only FBP_CUDA returns the correct attenuation coefficients, while for the same data, iterative methods give incorrect attenuation values.
![lac_error](https://user-images.githubusercontent.com/55736907/82219780-a8963280-9915-11ea-99be-8cb3563b1c9e.png)

**Comment by wjp** [comment]
This should be fixed with the current version 2.0. Please feel free to re-open this issue if it still occurs for you, preferably with an example script to quickly reproduce the issue.
