### ISSUE TITLE
Noise in FBP output

### ISSUE THREAD

**Issue by vishalvaza** [astra-toolbox/astra-toolbox#238]
![600](https://user-images.githubusercontent.com/11832271/83871646-0ddb8780-a74e-11ea-869a-622082d4f531.jpg)
![600](https://user-images.githubusercontent.com/11832271/83871664-13d16880-a74e-11ea-8f19-b345cb7418d5.jpg)

Here I attached the input sinogram file and output of FBP algo.
can you tell me how to reduce the noise.

**Comment by X-Rayven** [comment]
You can different algorithms to reduce it, I would recommend TV (total variation) regularization.

**Comment by RadouaneBjm** [comment]
Hi @X-Rayven ,
first of all sorry for reopening this closed issue. from reading your comment, I'm curious to know if TV regularization is implemented on ASTRA
Thank you,
