### ISSUE TITLE
opTomo class not working (MATLAB in Linux)

### ISSUE THREAD

**Issue by furibec** [astra-toolbox/astra-toolbox#239]
Hi, 
I just installed Astra Toolbox for MATLAB in Linux. Most of the functionalities are working but when calling the `opTomo` class:
```matlab
addpath(genpath('/usr/local/astra/share/astra/matlab/'));
n = 64;
r = 128;
p = 180;
det_width = 1.0;
angles = linspace2(0, pi, p);
%
vol_geom  = astra_create_vol_geom(n, n);
proj_geom = astra_create_proj_geom('parallel', det_width, r, angles);
proj_id   = astra_create_projector('strip', proj_geom, vol_geom);
%
R = opTomo('linear', proj_geom, vol_geom);
```
I get the MATLAB error:
`Error using opTomo
The specified superclass 'opSpot' contains a parse error, cannot be found on MATLAB's search path, or is shadowed by another file with the same name.`

I know the class is not shadowed since writting `which -all opTomo`, I get one output: `/usr/local/astra/share/astra/matlab/tools/opTomo.m`. 

Could it be that this error is associated to a bad installation ? For the installation, I followed the readme file after downloading the source code files from Github:
```
cd build/linux
./autogen.sh
CPPFLAGS="-I/usr/local/boost_1_73_0/" ./configure --with-matlab=/opt/MATLAB/R2020a --prefix=/usr/local/astra/
make
sudo make install
```
and then I just added the /usr/local/astra/lib to the LD_LIBRARY_PATH. I did not get any error during instalation, and only the `opTomo` class is not working.

Thanks for the help !

**Comment by meetaig** [comment]
Hi,
did you add the spot toolbox to your path as well? OpTomo requires the spot operator that is implemented here:
https://github.com/mpf/spot

Hope that fixes it :)

**Comment by furibec** [comment]
Perfect, now it works. Thanks a lot !
