### ISSUE TITLE
OpTomo does not implement `_adjoint` or `_rmatvec`

### ISSUE THREAD

**Issue by RendersJens** [astra-toolbox/astra-toolbox#240]
Currently OpTomo does not implement `_adjoint` or `_rmatvec`. According to the [scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.LinearOperator.html) one of these methods should be implemented to implement the adjoint or transpose action.

Since `_transpose` is implemented, calling `W.transpose()` or `W.T` does work, but calling `W.adjoint()` or `W.H` returns an adjoint operator that cannot be multiplied with a vector. It tries to call `W._rmatvec` which is not implemented.

This leads to problems when passing the operator to functions that require the adjoint. I currently fix this by simply adding an underscore before `rmatvec` which is defined in `optomo.py`

**Comment by wjp** [comment]
This should be resolved by merging your PR #281. Thanks!
