### ISSUE TITLE
data2d.py missing import

### ISSUE THREAD

**Issue by jleuschn** [astra-toolbox/astra-toolbox#241]
After the latest very nice updates introducing array links there is a missing import of the function `checkArrayForLink`:

https://github.com/astra-toolbox/astra-toolbox/blob/master/python/astra/data2d.py#L68

I will make simple pull request that takes the corresponding lines from data3d.py.

**Comment by wjp** [comment]
Fixed by 618265c569d1917ea106d6937c344b085cf7980b
