### ISSUE TITLE
Unable to initialize iterative algorithms

### ISSUE THREAD

**Issue by tom-mcs** [astra-toolbox/astra-toolbox#243]
I am unable to initialize the algorithms SIRT_CUDA and SART_CUDA. However I am able to initialize the algorithm FDK_CUDA.

Despite no other changes

`cfg = astra_struct("FDK_CUDA");`
`cfg.ProjectionDataId = astra_mex_data3d('create', '-sino', proj_geom, projections);`
`cfg.ReconstructionDataId = rec_id;`
`alg_id = astra_mex_algorithm('create', cfg);`

works perfectly and (along with the rest of my code) reconstructs my data successfully, but when the first line is changed to
`cfg = astra_struct("SIRT_CUDA");`

it produces the following error:
`Configuration Error in Reconstruction2D: Invalid Projection Data Object.`
`Error using astra_mex_algorithm_c`
`Unable to initialize Algorithm.`

Am i experiencing a bug or do i perhaps need to create the projection data object differently for iterative algorithms?

Thank you. Any help on this issue would be greatly appreciated, please let me know if further information is required.

**Comment by wjp** [comment]
For 3D data you can use the `SIRT3D_CUDA` algorithm. (`SIRT_CUDA` is the 2D variant.) At this point we unfortunately do not yet have a 3D SART implementation.

**Comment by tom-mcs** [comment]
Thank you. It is working now.
Is there anywhere I can find a comprehensive list of algorithms available for cone-beam reconstruction?
