### ISSUE TITLE
2D Backprojection is all zeros

### ISSUE THREAD

**Issue by angelap14** [astra-toolbox/astra-toolbox#244]
Hello,

I have installed the toolbox in two of the computers of my lab, both using the "ASTRA v1.9.0.dev11 for Windows 64 bit CUDA/MATLAB" version.  Both PCs are using Matlab 2020a and Cuda 10.1 version. The only difference I have found between computers is the GPU. One of them has an RTX2070 and the other one is a GTX1080.  

The toolbox works well on the computer with the GTX1080. However, when I tried to use "astra_create_backprojection_cuda", the computer with the RTX2070 gives all zeros for the 2D fan beam back projection of any vector even if it's an all-ones vector. I tried using the optomo operator but that gives the same problem. I find this problem strange since the forward projection works fine on both PCs (its non-zero). 

This is the code I am currently testing:

det_rows = 512; 
det_size = 1; 
N = 256;
P = 360;

SID = 1200;       
SOD = 600;       

vol_geom = astra_create_vol_geom(N,N);

proj_geom = astra_create_proj_geom('fanflat', det_size, det_rows, linspace2(0,2*pi,P),SOD,SID-SOD);

W = opTomo('cuda', proj_geom, vol_geom);
test1 = W'*ones(P*det_rows,1);
test2 = 

I also tried compiling the files using "ASTRA v1.9.0.dev11 Source Code for Windows (Visual Studio 2017)" for the PC where I get the error but the same thing happens with the backprojection. I tried the 3D backprojection for a cone-beam architecture and it works fine. I only get the problem when I try to use the 2D backprojection. Is there anything I can try to correct the error?

Thank you for any help you can provide!

**Comment by oh75420** [comment]
I have the same questions for this issue. Did you fix the problem? thx~

**Comment by angelap14** [comment]
I tried compiling the latest files available on Github instead of the "ASTRA v1.9.0.dev11 Source Code for Windows (Visual Studio 2017)" and the resulting files gave me an answer that was different from zero for the 2D back projection.
