### ISSUE TITLE
weird result of SIRT3D_CUDA  algorithm when vol_geom no longer centered at the origin

### ISSUE THREAD

**Issue by hzz0033** [astra-toolbox/astra-toolbox#245]
Hello, 
I met a problem like this in 3D reconstruction with SIRT3D_CUDA algorithm in Matlab. When I shift the volume geometry from the center, the reconstruction result looks weird. 

Input is a shep-logan 3D phantom download online and first image is reconstruction around the center(-128:128), second is 32 pixel shift(-96:160) and third one is 128 shift.(0:256), iteration = 1.

![image](https://user-images.githubusercontent.com/65258378/87828716-5c427280-c832-11ea-9c63-e46bcc5a0089.png)

![image](https://user-images.githubusercontent.com/65258378/87828754-74b28d00-c832-11ea-9a92-eb0aa0a54c1f.png)

![image](https://user-images.githubusercontent.com/65258378/87828780-83993f80-c832-11ea-9bc4-f8f4c54fcafd.png)

I want to ask if anyone knows what happened to the SIRT algorithm raw reconstruction? Below is the code modified from the sample in ASTRA toolbox.
![image](https://user-images.githubusercontent.com/65258378/87829740-7715e680-c834-11ea-912a-fed152e8ee6b.png)

**Comment by hzz0033** [comment]
modify projection geometry, distance from the source to the center and distance from the center to the detector, will highly affect the result, too.

**Comment by wjp** [comment]
SIRT is an iterative algorithm and therefore cannot reconstruct partial volumes. If the reconstruction volume does not contain the full object, getting high-intensity artefacts at the edges of the volume is expected.
