### ISSUE TITLE
Invalid MEX-file errors - undefined symbol

### ISSUE THREAD

**Issue by heyitsguay** [astra-toolbox/astra-toolbox#25]
Hi there,

I'm running the latest github version of astra-toolbox (as of 2/8/16 3:00 PM EST) on 64-bit Ubuntu 15.10, with CUDA 7.5 and MATLAB 2015b. After setting up MATLAB to use gcc-4.7 and g++-4.7, I configured ASTRA using "./configure --with-cuda=/usr/local/cuda --with-matlab=/usr/local/MATLAB/R2015b --prefix=/usr/local/astra", then made and installed using the usual make, make install. 

That all worked successfully, but now when I'm running some tests of my MATLAB code, I get the following errors:

Invalid MEX-file '/usr/local/astra/matlab/mex/astra_mex_projector_c.mexa64': /usr/local/astra/matlab/mex/astra_mex_projector_c.mexa64: undefined symbol: _ZN5astra16CCudaProjector2D4typeB5cxx11E

Invalid MEX-file '/usr/local/astra/matlab/mex/astra_mex_data2d_c.mexa64': /usr/local/astra/matlab/mex/astra_mex_data2d_c.mexa64: undefined symbol: _ZN5astra17running_in_matlabE

Googling the problem was no help, I tried 'make clean' -> 'make distclean' -> ./autogen.sh etc etc, but the errors persisted. Same if I deleted the cloned astra-toolbox directory, deleted /usr/local/astra, then re-cloned astra-toolbox and installed again. Any thoughts?

Thank you,
Matt

**Comment by wjp** [comment]
Do you have any old versions of astra installed?

**Comment by heyitsguay** [comment]
Thanks for responding so promptly! I don't believe any old versions are installed, but I could double-check that if there's any easy way to do so. The output of 'locate astra' in bash didn't turn up anything other than stuff in /usr/local/astra/ and git/astra-toolbox/.

**Comment by heyitsguay** [comment]
Update: I tried a clean build without CUDA support (we need CUDA acceleration for our application, this was just to try and isolate the problem). I'm getting similar errors still, with this build:

Invalid MEX-file '/usr/local/astra/matlab/mex/astra_mex_projector_c.mexa64': /usr/local/astra/matlab/mex/astra_mex_projector_c.mexa64: undefined symbol: _ZN5astra9SingletonINS_19CAstraObjectFactoryINS_12CProjector2DENS_8typelist8TypeListINS_33CFanFlatBeamLineKernelProjector2DENS4_INS_34CFanFlatBeamStripKernelProjector2DENS4_INS_36CParallelBeamLinearKernelProjector2DENS4_INS_34CParallelBeamLineKernelProjector2DENS4_INS_34CParallelBeamBlobKernelProjector2DENS4_INS_35CParallelBeamStripKernelProjector2DENS4_INS_24CSparseMatrixProjector2DENS3_8NullTypeEEEEEEEEEEEEEEEEEE11m_singletonE

Invalid MEX-file '/usr/local/astra/matlab/mex/astra_mex_data2d_c.mexa64': /usr/local/astra/matlab/mex/astra_mex_data2d_c.mexa64: undefined symbol: _ZN5astra17running_in_matlabE

**Comment by wjp** [comment]
This is a bit puzzling, but I think I now see at least one possible cause. It looks like changing settings like matlab support and cuda support by re-running configure, doesn't always trigger all required files to be rebuilt.

Could you trying to do a 'make clean' before running make, make install, to see if problems persist?

**Comment by heyitsguay** [comment]
Hey,

Tried that - ran 'make clean', then the same configuration as in my previous post. Same errors.

On another of our 64 bit Ubuntu computers, building with CUDA support gave different errors - MATLAB would just tell me it was unable to find libastra.so.0 even though it was definitely pointed to by LD_LIBRARY_PATH, and when building without CUDA support it worked (albeit too slowly to be useful, of course). That might have to be another issue, but I'm hoping they're related and solving my first one will take care of this other one as well.

**Comment by heyitsguay** [comment]
Hi again,

After doing some more digging through my file system, I found there was an old set of astra libraries on my path from a third-party pyastra project from back before you had python bindings. Deleting them seems to have solved the 'undefined symbol' errors I was getting, but now i'm getting the "Invalid MEX-file '/usr/local/astra/matlab/mex/astra_mex_data2d_c.mexa64': libastra.so.0: cannot open shared object file: No such file or directory" error that I was getting on the other computer, as I mentioned in my previous comment.

I took a look at the output of getenv('LD_LIBRARY_PATH') in MATLAB, and for some reason there's a discrepancy between what MATLAB is seeing and what I get if I just type 'echo $LD_LIBRARY_PATH' into bash. MATLAB is giving me 

'/usr/local/MATLAB/R2015b/sys/os/glnxa64:/usr/local/MATLAB/R2015b/bin/glnxa64:/usr/local/MATLAB/R2015b/extern/lib/glnxa64:/usr/local/MATLAB/R2015b/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/usr/local/MATLAB/R2015b/sys/java/jre/glnxa64/jre/lib/amd64/server::/usr/lib/x86_64-linux-gnu/:/usr/local/cuda/lib64/:/lib/caffe/build/lib/:/usr/local/lib/'

while bash gives me 

':/usr/lib/x86_64-linux-gnu/:/usr/local/cuda/lib64/:/lib/caffe/build/lib/:/usr/local/lib/:/usr/local/astra/lib/
'

MATLAB-specific stuff aside, I see that somehow /usr/local/astra/lib/ is getting dropped. So, I'll try to figure out what's going on with that; it might be a MATLAB or Ubuntu issue, probably not a problem with your toolbox. So I think we can close this issue, and I'll open another one if it ends up looking like this library path thing might somehow be caused by your toolbox (unlikely).

Thanks!
Matt

**Comment by heyitsguay** [comment]
Followup: Figured out the problem with the LD_LIBRARY_PATH configuration - I'd added /usr/local/astra/lib/ to it in my .bashrc file instead of .profile, so MATLAB wasn't seeing it when it opened. It's resolved now.

**Comment by polatadem** [comment]
Dear heyitsguay,
I am a PhD student as well. I am a new user of toolbox of Matlab. Would you please teach me installing of Astra step by step as very basic to my Matlab (Windows). I downloaded Astra, but I could not install and run it.
Best,
Adem
