### ISSUE TITLE
Possible to remove noise from this Image? ( I am using BP algorithm in this process )

### ISSUE THREAD

**Issue by shalinsirwani** [astra-toolbox/astra-toolbox#250]
Here is my Input image 

![test1 - Copy](https://user-images.githubusercontent.com/28221425/89251617-190b4080-d635-11ea-8b47-13461f5ff3dd.jpg)

Output image 

![test-out-BP](https://user-images.githubusercontent.com/28221425/89251682-40620d80-d635-11ea-83d2-e6eae6e7430e.jpg)

If i am using **FBP algorithm**, output is without noise , but in side portion of the image is not filled as with **BP algorithm**
Here is the image of **FBP algorithm**
![test-out-FBP](https://user-images.githubusercontent.com/28221425/89251784-8919c680-d635-11ea-8217-63862140c57a.jpg)

Any way is it possible to get BP result without noise . by applying some filter or some thing else ??

**Comment by wohe157** [comment]
I think this is a normal artefact from using FBP, have you tried using another filter than the default ('ram-lak')? I don't know, but maybe you can find better results with another filter. Have a look [here](https://www.astra-toolbox.com/docs/algs/FBP_CUDA.html).

However, to get the best possible reconstruction, I would use an iterative algorithm such as SIRT or EM.

Another way to get better results in this specific case would be to segment the reconstructed image, but that would not be an option of you are dealing with images with multiple intensities of course.
