### ISSUE TITLE
Initialise a reconstruction with another reconstruction

### ISSUE THREAD

**Issue by raffra** [astra-toolbox/astra-toolbox#251]
Dear all,
have you ever tried to initialise a parallel 3d reconstruction with a previous iteration? I would like at least to change the tilt data  and reuse an older reconstruction estimate. In tomopy the reconstruct function has a parameter which can be assigned to an old reconstruction 3d array, providing for the aforementioned initialisation. What is the correct way to do with Astra toolbox? Is there some code snipped available? (if possible in python, but I can try to adapt the concept from the Matlab wrapper). Or can you suggest a strategy?
Thank you all in advance.

**Comment by meetaig** [comment]
Hi,
if you iterate one algorithm object the data is updated automatically. To get the current state of the reconstruction in each iteration you can do something like the following:

```
for iter in range(iterations):
     astra.algorithm.run(alg_id, 1)
     current_recon = astra.data3d.get(rec_id)
```

If you want to initialize a data3d object with another reconstruction you can do that using the create() function:
```
prev_recon = astra.data3d.get(rec_id)
rec2_id = astra.data3d.create('-vol', vol_geom, prev_recon)
```
or you can store() new data, overwriting the whole array
```
astra.data3d.store(rec2_id, prev_recon)
```
Note that the volumes have to be of the same size for this to work.

Hope that could help you along!
