### ISSUE TITLE
Problems loading tiff images into the ASTRA toolbox on Matlab

### ISSUE THREAD

**Issue by gideon1993** [astra-toolbox/astra-toolbox#252]
I have 3141 projections in tiff format which I am trying to load on the toolbox to perform Iterative reconstruction. I however have faced challenges loading them. Please assist with that part for tiff images

**Comment by meetaig** [comment]
Hi,
loading tif images can be achieved in several ways. Using MATLAB you can simply use imread(...) (https://nl.mathworks.com/help/matlab/ref/imread.html). If you're using Python you might want to look into the package PIL or imagio (https://stackoverflow.com/questions/7569553/working-with-tiffs-import-export-in-python-using-numpy).

Please note that all of those are **not part of the astra-toolbox**. To start working with the toolbox, simply load the images using one of the methods above and then put the data in one array. Then you can pass the data on to the toolbox.

**Comment by gideon1993** [comment]
I have worked well with the imread(....).

I think its the part of putting the data in one array. The reconstruction i am getting is a funny symetrical reconstruction which doesnt show my object. im assuming its the part of loading data which has the issue.

**Comment by Sophilyplum** [comment]
> I think its the part of putting the data in one array.May you please assist with that. The reconstruction i am getting is a funny symetrical reconstruction which doesnt show my object. im assuming its the part of loading data which has the issue.

Have you figured out a solution for this? What's the size of your sinogram? Remember ASTRA expects (for whatever reason) an M-by-N matrix for sinogram where M is the number of angles and N the total number of pixels.
