### ISSUE TITLE
Is there a FBP3D implemenation in python?

### ISSUE THREAD

**Issue by JulianFhofer** [astra-toolbox/astra-toolbox#253]
Hello everyone,

im trying to reconstruct .tif files with the help of the FBP3D algorithm in python. In this repository i've found the 2D implementation of the [FBP algorithm](https://github.com/astra-toolbox/astra-toolbox/blob/master/samples/python/s014_FBP.py). Furthermore, I've stumbled over [this](https://extrema2016.po.opole.pl/images/Arpad-Marinovszki.pdf) presentation which shows an implementation of the FBP3D_CUDA algorithm on slide four. However, the syntax seems to be different and so far i was not able to make it work (maybe it was implemented for python 2.x or matlab?). Does astra have an implementation of the FBP3D algorithm?

**Comment by JulianFhofer** [comment]
So I have modified the [SIRT3D_CUDA](https://github.com/astra-toolbox/astra-toolbox/blob/master/samples/python/s007_3d_reconstruction.py) implementation to FBP3D_CUDA:

```
import astra
import numpy as np


angles = np.linspace(0, np.pi, 180,False)

vol_geom = astra.create_vol_geom(128, 128, 128)
proj_geom = astra.create_proj_geom('cone', 1.0, 1.0, 128, 192, angles, 1825, 8800)

# Create a simple hollow cube phantom
cube = np.zeros((128,128,128))
cube[17:113,17:113,17:113] = 1
cube[33:97,33:97,33:97] = 0

# Create projection data from this
proj_id, proj_data = astra.create_sino3d_gpu(cube, proj_geom, vol_geom)

# Display a single projection image
import pylab
pylab.gray()
pylab.figure(1)
pylab.imshow(proj_data[:,20,:])

# Create a data object for the reconstruction
rec_id = astra.data3d.create('-vol', vol_geom)

# Set up the parameters for a reconstruction algorithm using the GPU
cfg = astra.astra_dict('FBP3D_CUDA')
cfg['ReconstructionDataId'] = rec_id
cfg['ProjectionDataId'] = proj_id


# Create the algorithm object from the configuration structure
alg_id = astra.algorithm.create(cfg)

# Run 150 iterations of the algorithm
# Note that this requires about 750MB of GPU memory, and has a runtime
# in the order of 10 seconds.
astra.algorithm.run(alg_id, 150)

# Get the result
rec = astra.data3d.get(rec_id)
pylab.figure(2)
pylab.imshow(rec[:,:,65])
pylab.show()


# Clean up. Note that GPU memory is tied up in the algorithm object,
# and main RAM in the data objects.
astra.algorithm.delete(alg_id)
astra.data3d.delete(rec_id)
astra.data3d.delete(proj_id)
```

However, this code throws `Exception: Unknown Algorithm.` It seems like this algorithm was once [implemented](https://extrema2016.po.opole.pl/images/Arpad-Marinovszki.pdf) but recently was removed.

**Comment by meetaig** [comment]
Hello,
I am not aware of this algorithm ever existing (though I am not on the developer team): There are FP3D_CUDA and BP3D_CUDA however, which shoud enable implementing your own FBP for 3D that is CUDA enabled. The filters would be a bit slower then unfortunately. I assume the slide has a typo, but as I didn't make them, I don't know if my hunch is correct.
If you're using cone beam, as your example indicates, try using FDK_CUDA (http://astra-toolbox.com/docs/algs/FDK_CUDA.html). 

Hope that could help you!

**Comment by JulianFhofer** [comment]
Oh how could i miss that! Using FDK_CUDA did the job. Thanks alot and have a nice weekend!
