### ISSUE TITLE
Suggest reconstruction algorithm

### ISSUE THREAD

**Issue by vishalvaza** [astra-toolbox/astra-toolbox#254]
Hello,

I have object and I used only back projection data to generate 3d volume mesh. Overall my setup is backside is light source, in center I have turn table where object kept and in same center line I have camera at front side.

Light Source--->>>>>  TurnTable --->>>> Camera.

Camera will see only dark objects and other in screen remains gray portion.

Can anyone suggest me which algorithm is useful for me?

I already tried with FBP and Back Projection but BP is not working due to higher noise and FBP is not giving proper output.

**Comment by wohe157** [comment]
If you are dealing with a lot of noise, I would suggest an iterative algorithm such as SIRT (Simultaneous Iterative Reconstruction Algorithm) or EM (Expectation Maximization). SIRT should work well if you have a lot of projection images (I would say at the very least 100), while I find EM to be better for fewer projection images and if you have Poisson noise.
