### ISSUE TITLE
Repeated application of CUDA projectors resulting in RAM usage blowing up

### ISSUE THREAD

**Issue by fsherry** [astra-toolbox/astra-toolbox#255]
I have been experiencing a memory issue while using ASTRA 1.9.9dev. In my application, I am applying forward and backward projections a very large number of times and am finding that if I use the CUDA projectors, RAM usage constantly grows, eventually exhausting all the system memory (I first experienced this problem as my program was automatically killed for exceeding a memory threshold). On the other hand, if I use the CPU projectors, RAM usage is flat (as expected). 

Below I have included two basic Python snippets, one for the CUDA projector and the other for the CPU projector, which I have profiled using memory_profiler to highlight the issue that I am running into. Is this a result of an error in my usage of ASTRA, or is it possible that there is a memory leak in the implementation of the CUDA projectors?

## CUDA:
```python
from math import sqrt, pi
import astra
import numpy as np

vol_geom = astra.create_vol_geom(100, 100, -0.5, 0.5, -0.5, 0.5)
proj_geom = astra.create_proj_geom('parallel', sqrt(2) / 200, 200, np.linspace(0, pi, 500))

im_id = astra.data2d.create('-vol', vol_geom)
proj_id = astra.projector.create({'type': 'cuda',
				  'VolumeGeometry': vol_geom,
				  'ProjectionGeometry': proj_geom,
				  'options': {}})
sino_id = astra.data2d.create('-sino', proj_geom)

forward_config = astra.astra_dict('FP_CUDA')
forward_config['VolumeDataId'] = im_id
forward_config['ProjectionDataId'] = sino_id
forward_config['ProjectorId'] = proj_id
forward_alg_id = astra.algorithm.create(forward_config)

def raytransform(x):
    astra.data2d.store(im_id, x)
    astra.algorithm.run(forward_alg_id)
    return astra.data2d.get(sino_id)

x = np.zeros((100, 100))
for i in range(10000):
    raytransform(x)
```
![memory_cuda](https://user-images.githubusercontent.com/12610714/92639394-0216d880-f2dc-11ea-8357-7560e89883b2.png)

## CPU:
```python
from math import sqrt, pi
import astra
import numpy as np

vol_geom = astra.create_vol_geom(100, 100, -0.5, 0.5, -0.5, 0.5)
proj_geom = astra.create_proj_geom('parallel', sqrt(2) / 200, 200, np.linspace(0, pi, 500))

im_id = astra.data2d.create('-vol', vol_geom)
proj_id = astra.projector.create({'type': 'line',
				  'VolumeGeometry': vol_geom,
				  'ProjectionGeometry': proj_geom,
				  'options': {}})
sino_id = astra.data2d.create('-sino', proj_geom)

forward_config = astra.astra_dict('FP')
forward_config['VolumeDataId'] = im_id
forward_config['ProjectionDataId'] = sino_id
forward_config['ProjectorId'] = proj_id
forward_alg_id = astra.algorithm.create(forward_config)

def raytransform(x):
    astra.data2d.store(im_id, x)
    astra.algorithm.run(forward_alg_id)
    return astra.data2d.get(sino_id)

x = np.zeros((100, 100))
for i in range(1000):
    raytransform(x)
```
![memory_cpu](https://user-images.githubusercontent.com/12610714/92639387-00e5ab80-f2dc-11ea-869c-d31038a93bdd.png)

**Comment by fsherry** [comment]
I think I might have found the issue. In the CUDA implementation of the parallel beam forward projection, the following function allocates memory that is never deallocated and the function is called for every angle:
https://github.com/astra-toolbox/astra-toolbox/blob/b1f9c6051205f4c4b03486e16d4697787865bf36/cuda/2d/par_fp.cu#L242-L254

**Comment by fsherry** [comment]
Applying the fix in the pull request https://github.com/astra-toolbox/astra-toolbox/pull/256#issue-485459325, this issue is solved, as evidenced by the memory profile shown below:
![memory_cuda_fixed](https://user-images.githubusercontent.com/12610714/92973136-cdde1c00-f483-11ea-8be8-b49694f7b8af.png)

**Comment by wjp** [comment]
Thank you for the analysis and fix! Much appreciated.
