### ISSUE TITLE
Mask option for FP3D-CUDA and BP3D-CUDA

### ISSUE THREAD

**Issue by Mikerov** [astra-toolbox/astra-toolbox#258]
Does Astra provide an option to mask volumes and projections in FP3D-CUDA/BP3D-CUDA?
I receive a warning that this configuration option is unused. 

I would like to reduce the amount of data that I need to keep on the GPU. I thought that I could achieve it with masks. Is it possible? Is there another way to reduce the data that is used during iterative reconstruction (FP+BP) without manually reducing the data and adjusting geometry (offsets etc).

**Comment by wjp** [comment]
The mask options in ASTRA are implemented in a way that doesn't reduce the amount of memory used on the GPU; it still stores the full volumes. We don't have a way to automate this manually cutting up the volume like you describe.
