### ISSUE TITLE
Incomplete error messages for MATLAB

### ISSUE THREAD

**Issue by Sophilyplum** [astra-toolbox/astra-toolbox#259]
from matlab/tools/astra_create_proj_geom.m, lines 109--120 (this is not the only instance of this issue but an example):

```
elseif strcmp(type,'parallel_vec')
	if numel(varargin) < 2
		error('not enough variables: astra_create_proj_geom(parallel_vec, det_count, V')
	end
	if size(varargin{2}, 2) ~= 6
		error('V should be a Nx6 matrix, with N the number of projections')
	end
	proj_geom = struct( ...
		'type',					'parallel_vec',  ...
		'DetectorCount',		varargin{1}, ...
		'Vectors',				varargin{2}  ...
	);
```

Line 111 should read 
> error('not enough variables: astra_create_proj_geom(parallel_vec, det_count, V).')

Suggest a more MATLAB-like error message, which would be: 
> "Not enough input arguments." 

followed by a complete list of the required variables as above. Preferably highlight that they are **input** arguments.

**Comment by wjp** [comment]
Excellent suggestion, thanks!
