### ISSUE TITLE
Problem installing Astra Toolbox in Ubuntu

### ISSUE THREAD

**Issue by PauTorru** [astra-toolbox/astra-toolbox#26]
Hi,

I am trying to get the astra toolbox working with python 2.7 in Ubuntu 14.04. 
When I execute "make" in /build/linux  I get the following error:

/usr/local/cuda/bin/nvcc -gencode=arch=compute_20,code=sm_20 -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_50,code=compute_50 -I/usr/local/cuda/include -I../.. -I../../include -DASTRA_CUDA -Iusr/inlcude/mpi  -std=c++11 -DUSE_MPI=1 -c ../../cuda/3d/cgls3d.cu -o cuda/3d/cgls3d.o
../../cuda/3d/cgls3d.cu:41:17: fatal error: mpi.h: No such file or directory
 #include "mpi.h"
                 ^
compilation terminated.
make: *** [cuda/3d/cgls3d.lo] Error 1

I am also attaching the output of ./configure

By the way, the said "mpi.h" is found in /usr/lib/openmpi/include.

Any ideas on how can I get this working? What am I doing wrong?

Thank you.

[PAUconfigure.txt](https://github.com/astra-toolbox/astra-toolbox/files/134238/PAUconfigure.txt)

**Comment by wjp** [comment]
Thanks for your interest and report.

In the command line you gave, there's a typo in -Iusr/inlcude/mpi . Could you check if that is the cause?

**Comment by jbedorf** [comment]
Hi,
It looks like you are trying to build the mpi branch of Astra and have set the MPI flag to enabled. If this is on purpose, try adding this parameter to your configure line:
--with-mpi=/usr/lib/openmpi/include

**Comment by PauTorru** [comment]
Wow, sorry... Apparently I had set the --with-mpi parameter with the wrong path...

Thank you.

**Comment by PauTorru** [comment]
It looks like I could install astra. However, when importing it in python I get the following error:

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import astra
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/astra/python/astra/__init__.py", line 26, in <module>
    from . import matlab as m
  File "/usr/local/astra/python/astra/matlab.py", line 38, in <module>
    from . import astra_c
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory

**Comment by wjp** [comment]
The directory containing libcudart.so.7.5 (often /usr/local/cuda-7.5/lib64) should be in your LD_LIBRARY_PATH, or in ld.so.conf.

**Comment by PauTorru** [comment]
Ok, I added the path to LD_LIBRARY_PATH and now get the following error:

import astra
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/astra/python/astra/__init__.py", line 26, in <module>
    from . import matlab as m
  File "/usr/local/astra/python/astra/matlab.py", line 38, in <module>
    from . import astra_c
ImportError: /usr/local/astra/lib/libastra.so.0: undefined symbol: _ZN5astra25CCompositeGeometryManager4doBPEPNS_12CProjector3DEPNS_26CFloat32VolumeData3DMemoryEPNS_30CFloat32ProjectionData3DMemoryE

**Comment by wjp** [comment]
This error message usually appears if you're using an older version if astra. Please make sure that /usr/local/astra/lib/libastra.so.0 is the version of astra that you just compiled.

We also have a bug that sometimes not all necessary files get rebuilt. If libastra.so.0 seems up to date, you could try a 'make clean' followed by make, make install..

**Comment by PauTorru** [comment]
Ok, in /usr/local/astra/lib/ there is the file libastra.so.0 which apparently is linked to the file libastra.so.0.0.0, I don't if this is Ok?

After doing make clean, make, make install, I got a different error similar to the previous one.

import astra
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/astra/python/astra/__init__.py", line 26, in <module>
    from . import matlab as m
  File "/usr/local/astra/python/astra/matlab.py", line 38, in <module>
    from . import astra_c
ImportError: /usr/local/astra/lib/libastra.so.0: undefined symbol: ompi_mpi_op_sum

**Comment by wjp** [comment]
Could you check with 'ldd /usr/local/astra/lib/libastra.so.0' if it is linking against the right MPI library?

**Comment by PauTorru** [comment]
This is the output of ldd. I don't really understand it.

pau@pau-X555LD:~$ ldd /usr/local/astra/lib/libastra.so.0
	linux-vdso.so.1 =>  (0x00007ffc52fe2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f17aff97000)
	libcudart.so.7.5 => /usr/local/cuda-7.5/lib64/libcudart.so.7.5 (0x00007f17afd39000)
	libcufft.so.7.5 => /usr/local/cuda-7.5/lib64/libcufft.so.7.5 (0x00007f17a90fd000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f17a8b99000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f17a8895000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f17a858e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f17a81c9000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f17a7fb3000)
	/lib64/ld-linux-x86-64.so.2 (0x00005654686bf000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f17a7dae000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f17a7ba6000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f17a798d000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f17a7789000)

**Comment by PauTorru** [comment]
Any Idea of what should I do now?
I'm still getting the same error when trying to import astra in python.

**Comment by dmpelt** [comment]
Sorry for the late reply.

To me it seems that the `ldd` output shows that it is not linked to any mpi library. This might be because it is still the result of an older build, or because something is going wrong during compilation. Could you try to delete the `/usr/local/astra/` folder completely, and do a clean rebuild again (with a redownloaded source in an empty folder)? Afterwards, what does `ldd /usr/local/astra/lib/libastra.so.0` say?

Just out of curiosity, are you sure that you want to use the MPI capabilities of ASTRA? It is still a bit untested, so if you are not planning on using it, I would suggest to disable it during compilation (by simply not specifying it in `configure`).

**Comment by PauTorru** [comment]
Hey, 
Today I tried to install astra again from scratch on another computer (ubuntu 12.04) without MPI and it worked so maybe that was the problem.
