### ISSUE TITLE
How to get the projection matrix for each image

### ISSUE THREAD

**Issue by ramanpreet9** [astra-toolbox/astra-toolbox#260]
The toolbox reconstructs data in 3D using  lets say 100 2D images. 
For each image, we should have a projection matrix (W*P_3D = P_2D)
where P_3D is 3D points and P_2D is 2D points on each image.
Once we reconstruct the data, how do we obtain the projection matrices for each individual 100 images.

**Comment by wjp** [comment]
The projection matrix in ASTRA is computed on-the-fly as needed. We currently provide no functionality to obtain the matrix for 3D projections. You can of course form it explicitly one column at a time by projecting unit vectors.
