### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by mars11121** [astra-toolbox/astra-toolbox#261]
My environment is RTX3090 with ubuntu18.04, cuda 11.0, cudnn 8.0.4, I suffered environment-conflict when run "conda install astra-toolbox astra-toolbox", is there any solutions?

**Comment by wjp** [comment]
There are newer packages available in the `astra-toolbox/label/dev` channel.

**Comment by mars11121** [comment]
> There are newer packages available in the `astra-toolbox/label/dev` channel.

Very thanks, and I compile with the following instructions, which helps me successfully install astra-toolbox
cd build/linux
./autogen.sh   # when building a git version
./configure --with-cuda=/usr/local/cuda \
            --with-python \
            --with-install-type=module
make
make install
