### ISSUE TITLE
CPU multi-thread support ?

### ISSUE THREAD

**Issue by pierrepaleo** [astra-toolbox/astra-toolbox#263]
Hello,

When I follow the build instructions for python, everything works great, but it seems that CPU backprojector only uses one thread. 
So I wondered if the CPU implementation of backprojector is multi-threaded ; if so, do I have something special to do in the build process ?

Thanks in advance !

**Comment by wjp** [comment]
This would be very nice to have, but improving our CPU performance is not a current development priority unfortunately.
