### ISSUE TITLE
Support for newer python versions (>3.6)

### ISSUE THREAD

**Issue by wohe157** [astra-toolbox/astra-toolbox#265]
Hi

I was wondering if it would be possible to add support for newer python versions? I installed ASTRA through Anaconda, but this only works for python 3.6. This causes conflicts with other packages that require newer versions.

When trying to install ASTRA in a python 3.8 environment I get this error:
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - astra-toolbox -> python[version='2.7.*|3.5.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.6.*']

Your python: python=3.8
```

**Comment by wjp** [comment]
Hi,

We have conda packages for newer python versions available in our development channel `astra-toolbox/label/dev` .

**Comment by wohe157** [comment]
Thanks a lot, that worked for me!
Will this be supported in the (near) future in a release?

**Comment by Obi-Wan** [comment]
The answer is most certainly yes.

The upcoming ASTRA 2.0 (1.99dev) has been in the works for quite some time now. I also wonder what is the release plan / roadmap, but I guess this should be discussed in a different thread.
