### ISSUE TITLE
Fanflat reconstruction using FBP_CUDA gives strange results

### ISSUE THREAD

**Issue by nynal13** [astra-toolbox/astra-toolbox#269]
Hello everyone,

I am relatively new to Astra and currently trying to do different fanflat reconstructions using different algorithms. 
I noticed the following problem applying the FBP_CUDA algorithm:
I created a test object, let astra create the sinogram via astra.create_sino(...) and do the reconstruction. When I use FBP_CUDA, the reconstructed values are approximately a factor ~100 too small, while they seem to be reasonable when I use e.g. SIRT_CUDA or SART_CUDA. Also, the reconstructed values seem to depend heavily on the number of angles for FBP_CUDA. For a parallel beam setup I don't get this problem.
This is my python script:
```
import astra
import numpy as np
import matplotlib.pyplot as plt

detpixels = 256
pixelsize = 1.1 #mm
d_so = 500 #mm
d_od = 100 #mm
nb_angles = 180

algorithm = 'FBP_CUDA'
#algorithm = 'SIRT_CUDA'
iterations = 150 #only for iterative algorithms

vol_geom = astra.create_vol_geom(256, 256)
#proj_geom = astra.create_proj_geom('parallel', 1.0, detpixels, np.linspace(0.,np.pi,nb_angles,False))
proj_geom = astra.create_proj_geom('fanflat', 1.0, detpixels, np.linspace(0.,2*np.pi,nb_angles,False),(d_so+d_od)/pixelsize, 0)
                                       
# phantom
P = np.zeros((256,256))
for x in range(64,192):
    for y in range(64,192):
        P[x,y] = 0.5
        if(x> 100 and y >100):
            P[x,y] = 0.3

plt.figure()
plt.imshow(P,cmap=plt.cm.gray)
plt.colorbar().set_label(r'')
plt.title('Object')

### create sino from phantom
proj_id = astra.create_projector('cuda',proj_geom,vol_geom)
sinogram_id, sinogram = astra.create_sino(P, proj_id)
print("sinogram_id", sinogram_id)
print("sinogram type", type(sinogram))
#print(sinogram)

plt.figure()
plt.imshow(sinogram,cmap=plt.cm.gray)
plt.title('Sinogram')

#--- reconstruction ------------------------------------------

rec_id = astra.data2d.create('-vol', vol_geom)

cfg = astra.astra_dict(algorithm)
cfg['ReconstructionDataId'] = rec_id
cfg['ProjectionDataId'] = sinogram_id

alg_id = astra.algorithm.create(cfg)

if algorithm != 'FBP_CUDA':
    astra.algorithm.run(alg_id, iterations)
else:
    astra.algorithm.run(alg_id)

# Get the result and plot
rec = astra.data2d.get(rec_id)
plt.figure()
plt.imshow(rec,cmap=plt.cm.gray)
plt.colorbar().set_label(r'')
plt.title('Reconstruction. Algorithm '+algorithm+'. Number of angles: '+str(nb_angles))
plt.show()

# Clean up
astra.algorithm.delete(alg_id)
astra.data2d.delete(rec_id)
astra.data2d.delete(sinogram_id)
astra.projector.delete(proj_id)
```
Here are example plots made with this script to illustrate the problem:

![object](https://user-images.githubusercontent.com/77120059/103933038-0be20880-5123-11eb-9612-cda63ee43537.png) 
![fanflat_FBPCUDA_180angles](https://user-images.githubusercontent.com/77120059/103933097-21efc900-5123-11eb-872a-6b27c5a4e218.png)
![fanflat_FBPCUDA_90angles](https://user-images.githubusercontent.com/77120059/103933083-1d2b1500-5123-11eb-8d5a-f78df475c821.png)
![fanflat_SIRTCUDA_180angles](https://user-images.githubusercontent.com/77120059/103933069-18666100-5123-11eb-8765-dbd8e4864d1e.png)

I installed astra via conda and I use python 2.7. I also got the development packages via `conda install -c astra-toolbox/label/dev astra-toolbox` 

Does anyone have an idea what's the problem here? Any help is very much appreciated!

**Comment by wjp** [comment]
Thanks for the report. This should be fixed with the current version 2.0. Please feel free to re-open this issue if it still occurs for you.
