### ISSUE TITLE
Problems with non GPU build of Astra in Ubuntu VM

### ISSUE THREAD

**Issue by markbasham** [astra-toolbox/astra-toolbox#27]
Hi,

Sorry about this but I am having issues with getting my build up and running in ubuntu. I currently am using the following commands to get things going

    >>> git clone https://github.com/astra-toolbox/astra-toolbox.git
    >>> cd astra-toolbox/build/linux
    >>> ./autogen.sh 
    >>> ./configure --with-python --prefix=/home/mark/opt/astra
    >>> make -j4

But I get the following error:

    astra/astra_c.cpp: In function ‘PyObject* __pyx_pf_5astra_7astra_c_8set_gpu_index(PyObject*, PyObject*, PyObject*)’:
    astra/astra_c.cpp:1173:3: error: ‘SGPUParams’ is not a member of ‘astra’
       astra::SGPUParams __pyx_v_params;
       ^

I also had a look at using the download of the stable release, 1.7.1, but when I build that, I get the error :

    astra/experimental.cpp: In function ‘PyObject* __pyx_pf_5astra_12experimental_do_composite(PyObject*, PyObject*, PyObject*, PyObject*, PyObject*)’:
    astra/experimental.cpp:884:3: error: ‘CCompositeGeometryManager’ is not a member of ‘astra’
       astra::CCompositeGeometryManager __pyx_v_m;
       ^
which seems to be the fixed problem #21 

Any help would be really appreciated :)

Mark

**Comment by wjp** [comment]
Hi,

That looks like I forgot to make something conditional on CUDA support. It should be fixed by b74e64aef7845666d27cbf7e876a6a360eefed7f now. Thanks for the report!

-Willem Jan

**Comment by markbasham** [comment]
Works like a charm, thanks for the quick updates

Cheers

Mark
