### ISSUE TITLE
Maximum number of projections with 'parallel3d' geometry and SIRT3D_CUDA

### ISSUE THREAD

**Issue by pwrasmuss** [astra-toolbox/astra-toolbox#270]
Hello,

I am experiencing issues when going above 1024 projections when using `parallel3d` geometry and `SIRT3D_CUDA` algorithm. The reconstructed array is filled with NaNs or sometimes zeros when going above 1024 projections. I have included a minimal working example which can reproduce the error when I run it.

```python
import numpy as np
import astra
astra.set_gpu_index([0, 1])

num_row = 256
num_col = 256
num_proj = 1025
num_slice = 256
num_pixel = int(np.sqrt(2)*num_row)

angles = np.linspace(0, np.pi, num_proj, endpoint=False)

sinograms = np.zeros((num_slice, num_proj, num_pixel), dtype=np.float32)
sinograms[64:-64,:,50:-50] = 1
    
proj_geom = astra.create_proj_geom('parallel3d', 1, 1, num_slice, num_pixel, angles);
vol_geom = astra.create_vol_geom(num_row, num_col, num_slice)

sinograms_id = astra.data3d.create('-sino', proj_geom, sinograms)
rec_id = astra.data3d.create('-vol', vol_geom)
reco_alg = 'SIRT3D_CUDA'
cfg = astra.astra_dict(reco_alg)
cfg['ProjectionDataId'] = sinograms_id
cfg['ReconstructionDataId'] = rec_id
alg_id = astra.algorithm.create(cfg)

astra.algorithm.run(alg_id, 1)
rec = astra.data3d.get(rec_id)

astra.algorithm.delete(alg_id)
astra.data3d.delete(rec_id)
astra.data3d.delete(sinograms_id)

print(np.sum(np.isnan(rec))/rec.size, np.count_nonzero(rec == 0)/rec.size)
```
The script prints 
```
1.0 0.0
```
when I run it. If I change `num_proj = 1024` then it prints
```
0.0 0.5
```
This problem does not persist if `cone` geometry is used. Performing the reconstruction with 1025 projections on a slice by slice basis using `SIRT_CUDA` fixes the problem as well. Using the SIRT plugin for 3D data results in a segmentation error.

I guess it might be an initialisation/allocation issue.

Thanks in advance and kind regards,
Peter

**Comment by wjp** [comment]
I am unable to reproduce this with the current version 2.0. Please feel free to re-open this issue if it still occurs for you.
