### ISSUE TITLE
Tomosynthesis 3d reconstruction scaling problem

### ISSUE THREAD

**Issue by onejiin** [astra-toolbox/astra-toolbox#273]
Dear author,

Hi, thanks to ASTRA Toolbox, I am researching X-ray images :)

I have 1 question.
I am trying to perform a tomosynthesis 3d reconstruction.
In this case, I don’t know/understanding where the “detector pixel size” should be applied.

To efficient using toolbox, I am referring to paper, “Fast and flexible X-ray tomography using the ASTRA toolbox”, Wim van Aarl et al.
In chapter 4 of this paper, Non-conventional geometries of tomography, U and V vectors are defined as multiplied by “detector pixel size” (\deta t).
In chaper4.2 tomosynthesis, However, U and V vectors are defined by (1,0,0) (0,1,0).
**Here (\delta t, 0, 0) (0, \delta t,0) should be in this form, isn't it?**

As a result of using ASTRA Toolbox, I have a problem with 3D reconstuction scaling,  so I will contact you.
I will wait for your contact.

Best regards,
Wonjin

**Comment by rossha46** [comment]
delta t would be your physical pixel detector size, however in CT and other Computer Graphics applications, voxels are used (the 3D equivalent of a pixel which is dimensionless but given a unit size of 1). If your pixel size if 0.2, then any actual measurements can be multipled by 5 (1 / delta_t). This will give the correct inputs to ASTRA as far as I am aware. As for your output, any measurement you take between locations can be multiplied by delta_t to give the correct value. Hope this helps
