### ISSUE TITLE
Problem with implementation in octave

### ISSUE THREAD

**Issue by BieberleA** [astra-toolbox/astra-toolbox#275]
It seems that there is an issue between the current version of astra-toolbox and (my) Ubuntu 20.04. As I cloned the repository and performed the install instructions as mentioned in the readme.md the `./configure` command could not find my OCTAVE that I installed via

`sudo apt install octave`

For more information I attached the corresponding terminal together with the command I executed before. As my OCTAVE is not found the modules are finally not copied into the corresponding folder using `make install`. Could you please help? I'm using the toolbox for a long time (in Ubuntu 18.4) and it perfectly worked together with OCTAVE. Thank you in advance, André 

![Screenshot from 2021-02-22 16-15-50](https://user-images.githubusercontent.com/19644183/108728547-ff2a4000-7529-11eb-9c9b-595452021f7f.png)

HZDR: www.hzdr.de

**Comment by wjp** [comment]
Thank you for the report. Do you have the ubuntu package `liboctave-dev` installed? If so, could you attach the file `config.log` that is generated by configure? It might contain a clue to why Astra is not finding Octave.

**Comment by BieberleA** [comment]
Thank you very much for the fast reply. After installing `liboctave-dev` my OCTAVE became known to the astra-toolbox installation. Now everything is working as expected. I already reconstructed an image. The hint could/should be implemented to the install instruction (Readme.md). Thanks again. André

**Comment by wjp** [comment]
Great to hear that that solved it. Explicitly mentioning it is a good suggestion, and I've added it as a note in the paragraph on Octave in the readme now.

**Comment by ricounet67** [comment]
I have the same issue with Ubuntu 24.04 and sudo apt install liboctave-dev doesn't work

**Comment by wjp** [comment]
@ricounet67 If installing liboctave-dev doesn't help, I expect it is probably a different issue. Could you open a new bug report and attach the output of configure and the file config.log so that we can investigate? Thanks.
