### ISSUE TITLE
Changing the example implementation from pylab to matplotlib

### ISSUE THREAD

**Issue by kolibril13** [astra-toolbox/astra-toolbox#277]
As can be found here:
https://github.com/matplotlib/matplotlib/blob/200ebe1dcb8c8adb9ed4d177f02a57686ffef085/lib/matplotlib/pylab.py#L7-L11
and here:
https://queirozf.com/entries/matplotlib-pylab-pyplot-etc-what-s-the-different-between-these#pylab
The use of pylab is not encouraged these days.
So I think that changing to matplotlib in the python example section would be a good idea.
So:
```
import matplotlib.pyplot as plt
plt.imshow(R, cmap="gray")
plt.show()
```
instead of:
```
import pylab
pylab.gray()
pylab.imshow(R)
pylab.show()
```
If you like this idea, I volunteer to make a pull request on this.

**Comment by meetaig** [comment]
I really like this idea! Would be a great addition to the toolbox. The documentation needs some updating anyway :)

**Comment by kolibril13** [comment]
Thanks for your answer! :)
I've now started a pull request, closing this now.
