### ISSUE TITLE
Retrieve filtered sinogram with FDK

### ISSUE THREAD

**Issue by RendersJens** [astra-toolbox/astra-toolbox#285]
Is there a way to get acces (in python) to the filtered sinogram when using FDK? In such a way that applying BP3D_CUDA to it, would give the complete FDK reconstruction.

This would be very useful when running FDK multiple times on the same sinogram, for example when aligning a geometry, or when reconstructing multiple volumes of interest (e.g. slices) from the same sinogram.

**Comment by MaxBe23** [comment]
Why you don not split it? 

Using your own filtering and jumping then into BP3D_CUDA. I did because I got some trouble with the filtering in Astra and with serperated way it worked like a charm.
