### ISSUE TITLE
Artifact on sinogram after FP

### ISSUE THREAD

**Issue by IloveASTRA** [astra-toolbox/astra-toolbox#288]
Hi
I am trying to reconstruct an uneven resolution volume,
I.e. each voxel is not isotopic - for example [x,1,1]
I noticed that when x> 8 the FP results (the 2D sinograms) gets an artifact - some black and white stripes
Even if the reconstruction is done on an "empty" volume (of ones)
Can someone tell me more about is? Maybe this is a physical phenomenon? Maybe some bug?
What can I do to solve the problem?
![Screenshot](https://user-images.githubusercontent.com/84117771/118082791-7901f500-b3c6-11eb-8259-46450539142d.png)

**Comment by MaxBe23** [comment]
Perhaps some problems with the filtering and the padding during the FFT? 

Cheers

**Comment by askorikov** [comment]
If that's still relevant, can you provide a minimal reproducible example?
