### ISSUE TITLE
Load real cone-beam projections to python

### ISSUE THREAD

**Issue by Pawelip** [astra-toolbox/astra-toolbox#289]
Hello,
I have CT data with a cone-beam tomograph. I have 900 projections with a resolution of 2000x1332 px. I have a problem with loading this data into the toolbox. Can I ask you for an example how to use eg. numpy to create a matrix [x, rotate, y] so that I can use it in ASTRA? 

thank you for every answer, best regards 
Pawel

**Comment by hzz0033** [comment]
You can refer this tutorial:
https://tomroelandts.com/articles/astra-toolbox-tutorial-reconstruction-from-projection-images-part-2

**Comment by MaxBe23** [comment]
Hey, 

you can use the cv2 package for Python and do something like this: 

`proj = np.zeros((params['nu'],params['nProj'],params['nv']), dtype=float)`

and then fill this empty array with the images: 

`for i in range(params['nProj']):
    proj[:,i,:] = cv2.imread(folders['projection_dir'][i],2)`

Hope this will help you.
