### ISSUE TITLE
Astra on docker with cuda available

### ISSUE THREAD

**Issue by Mojzaar** [astra-toolbox/astra-toolbox#291]
Hi,

I am going to use the Astra toolbox on my docker with TensorFlow in Ubuntu 18.04 with cuda:10.0-cudnn7 with python 3.6.5 installed in my docker.  I have installed Astra toolbox with " CUDA_ROOT=/usr/local/cuda/ MAKEOPTS="-j 16" pip3 install astra-toolbox". I had some problems installing with source code and I don't want to install it via conda. 
When I check the TensorFlow (V1) Cuda availability it returns true but astra.astra.use_cuda()  returns false! I passed the Cuda directory to my bash with the $LD_LIBRARY_PATH but I am not sure why I still cannot have the Cuda enabled Astra. Would you please help me?

For your reference, I have included my docker file.

[Docker.txt](https://github.com/astra-toolbox/astra-toolbox/files/6604820/Docker.txt)

**Comment by ahendriksen** [comment]
In general, it is not recommended to use tensorflow with ASTRA. Tensorflow allocates all GPU memory. Therefore, ASTRA cannot allocate required intermediate buffers and will crash. 

Installation instructions for use on Google Colab can be found here: 
https://colab.research.google.com/drive/18B1UuJA5tALPHAVOVNHEgkjbD_Hm0ux-?usp=sharing

Maybe that helps to get it working your container :)
