### ISSUE TITLE
handling half-scan cone-beam CT (CBCT)

### ISSUE THREAD

**Issue by aziabari** [astra-toolbox/astra-toolbox#295]
Hello,

Could you please elaborate on how we can modify and use this code to run FDK for half-scan (180+fan angle) CBCT measurement?

Thank you,

**Comment by MaxBe23** [comment]
Hey, 

on which part do oyu need help? 

Cheers

**Comment by X-Rayven** [comment]
Ye at the beginning and at the moment I'm just using the FBP_3DCUDA and some geometric functions of the toolbox. I like to be a little bit more flexible in this case I starteted with my own filters and weights and after image processing I put it  into the reconstruction. 

I think in the reconstruction itself, they don't have parkerweights or they do have?

**Comment by wjp** [comment]
I am unable to reproduce this with the new version 2.0. Please feel free to re-open the issue if it still occurs for you, and please then also add a script to reproduce this.
