### ISSUE TITLE
Hangs with FBP_CUDA on RTX3070 and RTX3090

### ISSUE THREAD

**Issue by dmpelt** [astra-toolbox/astra-toolbox#296]
I tried to run astra (both label/dev and stable anaconda builds) on some recent RTX3070 and RTX3090 machines. On both machines, forward projection and backprojection work fine on GPU, but FBP_CUDA (called trough an astra.OpTomo object) hangs, after which I have to kill the process. I just tested SIRT_CUDA, and that works fine...

**Comment by jiayangshi** [comment]
Same issue, FBP_CUDA couldn't run through on RTX 3070. In my case, it was called by astra.algorithm.run(). And SIRT_CUDA in deed works.

**Comment by wjp** [comment]
That sync issue is now fixed by 7f5a50d5b142fe8aeea22754b9895d1fae25e662. Hopefully that resolves this hang too.
