### ISSUE TITLE
FDK Filtering Problems

### ISSUE THREAD

**Issue by X-Rayven** [astra-toolbox/astra-toolbox#302]
Hey, 

during reconstruction I noticed that FDK algorithm has problems with projection, which have no air outside. For example if you have specimen, where you a have a special field of view. 

The Results showing a corona around the object, see image 1. 

![reco_0449_false](https://user-images.githubusercontent.com/60846549/136162510-25273f59-2603-4384-844b-331851b159fd.png)

I could eliminate that with the filter and a padding during FFT transformation. I'm not sure how ASTRA is filtering during FDK but it would be nice to implement that, that users who have such type of data has no problems during FDK. 
If I did sometrhing wrong let me know or if there is an option to fix that in the toolbox itself. 

Here is my own image with my own filtering. Hope you can see the difference. 

![reco_0449_right](https://user-images.githubusercontent.com/60846549/136162536-df34333a-f4b1-40af-a3ab-e29cd7307056.png)

Just in case somebody has the same problems or is interested in some solution.

**Comment by godspeedlucip** [comment]
Have you ever find solutions? I have met the same question, which is using filter in 3D reconstruction by astra.
