### ISSUE TITLE
Some questions on Ramp Filter generation

### ISSUE THREAD

**Issue by z0gSh1u** [astra-toolbox/astra-toolbox#310]
Hi, I'm a beginner learning CT image reconstruction. I'm currently having some confusion on Ramp Filter generation. It would be very nice if you can help me with these questions.

Please see: https://github.com/astra-toolbox/astra-toolbox/pull/59/files

In the previous frequency domain convolution, we have

```
pfFilt[iDetectorIndex] = 2.0f * fRelIndex;
```

to generate Ramp Filter. I'd like to ask **why a factor `2.0f` is used** to adjust the amplitude of the kernel.

Also, in the current spatial domain convolution version, we have

```
pfFilt[iDetectorIndex] = 2.0f * pfData[2*iDetectorIndex];
```

There is also a factor `2.0f`.

**What's more,** why do we only keep the real part of the FFT of the kernel, since FFT of sinogram will be multiplied with it later, and the imaginary part of FFT of sinogram won't be zero, so the imaginary part of FFT of the kernel will interact with it.

**Besides,** to better understand the imaging geometry, which detector does `iDetectorIndex = 0` mean? It is the middle one of the detector array, or the first one?

These are all my questions. Thanks a lot!

**Comment by wjp** [comment]
Hi, for the analytic derivations of these filters I can recommend the book Principles of Computerized Tomographic Imaging by Kak and Slaney, section 3.3 (freely available from Slaney's website). That has more background information and derivations than our source code, and also less implementation details to distract from the actual algorithm.

The kernel is symmetric, and therefore has a real FFT.

In that file the name iDetectorIndex is sometimes used in the Fourier domain and sometimes in the spatial domain. Usually in the spatial domain the index 0 would correspond to the first detector element, while in the Fourier domain it would usually correspond to the central (DC) frequency.
