### ISSUE TITLE
FDK filter type & truncation correction

### ISSUE THREAD

**Issue by Hoonly** [astra-toolbox/astra-toolbox#312]
1. why the filter type of FDK can not be changed? I saw that it was fixed in source code
![image](https://user-images.githubusercontent.com/20243833/144847184-d4878fe3-d805-47d0-89b2-8fe802a25917.png)

2. Have you considered adding a truncation correction algorithm？I can preprocess it in the projection data, but due to that this correction should be applied after parker weighting, it can not be added in matlab workflow now.

**Comment by leekunpeng** [comment]
> 1. why the filter type of FDK can not be changed? I saw that it was fixed in source code
>    ![image](https://user-images.githubusercontent.com/20243833/144847184-d4878fe3-d805-47d0-89b2-8fe802a25917.png)
> 2. Have you considered adding a truncation correction algorithm？I can preprocess it in the projection data, but due to that this correction should be applied after parker weighting, it can not be added in matlab workflow now.

I am also very interested in this, please let me know if there is a solution. Thanks！

**Comment by Hoonly** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已收到，谢谢。

**Comment by askorikov** [comment]
These features are not available at the moment, but you can implement the filtering part in Matlab/Python (which should be computationally inexpensive, especially with GPU acceleration) and only use the backprojection algorithm after.

**Comment by Hoonly** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已收到，谢谢。

**Comment by Hoonly** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已收到，谢谢。

**Comment by MarkatLiu** [comment]
> These features are not available at the moment, but you can implement the filtering part in Matlab/Python (which should be computationally inexpensive, especially with GPU acceleration) and only use the backprojection algorithm after.

Hi askorikov, can you please share some examples on hwo to  perform filtering and bakprojection seperately for 3D reconstruction? Many thanks.

**Comment by Hoonly** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已收到，谢谢。

**Comment by hyaihjq** [comment]
> 1. why the filter type of FDK can not be changed? I saw that it was fixed in source code
>    ![image](https://user-images.githubusercontent.com/20243833/144847184-d4878fe3-d805-47d0-89b2-8fe802a25917.png)
> 2. Have you considered adding a truncation correction algorithm？I can preprocess it in the projection data, but due to that this correction should be applied after parker weighting, it can not be added in matlab workflow now.

请问怎么解决truncation correction问题的？

**Comment by Hoonly** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已收到，谢谢。
