### ISSUE TITLE
Can not build astra 2.0.0 on Debian unstable

### ISSUE THREAD

**Issue by picca** [astra-toolbox/astra-toolbox#315]
Hello, I am trying to build astra in order to update the Debian package.

with boost 1.74, cuda 11 and gcc11

but the configure part failed with this error message

```
configure:16907: checking if boost and CUDA versions are compatible
configure:16917: /usr/lib/ccache/nvcc -c -o conftest.o conftest.cu 
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with '...':
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         '_ArgTypes'
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with '...':
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         '_ArgTypes'
configure:16920: $? = 1
configure: failed program was:
| #include <boost/shared_ptr.hpp>
| int main() {
|   return 0;
| }
configure:16932: result: no
configure:16934: error: Boost and CUDA versions are incompatible. You probably have to upgrade boost.
```

look at this error message it seems related to a template syntax

Are you aware of this ?

**Comment by picca** [comment]
It seems that there is a bug in gcc11

https://github.com/NVIDIA/nccl/issues/614

**Comment by codehelp** [comment]
It isn't as simple as a bug in gcc-11.

I've tested with gcc-12 and with gcc-10 - astra-toolbox 2.1.0 fails to build in exactly the same way.

nvidia-cuda-toolkit                              11.4.3-2+b1
libboost-dev:amd64                               1.74.0.3

gcc-10 build using CC=gcc-10 CXX=g++-10 :
[astra.txt](https://github.com/astra-toolbox/astra-toolbox/files/8513009/astra.txt)

**Comment by askorikov** [comment]
In any case, it doesn't look like a bug on astra's side.
