### ISSUE TITLE
CUDA Error: Failed to allocate 512x512 GPU buffer on RTX 3090

### ISSUE THREAD

**Issue by jiayangshi** [astra-toolbox/astra-toolbox#316]
Error message:
```
Error: CUDA error 222: the provided PTX was compiled with an unsupported toolchain..
Error: Failed to allocate 512x512 GPU buffer
python: ./../../src/CudaReconstructionAlgorithm2D.cpp:293: virtual void astra::CCudaReconstructionAlgorithm2D::initCUDAAlgorithm(): Assertion `ok' failed.
Aborted
```

This code on RTX 3090 24GB keeps throwing error, astra is installed with `conda install -c astra-toolbox astra-toolbox
` in a clean environment, and its version is 
```# Name                    Version                   Build  Channel
astra-toolbox             2.0.0            py39h4319877_1    astra-toolbox
libastra                  2.0.0               cuda_11.3_0    astra-toolbox
```
The same code could run through without error on RTX 2080 and RTX 3070.

The code:
```
import astra
import numpy as np

sinogram = np.random.random((1024,512)) # load a sinogram

vol_geom_slice = astra.creators.create_vol_geom(512, 512)
recon_id = astra.data2d.create("-vol", vol_geom_slice)
proj_geom_slice = astra.creators.create_proj_geom('parallel', 1, 512, np.linspace(0, np.pi, 1024, True))

sino_id = astra.data2d.create("-sino", proj_geom_slice, sinogram)
algo = 'FBP_CUDA'
cfg2 = astra.astra_dict(algo)
cfg2['ProjectionDataId'] = sino_id
cfg2['ReconstructionDataId'] = recon_id

algo_id = astra.algorithm.create(cfg2)
astra.algorithm.run(algo_id)
recon = astra.data2d.get(recon_id)

astra.algorithm.delete(algo_id)
astra.data2d.delete(sino_id)
astra.data2d.delete(recon_id)
```

**Comment by wjp** [comment]
Thanks for the report. Does this work with the development packages (version 2.0.9) in our astra-toolbox/label/dev channel? (`conda install -c astratoolbox/label/dev astra-toolbox`) Some relevant compilation options are updated in those.

**Comment by jiayangshi** [comment]
Thanks for the answer. I tried development package on 3090, 3070 and 2080. They all work now.
```
# Name                    Version                   Build  Channel
astra-toolbox             2.0.9            py39h4319877_0    astra-toolbox/label/dev
libastra                  2.0.9               cuda_11.3_0    astra-toolbox/label/dev

```

**Comment by wjp** [comment]
That's great to hear. Thanks for testing on all GPUs!

**Comment by wuniii** [comment]
Error: zeroVolume: CUDA error 1: invalid argument.
Error: FanBP: CUDA error 700: an illegal memory access was encountered.
Error: copyVolumeFromDevice: CUDA error 700: an illegal memory access was encountered.
python3.7: ./../../src/CudaReconstructionAlgorithm2D.cpp:338: virtual void astra::CCudaReconstructionAlgorithm2D::run(int): Assertion `ok' failed.
my error is similar with you , can you help me?

**Comment by askorikov** [comment]
Hi, can you provide a minimal example to reproduce the issue and also the output of `conda list 'astra-toolbox|libastra'?

**Comment by wuniii** [comment]
邮件我已收到，会尽快阅读
