### ISSUE TITLE
blurry Image reconstruction using SIRT3D_CUDA algorithm

### ISSUE THREAD

**Issue by blauyang** [astra-toolbox/astra-toolbox#317]
The difference in sharpness between the images produced using the FDK_CUDA and SIRT3D_CUDA algorithms is significant. 
 The first image is generated by the SIRT3D_CUDA algorithm and the second by the FDK_CUDA algorithm. I used 150 iterations of the SIRT3D_CUDA algorithm to produce this reconstructed image.
The SIRT3D_CUDA algorithm uses the cone_vec (3D cone beam geometry specified by 3D vectors) geometry. The FDK_CUDA algorithm uses a normal cone geometry (proj_geom = astra_create_proj_geom('cone',  det_spacing_x, det_spacing_y, det_row_count, det_col_count, angles, source_origin, origin_det)).

<img width="621" alt="ef691ea6a85c0924d12113546b50815" src="https://user-images.githubusercontent.com/87274625/149621656-3138c22d-e407-4f95-9633-ada191b9777a.png">
SIRT3D_CUDA

![kkk](https://user-images.githubusercontent.com/87274625/149621890-835516fb-debd-4f5b-aa94-e0da5ac1a6f8.PNG)
FDK_CUDA

The code is as follows*（SIRT3D_CUDA）

vectors = zeros(numel(angles), 12);
for i = 1:numel(angles)

	% source
	vectors(i,1) = -sin(angles(i)) * distance_source_origin/VoxelSizeX;
	vectors(i,2) = -cos(angles(i)) * distance_source_origin/VoxelSizeX
	vectors(i,3) = 0;	

	% center of detector
    vectors(i,4) = sin(angles(i)) * distance_origin_detector/VoxelSizeX;
    vectors(i,5) = cos(angles(i)) * distance_origin_detector/VoxelSizeX;
    vectors(i,6) = 0;

	% vector from detector pixel (0,0) to (0,1)
	vectors(i,7) = cos(angles(i))*DetectorSpacingX/VoxelSizeX;
	vectors(i,8) = -sin(angles(i))*DetectorSpacingX/VoxelSizeX;
	vectors(i,9) = 0;

	% vector from detector pixel (0,0) to (1,0)
	vectors(i,10) = 0;
	vectors(i,11) = 0;
	vectors(i,12) = 1*DetectorSpacingY/VoxelSizeX;		
end

% Parameters: #rows, #columns, vectors
proj_geom = astra_create_proj_geom('cone_vec', detector_rows, detector_cols, vectors);
projections_id    = astra_mex_data3d('create', '-proj3d', proj_geom, projections);    

%% Create reconstruction.
vol_geom = astra_create_vol_geom(volumeSizeX, volumeSizeY, volumeSizeZ);
reconstruction_id = astra_mex_data3d('create','-vol', vol_geom);
cfg = astra_struct('SIRT3D_CUDA');
cfg.ReconstructionDataId = reconstruction_id;
cfg.ProjectionDataId = projections_id;

% Create the algorithm object from the configuration structure
algorithm_id = astra_mex_algorithm('create', cfg);

% Run iterations of the algorithm
astra_mex_algorithm('iterate', algorithm_id, 150);
reconstruction = astra_mex_data3d('get', reconstruction_id);

**Comment by wjp** [comment]
At first glance this looks like it could be more of a visualisation issue than a reconstruction issue. See if the displayed range of values is comparable in the two reconstructions.
