### ISSUE TITLE
MiltiGPU does not work 

### ISSUE THREAD

**Issue by Mojzaar** [astra-toolbox/astra-toolbox#318]
I am going to use the FBP as a PyTorch layer in my model. To carry out the training I need to use multiple GPUs. I followed the provided example and set `astra.set_gpu_index(list(range(torch.cuda.device_count())))` and wrap model in Dataparallel mode. However, there is a problem and having multiple GPU halts the training at very beginning!

Am I missing something about Astra? Does it support multi-GPU implementation for PyTorch?

**Comment by wjp** [comment]
astra.set_gpu_index with a list of GPUs indices will make astra use multiple GPUs for every individual FBP call.

While I'm not very familiar with pytorch's DataParallel mode, from what I understand, that will split up the training over multiple devices itself. That sounds like it would conflict with Astra's own multi-GPU handling. It should work fine if you have astra in (the default) single-GPU mode.

I would suggest also taking a look at the pytorch integration provided by tomosipo at https://github.com/ahendriksen/tomosipo . In particular the sample at https://github.com/ahendriksen/tomosipo/blob/master/notebooks/learned_pd_lightning.py looks relevant.
