### ISSUE TITLE
Running ASTRA on Jetson Xavier NX, basic CUDA functionality tests fail

### ISSUE THREAD

**Issue by aisosalo** [astra-toolbox/astra-toolbox#329]
We have attempted to utilize the ASTRA Toolbox on a [Jetson Xavier NX](https://developer.nvidia.com/embedded/jetson-xavier-nx) device with 384-core NVIDIA Volta™ GPU with 48 Tensor Cores. The operating system is L4T (Linux for Tegra) and it’s currently at version 32.4.2 which comes default with Ubuntu 18.04.

The ASTRA tests with parametr 'cuda' are failing. Does anyone here have experience on running ASTRA functions on Jetson devices?

Here is what we have done:

```
# Virtual environment
python3.6 -m venv astra_env3.6
source astra_env3.6/bin/activate

sudo apt-get install python3.6-dev

#wget https://repo.download.nvidia.com/jetson/common/pool/main/c/cuda-toolkit-10-2/cuda-toolkit-10-2_10.2.460-1_arm64.deb
#sudo apt install ./cuda-toolkit-10-2_10.2.460-1_arm64.deb

sudo nvpmodel -m 0
sudo jetson_clocks

pip install --upgrade pip

# Compatibility Library
pip install six

# Dependencies
pip install Cython
pip install numpy
pip install scipy

# Downloading and building the ASTRA Toolbox
git clone https://github.com/astra-toolbox/astra-toolbox.git
cd astra-toolbox/build/linux
./autogen.sh
./configure --with-cuda=/usr/local/cuda --with-python --with-install-type=module
make
make install
```

According to the log everything seems to go well, Python checks and CUDA checks.

Running
```
python
>>> import astra
>>> astra.test()
```
produces though the following output:
```
ASTRA Toolbox v2.1.0
Getting GPU info... GPU #0: Xavier, with 7773MB
Testing basic CPU 2D functionality...
Testing basic CUDA 2D functionality...
vg: {'option': {'WindowMinX': -16.0, 'WindowMaxX': 16.0, 'WindowMinY': -1.0, 'WindowMaxY': 1.0}, 'GridRowCount': 2, 'GridColCount': 32}
pg: {'type': 'parallel', 'DetectorWidth': 1, 'DetectorCount': 32, 'ProjectionAngles': [0]}
proj_id: 5
vol: [[0.28635971 0.63769284 0.60925968 0.41059231 0.15340192 0.19105215
  0.7077704  0.76610116 0.84508421 0.31476097 0.56899393 0.87255856
  0.44372977 0.15287647 0.82377982 0.9815391  0.74331011 0.52241107
  0.49778621 0.03881029 0.40476135 0.16276452 0.9559422  0.36550274
  0.96994949 0.67912528 0.45996371 0.60159247 0.37094663 0.14354627
  0.31886824 0.07315799]
[0.45619408 0.48514432 0.91593215 0.19979986 0.62558614 0.47523196
  0.03423413 0.45860549 0.08731845 0.82216769 0.70680854 0.93116652
  0.651305   0.11671216 0.34460399 0.94414344 0.93397011 0.21372567
  0.47408543 0.47010665 0.10257098 0.38391788 0.30727981 0.7956086
  0.75004709 0.03210808 0.70824047 0.5513133  0.5689744  0.5960419
  0.37354463 0.26573112]]
(sino_id, sino): (7, array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32))
err: 1.9845480011632959 < 1e-6
Error
Testing basic CUDA 3D functionality... Error
```

Running more complicated experiments result errors with various severity:
```
python: ./../../cuda/2d/par_bp.cu:195: bool astraCUDA::BP_internal(float*, unsigned int, float*, unsigned int, const astraCUDA::SDimensions&, const astra::SParProjection*, float): Assertion `e1 == cudaSuccess' failed.
Aborted (core dumped)
```

Any help is grately appreciated!

**Comment by katjasrz** [comment]
In the config [astra-toolbox](https://github.com/astra-toolbox/astra-toolbox/tree/fa2ec619edb2994e828897e80c06e7fb35c55c44)/[build](https://github.com/astra-toolbox/astra-toolbox/tree/fa2ec619edb2994e828897e80c06e7fb35c55c44/build)/[linux](https://github.com/astra-toolbox/astra-toolbox/tree/fa2ec619edb2994e828897e80c06e7fb35c55c44/build/linux)/configure.ac line 150 https://github.com/astra-toolbox/astra-toolbox/blob/fa2ec619edb2994e828897e80c06e7fb35c55c44/build/linux/configure.ac#L150 

there is a list of CUDA architectures, and it doesn't have any Jetson in it. Jetson would be 53 (TX1, Nano), 62 (TX2), and 72 (AGX, NX).
 
To make it on an NX, you could either add these numbers or simply replace this line with `with_cuda_compute="72"`.

It also might be necessary to install a specific version of numpy:

```
pip install "numpy==1.19.4"
```

**Comment by aisosalo** [comment]
We can confirm that the fix proposed by @katjasrz resolves the issue, many thanks!

**Comment by wjp** [comment]
I'm glad that resolves it. It may be simpler to use the command line argument `./configure --with-cuda-compute=72` instead of modifying configure.ac though.
