### ISSUE TITLE
No GPU support available on HPC cluster

### ISSUE THREAD

**Issue by physlin** [astra-toolbox/astra-toolbox#331]
I've been using ASTRA on my local Linux cluster for years. I'm not sure what changed recently or if it has anything to do with me updating conda, but the reconstruction code I've been using for quite awhile has suddenly stopped working. I'm getting the following error message:

Error: allocateVolume: CUDA error 35: CUDA driver version is insufficient for CUDA runtime version.
Error: Failed to allocate 2549x2549 GPU buffer
python: ./../../src/CudaReconstructionAlgorithm2D.cpp:293: virtual void astra::CCudaReconstructionAlgorithm2D::initCUDAAlgorithm(): Assertion `ok' failed.
Aborted (core dumped)

I opened up an ipython interpreter to try to figure out what was going on, and I got this:

In [2]: astra.test()
No GPU support available
ASTRA Toolbox v2.1.0
Testing basic CPU 2D functionality... Ok

Any idea why it's not recognising the GPU? I'm working on a login node with an NVIDIA Tesla P4, and I have the current CUDA module loaded (10.1).

**Comment by physlin** [comment]
I have tried downgrading to cudatoolkit 10.1.243-h6bb024c_0 and libastra 2.1.0-cuda_10.1_0 to ensure that they are compatible with the loaded CUDA module (10.1) to no avail. I still get:

In [2]: astra.test()
No GPU support available
ASTRA Toolbox v2.1.0
Testing basic CPU 2D functionality... Ok

and

In [3]: astra.astra.use_cuda()
Out[3]: False

**Comment by physlin** [comment]
@wjp any ideas on this? I've tried three different miniconda/anaconda installations with no luck. I've tried it on the Remote Desktop, login node, and compute nodes as well. It just doesn't recognise the GPUs, which are all NVIDIA. I'd try it on my laptop, but I have an M1 Max.

**Comment by wjp** [comment]
I don't think anything relevant changed on astra's side. Were there any major changes to the cluster software? Does the command-line tool nvidia-smi show the GPU? And which driver version does nvidia-smi report?

**Comment by physlin** [comment]
Hi @wjp thanks for your response. I'm not sure what changed. It must have been something on the cluster side, because it wasn't working at the end of the day on Friday and suddenly started working Monday, at least on some of the GPUs. I hadn't changed anything. nvidia-smi shows the CUDA version and driver version, which it didn't last week. Thanks again.
