### ISSUE TITLE
pixel size

### ISSUE THREAD

**Issue by zhihan0210** [astra-toolbox/astra-toolbox#336]
Hello,
I would like to create a projection geometry using the function "create_proj_geom" in astra, especially for fan-beam. The unit of parameters (det_width, source_origin, origin_det) is in millimeter, but how does it relate to the pixel size of the image to be projected? Is the detector pixel size equal to the image pixel size?
Thank you.

**Comment by aenne-abel** [comment]
Hi,
Astra Toolbox needs all distances etc. in pixels. Therefore you need to recalculate all your parameters to pixels.
Let's say, you reconstruct on a volume geometry with 120x120 pixels and you know, that originally your detector width was 50 mm. Then one pixel is 50mm/120 so ca. 0.417 mm large. You will need to divide your source_origin and origin_det by this pixel size in order for it to work.
The parameter det_width specifies how large the detector spacing is in pixel. If you use exactly the same amount of pixel in your volume geometry as you have detectors, you can set this parameter to 1. If you want to reconstruct on double the amount of pixels as you have detectors, this parameter needs to be one etc. 
This might be a late reply but maybe it will help someone looking at this issue.
