### ISSUE TITLE
What is the projection model used in 'fanflat' geometry with 'cuda' projector? 

### ISSUE THREAD

**Issue by Sam078** [astra-toolbox/astra-toolbox#337]
Hi,

Sorry if this is not the correct place to ask this question. I am asking it here because I could not find an answer in the documentation.

How can I find what is the projection model (line, strip etc.) used in 'fanflat' geometry with 'cuda' projector?

That is, what is the projection model used with following code:

```
proj_geom = astra_create_proj_geom('fanflat', det_width, det_count, angles, source_origin, origin_det);
proj_id = astra_create_projector('cuda', proj_geom, vol_geom);
sinogram_id, sinogram = astra.create_sino(data, proj_id)
```

Thank you very much.

**Comment by askorikov** [comment]
Hi! As far as I'm aware, linear projector (aka Joseph kernel) is used for `cuda` projector.
