### ISSUE TITLE
Diagonal Artefacts with Cone Beam

### ISSUE THREAD

**Issue by aenne-abel** [astra-toolbox/astra-toolbox#338]
I have simulated some data with a cone beam source and a flat detector using Geant4. I now want to create a tomography with astra toolbox. 
As a reference intensity I created simulation data without an object with 10 times more incident particles than the other simulation angles with object. Because of this reference simulation having statistical fluctuations, I get circular lines around the center of the image, that' fine and does not concern me.

However my tomographies show weird diagonal lines. The "box_hole_shift" object is supposed to be an aluminium square with a side length of 5cm and a circular hole filled with air at x=1cm. The "siemens_star" object is a siemens star with radius 3.9 cm. Every second segment is made of air, the segment materials in between the air segments alternate between PVC and Aluminium.

![Tomography_box_hole_shift_Aluminium_neutron_ISO8529_2022_06_03_20_1_off](https://user-images.githubusercontent.com/107397117/173316543-39f50de5-4f4b-4462-b3b3-4264de883d3d.jpeg)
![Tomography_siemens_star_Air_gamma_4 44_2022_06_03_20_1_off](https://user-images.githubusercontent.com/107397117/173316551-750e1677-ec15-4cad-8468-46b4d205a49a.jpeg)

I triple checked every distance used in the astra toolbox reconstruction. 
After rebinning the data to get more counts per bin and calculating the absorption my code is as following:

vol_geom = astra.create_vol_geom(pixels, pixels)

vectors = np.zeros((num_rows,6))
for i in range(0,num_rows):
vectors[i,0] = np.sin(angles[i])*float(source_dist)/size_pixel	
vectors[i,1] = -np.cos(angles[i])*float(source_dist)/size_pixel
vectors[i,2] = -np.sin(angles[i])*float(det_dist)/size_pixel		
vectors[i,3] = np.cos(angles[i])*float(det_dist)/size_pixel
vectors[i,4] = np.cos(angles[i])*pixel_per_bin				
vectors[i,5] = np.sin(angles[i])*pixel_per_bin
proj_geom = astra.create_proj_geom('fanflat_vec', num_cols, vectors)

sinogram_id = astra.data2d.create('-sino', proj_geom, absorption)
sinogram = astra.data2d.get(sinogram_id)

rec_id = astra.data2d.create('-vol', vol_geom)

cfg = astra.astra_dict('SIRT_CUDA')	#CGLS_CUDA, sort of makes minconstraint on its own
cfg['ReconstructionDataId'] = rec_id
cfg['ProjectionDataId'] = sinogram_id
cfg['Option']={}
if (supersampling == "on"):
cfg['Option']['PixelSuperSampling'] = pixel_per_bin	# supposed to make reconstruction better if pixel_per_bin > 1 but I cannot see a difference
if (minConstraint == "on"):
cfg['Option']['MinConstraint'] = 0	# absorption cannot be lower than zero

alg_id = astra.algorithm.create(cfg)

astra.algorithm.run(alg_id, nIterations)

rec = astra.data2d.get(rec_id)
reconstruction = rec/size_pixel*pixel_per_bin	# divide reconstruction by pixel size to get absorption in 1/cm, for some reason one also needs to multiply by pixel_per_bin

astra.algorithm.delete(alg_id)
astra.data2d.delete(rec_id)
astra.data2d.delete(sinogram_id)

Does anyone know what could cause these kind of artefacts? It is also possible that the error lies in the simulated data but I can't seem to find the problem and I have no clue where else to look.

Thank you in advance.

**Comment by wjp** [comment]
From the first image I would guess the rotation direction (cw/ccw) of the simulation is the opposite of astra's. Try flipping the angles to see if that helps.
