### ISSUE TITLE
Inconsistent and even wrong result of SIRT_CUDA when repeating running the reconstruction code

### ISSUE THREAD

**Issue by houqh13** [astra-toolbox/astra-toolbox#343]
Hi, all!
I want to compare the reconstructions at different DSO & DSD in fanbeam geometry, so I need to reconstruct several times in one run.
When I debugged my code, I found that in one run, some recon images looked well, but the other ones showed evident strip artifacts (please check the image below). Then I tried repeating reconstruction under same geometry configuration, the issue wasn't solved. Also I found:
1. the first reconstuction always looks "correct" under my dozens of tests, which means in jupyter notebook, I have to restart the kernal instead of run the cell again to guarentee the correctness of the result;
2. but even "correct" images are slightly different (`astra.algorithm.get_res_norm()` returns different values);
3. wrong reconstruction appears randomly.

My questions:
1. How do the wrong results appear?
2. What can I do to avoid this issue?
3. As the recon images are different every time, what is the random part in SIRT_CUDA code?

Thank you!

My test code is as following:

```python
import astra
import matplotlib.pyplot as plt
import numpy as np
from phantominator import ct_shepp_logan

# parameters
distance_source_to_center = 200
distance_center_to_detector = 250
detector_pixel_size = 0.8
detector_resolution = 1024
projection_number = 720
angles = np.linspace(0, 2 * np.pi, projection_number, endpoint=False)
recon_pixel_size = 0.5
recon_resolution = 512

# initialize CT geometry
projection_geometry = astra.create_proj_geom('fanflat', detector_pixel_size, detector_resolution, 
                                             angles, distance_source_to_center, distance_center_to_detector)
boundary = recon_pixel_size * recon_resolution / 2
volume_geometry = astra.create_vol_geom(recon_resolution, recon_resolution, 
                                        -boundary, boundary, -boundary, boundary)

# sinogram
image = ct_shepp_logan(recon_resolution)
projector_id = astra.create_projector('cuda', projection_geometry, volume_geometry)
sinogram_id, sinogram = astra.create_sino(image, projector_id)

# SIRT reconstruction
for i in range(10):
    recon_id = astra.data2d.create('-vol', volume_geometry, 0)
    SIRT_config = astra.astra_dict('SIRT_CUDA')
    SIRT_config['ProjectionDataId'] = sinogram_id
    SIRT_config['ReconstructionDataId'] = recon_id
    SIRT_config['option'] = {'MinConstraint': 0}
    SIRT_id = astra.algorithm.create(SIRT_config)
    astra.algorithm.run(SIRT_id, 200)
    recon = astra.data2d.get(recon_id)
    print(astra.algorithm.get_res_norm(SIRT_id))
    astra.algorithm.delete(SIRT_id)
    astra.data2d.delete(recon_id)

astra.projector.delete(projector_id)
astra.data2d.delete(sinogram_id)
```
A typical wrong reconstruction image is as following:

![image](https://user-images.githubusercontent.com/26644358/188821148-40d79a5e-684f-4277-9f35-5c7267fecc6c.png)

**Comment by wjp** [comment]
Hi,
I am not able to reproduce this inconsistency here, and get consistent results even after running your sample loop hundreds of times. Are you overclocking your GPU, or is it maybe overheating? (Since the streaks originating from a single point indicate a possible single pixel memory glitch.) Do you have access to a different machine to try it on? Also make sure your GPU driver and ASTRA are the latest version.

**Comment by houqh13** [comment]
Thank you for the quick reply!
After some troubleshooting, it's exactly a GPU issue (though it was not overclocked or overheated). I had never met this kind of problem and the display was all normal, so I didn't consider from hardware.
Now I change the GPU to a new one and everything goes well. Thanks for your help again!
