### ISSUE TITLE
How to compensate for the offset caused by center of projection and center of rotation for cone-beam?

### ISSUE THREAD

**Issue by mingdianliu** [astra-toolbox/astra-toolbox#345]
Hi. I would like to use Astra to reconstruct some images taken by a cone-beam X-ray. Just want to know how could I compensate for the offset caused by the center of projection and center of rotation. I reviewed all issues related to my question but none of them can resolve this issue. Could you please help me with this issue? Thank you very much.

**Comment by ZZF0** [comment]
I have the same problem. Have you solved your problem? If it is solved, can you tell me the solution, thank you!

**Comment by askorikov** [comment]
Hi! The most appropriate and general solution would be to create a [`cone_vec`](https://www.astra-toolbox.com/docs/geom3d.html#projection-geometries) projection geometry taking into account the shift in the rotation axis (you can also take a look into [`tomosipo`](https://github.com/ahendriksen/tomosipo) library for some help in handling geometries). In the simple case of a lateral shift in the rotation axis, you can also shift all of your projections in the opposite direction to compensate it.

**Comment by mingdianliu** [comment]
> I have the same problem. Have you solved your problem? If it is solved, can you tell me the solution, thank you!

Hi. I have manually implemented the offset compensation in Astra Toolbox. You can take this link for reference. https://github.com/mingdianliu/astra-toolbox-for-cone-beam

**Comment by askorikov** [comment]
You can also check the following example: [samples/python/s022_fbp_cor.py](https://github.com/astra-toolbox/astra-toolbox/blob/0692e88447b6416b21ddf728dfcf9aa34a90ffca/samples/python/s022_fbp_cor.py)
