### ISSUE TITLE
SIRT with TV Regularization

### ISSUE THREAD

**Issue by RadouaneBjm** [astra-toolbox/astra-toolbox#350]
Good Morning all,

I want to combine the SIRT_CUDA  with TV regularization using Astra, but I'm not quite sure about my implementation. below how I am doing this.I would be very grateful if you could give me your feedback about the script that i'm using.

Thank you, 

    detector_size = sinogram.shape[1]
    rec_size=dectector_size
    vol_geom = astra.create_vol_geom(rec_size, rec_size)
    proj_geom = astra.create_proj_geom('parallel', 1.0, detector_size, angles)

    sinogram_id = astra.data2d.create('-sino', proj_geom, data=sinogram)
    rec_id = astra.data2d.create('-vol', vol_geom)
    proj_id = astra.create_projector('cuda', proj_geom, vol_geom)
    cfg = astra.astra_dict(SIRT_CUDA)
    cfg['ReconstructionDataId'] = rec_id
    cfg['ProjectionDataId'] = sinogram_id
    cfg['ProjectorId'] = proj_id

    alg_id = astra.algorithm.create(cfg)
    niters=150
    residual_error = np.zeros(niters)
         
    for i in range(niters):
        astra.algorithm.run(alg_id, 1)
        residual_error[i] = astra.algorithm.get_res_norm(alg_id)
        rec = astra.data2d.get(rec_id)
        TV=np.sum(np.abs(rec[1:,:] - rec[:-1,:])) + \
            np.sum(np.abs(rec[:,1:] - rec[:,:-1]))
        astra.data2d.store(rec_id,data=rec+regularization_parameter*TV)

    rec = astra.data2d.get(rec_id)

**Comment by askorikov** [comment]
I don't think this algorithm will converge to a solution that minimizes TV, since SIRT is just not designed for this task. There are several implementations of TV-regularized reconstruction algorithms available on GitHub (Chambolle-Pock and FISTA algorithms are probably most popular). For example, you can check https://github.com/romanakmath/Chambolle-Pock.
