### ISSUE TITLE
How to assign SinogramMask

### ISSUE THREAD

**Issue by houqh13** [astra-toolbox/astra-toolbox#351]
My understanding is that both ReconstructionMask & SinogramMask need to be assigned as binary matrices. For ReconstructionMask I have verified that a non-binary mask may lead to a wrong recon result, but for SinogramMask I observed different behaviour.

My test code is as follows:
```python
import astra
import numpy as np
import phantominator
from skimage.metrics import peak_signal_noise_ratio

angles = np.linspace(0, 2 * np.pi, 720, endpoint=False)
image = phantominator.ct_shepp_logan(512)
proj_geom = astra.create_proj_geom('fanflat', 1.5, 1024, angles, 400, 400)
vol_geom = astra.create_vol_geom(512, 512)
proj_id = astra.create_projector('cuda', proj_geom, vol_geom)
sino_id, sino = astra.create_sino(image, proj_id)

# sino_mask = sino > 0        # binary mask
sino_mask = sino            # non-binary mask
recon_mask = image > 0

sino_mask_id = astra.data2d.create('-sino', proj_geom, sino_mask)
recon_mask_id = astra.data2d.create('-vol', vol_geom, recon_mask)
recon_id = astra.data2d.create('-vol', vol_geom, 0)

alg_cfg = astra.astra_dict('SIRT_CUDA')
alg_cfg['ProjectionDataId'] = sino_id
alg_cfg['ReconstructionDataId'] = recon_id
alg_cfg['option'] = {}
alg_cfg['option']['SinogramMaskId'] = sino_mask_id
alg_cfg['option']['ReconstructionMaskId'] = recon_mask_id
alg_cfg['option']['MinConstraint'] = 0
alg_id = astra.algorithm.create(alg_cfg)
astra.algorithm.run(alg_id, 200)
recon = astra.data2d.get(recon_id)
psnr = peak_signal_noise_ratio(image, recon, data_range=image.max() - image.min())

astra.algorithm.delete(alg_id)
astra.data2d.delete([sino_id, sino_mask_id, recon_id, recon_mask_id])
astra.projector.delete(proj_id)
```
The recon result when `sino_mask = sino` is better than that when `sino_mask = sino > 0`. 

Can anyone explain why this happens? How should I assign SinogramMask? Which one is correct?

**Comment by askorikov** [comment]
The idea behind using a sinogram mask is that you can remove unwanted parts from your input during reconstruction (e.g. if there are unwanted objects in the field of view that you would want to mask out). Given that, the sinogram mask is expected to be binary. Passing a floating point mask is technically possible, but it's difficult to see why you would want that. In the case you provided it probably slightly accelerates convergence of the algorithm, but it's not guaranteed to be useful in other cases (depending on the level of noise and the type of object). You can test noisy case by applying some Poisson noise to the sinogram:
```python
sino_noisy = np.random.poisson(sino)
sino_id = astra.data2d.create('-sino', proj_geom, sino_noisy)
```
