### ISSUE TITLE
How Can I Import another x- ray projection image to Astra toolbox to do FBP?

### ISSUE THREAD

**Issue by JamesHOEEEE** [astra-toolbox/astra-toolbox#352]
In windows matlab version, is there any support for importing other images (eg .mat) and then do the FBP method?

**Comment by Obi-Wan** [comment]
Can you to be a bit more precise with your question? As it is it formulated, we do not know what you mean by "importing": What are the characteristics of these images (e.g. size, type of data, etc)? What are you exactly trying to achieve (e.g. loading the data, creating the geometry, having the data assigned to a data object, etc)?

Probably, a piece of code with clear specifications of what it is currently doing and what you are trying to achieve would also help.

**Comment by JamesHOEEEE** [comment]
hi Obi-Wan 
Sorry, I didn't describe the problem clearly. What I want to ask is that I have a set of X-ray Scan datasets (projection images) in .mat format. I refer to example S014, how do I import my images into the example and set geometry parameters? Or is there any other reference document that can help me reconstruct CT slices?

**Comment by leekunpeng** [comment]
> hi Obi-Wan Sorry, I didn't describe the problem clearly. What I want to ask is that I have a set of X-ray Scan datasets (projection images) in .mat format. I refer to example S014, how do I import my images into the example and set geometry parameters? Or is there any other reference document that can help me reconstruct CT slices?

One solution is to first create the geometric phantom information you need, then load your data into it to create the reconstruction. However, it should be noted that for 3D data, the projection dimension is [U porjAngles V], where U and V are the horizontal and vertical widths of the detector, respectively, and projAngles is the number of projection angles.

**Comment by askorikov** [comment]
@JamesHOEEEE I also don't quite understand the problem. If we refer to the example s014, your projection images would be the `sinogram` variable and geometry parameters would be the arguments to the `astra_create_proj_geom` function. More details about the both can also be found in the [documentation](https://www.astra-toolbox.com/docs/index.html).
