### ISSUE TITLE
Should the volume size be equal on each axis?

### ISSUE THREAD

**Issue by mingdianliu** [astra-toolbox/astra-toolbox#353]
Hi. Thanks for providing such a wonderful tool.

When I set the volume geometry as follows:

```
## configuration of reconstruction space
x_min, x_max = -20, 20 # [mm] reconstruction volume range
y_min, y_max = -20, 20 # [mm] reconstruction volume range
z_min, z_max = -10, 10  # [mm] reconstruction volume range

x_vol_sz, y_vol_sz, z_vol_sz = 1500, 1500, 750 # volex number for x, y, z. Please make sure x_vol_sz=y_vol_sz
```

the code will bring an error as follows:
`The dimensions of the data do not match those specified in the geometry: (1500, 1500, 750) != (750, 1500, 1500)`

Should the volume size be equal on each axis? If I want to set the volume size in the z-axis smaller than that in the x or y-axis, how could I do it? 

Thank you very much!

**Comment by askorikov** [comment]
Hi! The error most likely comes from the fact that volume data is expected to be in ZYX layout. This example should be helpful for you: https://github.com/astra-toolbox/astra-toolbox/blob/c628fc7c6e3de27967226307dfa7a1919ac8938d/samples/python/s006_3d_data.py#L43
