### ISSUE TITLE
How can I get cone beam projection matrix in 'linear3d' or 'linearcone' type?

### ISSUE THREAD

**Issue by WJSZSBD** [astra-toolbox/astra-toolbox#355]
I noticed that you have set 'linear3d' and 'linearcone' type in the create_projector() function prototype:
`def create_projector(proj_type, proj_geom, vol_geom, options=None):
    """Create a 2D or 3D projector.

:param proj_type: Projector type, such as ``'line'``, ``'linear'``, ...
:type proj_type: :class:`string`
:param proj_geom: Projection geometry.
:type proj_geom: :class:`dict`
:param vol_geom: Volume geometry.
:type vol_geom: :class:`dict`
:param options: Projector options structure defining ``'VoxelSuperSampling'``, ``'DetectorSuperSampling'``.
:type options: :class:`dict`
:returns: :class:`int` -- The ID of the projector.

"""
    if proj_type == 'blob':
        raise Exception('Blob type not yet implemented')
    cfg = astra_dict(proj_type)
    cfg['ProjectionGeometry'] = proj_geom
    cfg['VolumeGeometry'] = vol_geom
    if options is not None:
        cfg['options'] = options
    types3d = ['linear3d', 'linearcone', 'cuda3d']
    if proj_type in types3d:
        return projector3d.create(cfg)
    else:
        return projector.create(cfg)
`
But I can't use them. Is this feature not implemented yet? The error message is as follows:
File "astra\projector3d_c.pyx", line 59, in astra.projector3d_c.create
Exception: Unknown Projector3D type.

**Comment by WJSZSBD** [comment]
Here is how I call it:
`proj_id = astra.create_projector('linear3d', proj_geom, recon_vol_geom)`
The `proj_geom` is in 'cone_vec' type, and `recon_vol_geom = astra.create_vol_geom(2945, 2304, 50)`
I'd appreciate it if you could help me.

**Comment by askorikov** [comment]
Only `cuda3d` is currently a valid type of a 3D projector. However, `cuda3d` is implemented using a linear projector kernel, so `lenear3d`, `linearcone` and `cuda3d` should be effectively the same in my understanding.
