### ISSUE TITLE
Using multiple GPUs with Matlab Wrapper

### ISSUE THREAD

**Issue by JHoahg** [astra-toolbox/astra-toolbox#356]
Hi, 
I would like to run reconstructions in parallel started from a parfor loop (or similar Matlab construct).
Based on the loop index I want to choose one of the GPUs in the node.
The documentation says that one can use the options during algorithm creation to achieve that.
So thats what I tried:

```
cfg = astra_struct('FBP_CUDA');
cfg.ProjectionDataId = sinogram_id;
cfg.ReconstructionDataId = recon_id;
cfg.FilterType = 'Ram-Lak';
cfg.ProjectorId = proj_id;
cfg.option.GPUindex = GPUindex;
```
What I observed with nvidia-smi was, that only one GPU is used. I can switch the GPU with Matlab's gpuDevice() but then still only this one selected GPU is used for computation. I am trying this on a Matlab R2021b with 2xA6000 GPUs.
Has anyone achieved this already?

Best
Johannes

**Comment by askorikov** [comment]
This kind of `parfor` parallelization works for me. Could you provide an entire minimal reproducible example of your code?
