### ISSUE TITLE
Some question about projection data dimension.

### ISSUE THREAD

**Issue by leekunpeng** [astra-toolbox/astra-toolbox#358]
Hi~ Palenstijn, the dimension of the cone beam projection is [det_col_count, projNums, det_row_count], why set dimension in this oreder? Usually intuitively the data dimension is [det_col_count, det_row_count, projNums]. Is the underlying source code of C++ also defined in this way?

Best.
lee

**Comment by askorikov** [comment]
Hi Lee, I believe the layout currently used in Astra Toolbox (also in the C++/CUDA part) corresponds to viewing input data as a collection of [sinograms](https://en.wikipedia.org/wiki/Radon_transform), and it's not necessarily obvious that [det_col_count, det_row_count, projNums] layout is more intuitive.

**Comment by leekunpeng** [comment]
> Hi Lee, I believe the layout currently used in Astra Toolbox (also in the C++/CUDA part) corresponds to viewing input data as a collection of [sinograms](https://en.wikipedia.org/wiki/Radon_transform), and it's not necessarily obvious that [det_col_count, det_row_count, projNums] layout is more intuitive.

Hi askorikov，Thanks for your reply. As shown in the figure below, the dimension [x, y, z]. The projection under each angle falls on the xoz plane which [x, ,z], and increases in the dimension of y. Am I right?
![image](https://user-images.githubusercontent.com/61607176/213046869-c7d1a7f1-2529-49fe-a60f-af79c5340990.png)

**Comment by askorikov** [comment]
I'm not sure I can follow. Each projection falls on UV plane in this case.

**Comment by leekunpeng** [comment]
> I'm not sure I can follow. Each projection falls on UV plane in this case.
okay, got it. Thanks for your help !
