### ISSUE TITLE
How to use own projection data to reconstruction

### ISSUE THREAD

**Issue by yangshiyan** [astra-toolbox/astra-toolbox#361]
Dear experts,
         I want to use my own projection data which produced by MC simulatiuon and from real experiments  to reconstruction,  while i don't know how and where to assign my data to ASTRA toolbox, could you give me some advise?

**Comment by askorikov** [comment]
Hi! We have [documentation](https://www.astra-toolbox.com/docs/index.html) and [example scripts](https://github.com/astra-toolbox/astra-toolbox/tree/master/samples) that will help you with that.
