### ISSUE TITLE
create sino_id

### ISSUE THREAD

**Issue by Binganyuan** [astra-toolbox/astra-toolbox#365]
hello everyone , I want to get sinogram_id using "astra_mex_data2d" function, it's in matlab code. However, it shows that " The dimensions of the data do not match those specified in the geometry", but I checked data dimension is matched with geometry, like the guide shows (angles, det_num) . My codes are following:
        [angles_proj_geom,det_proj_geom] = size(rotation_fan_sinogram);
        proj_geom = astra_create_proj_geom('fanflat', 1.0, det_proj_geom, angles_proj_geom,1387,100);
        sinogram_id = astra_mex_data2d('create','-sino',proj_geom,rotation_fan_sinogram);

thanks a lot!

**Comment by askorikov** [comment]
Hi! The 4th variable in `astra_create_proj_geom` should be an array representing angle values (in radians), not just the number of angles.

**Comment by Binganyuan** [comment]
oh!&nbsp;&nbsp;tthanks&nbsp;&nbsp;a&nbsp;lot😊😊👍👍


---Original---
From: &quot;Alexander ***@***.***&gt;
Date: Wed, Mar 1, 2023 23:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [astra-toolbox/astra-toolbox] create sino_id (Issue #365)




 
Hi! The 4th variable in astra_create_proj_geom should be an array representing angle values (in radians), not just the number of angles.
 
&mdash;
