### ISSUE TITLE
Geometry class not initialized

### ISSUE THREAD

**Issue by navami123nair** [astra-toolbox/astra-toolbox#367]
Hello!!
   I was doing a project on image reconstruction using CBCT Scanner. For that I am using Astra Toolbox. While creating the geometries for the toolbox I have been facing this error message stating "Geometry class not initialized". I have created the volume geometry as "vol_geom = astra_create_vol_geom(image_columns, image_rows, num_slices);" and projection geometry as "proj_geom = astra_create_proj_geom('cone', detector_pixel, detector_pixel, detector_rows, detector_columns,proj_angles, dsd, (dsd-dso));". The proj_angles are in .txt format and I have loaded it successfully. Please help me to find what went wrong.
![error in astra_fdk](https://user-images.githubusercontent.com/126770219/222399058-00843d46-d3e0-49f7-b2de-742b0a416ee8.png)

**Comment by askorikov** [comment]
Hi! I think you need to use `astra_mex_data3d` function, since `cone` geometry is necessarily 3D.

**Comment by navami123nair** [comment]
Hi !!
  Thank You for the information. I will do the same.
