### ISSUE TITLE
ram-lak frequency cutoff

### ISSUE THREAD

**Issue by RadouaneBjm** [astra-toolbox/astra-toolbox#368]
Good morning all,

Is it possible to define the cutoff frequency of ram-lak filter on Astra using FBP_CUDA? for example in the ram-lak filtering step I want to keep only 90% of the Fourier space(0.9 normalized frequency cutoff of the filter) how can I do that? I looked at the documentation but I didn't find answer related to the filter cutoff frequency

Thank you,

**Comment by askorikov** [comment]
Hi! As far as I'm aware there's no such option, but you can pass you own filter to the FBP algorithm. In Matlab, you need to choose `projection` as the `FilterType` and pass your (frequency cutoff) filter as the `FilterSinogramId` parameter (see [here]( https://www.astra-toolbox.com/docs/algs/FBP_CUDA.html)). In Python you can also use `create_reconstruction` function (see [here](https://www.astra-toolbox.com/apiref/creators.html#astra.creators.create_sino)). A bit more information can be found here: https://github.com/astra-toolbox/astra-toolbox/blob/fa2ec619edb2994e828897e80c06e7fb35c55c44/include/astra/Filters.h#L60.

**Comment by RadouaneBjm** [comment]
@askorikov Thank you for your answer. I will take a look on it
Sorry, i forgot to say that I'm using python.

**Comment by wjp** [comment]
The `FilterD` option to `FBP_CUDA` lets you control the cut-off frequency. It defaults to 1.0, and you can make it smaller to cut off more of the filter.

**Comment by RadouaneBjm** [comment]
@wjp  is snippet script below correct allows to define correctly the filter ?
    
    cfg = astra.astra_dict("FBP_CUDA")
    cfg['ReconstructionDataId'] = rec_id
    cfg['ProjectionDataId'] = sinogram_id
    cfg['ProjectorId'] = proj_id
    cfg['FilterType'] = "ram-lak"
    cfg["FilterD"]=cutoff #between 0 and 1.0

**Comment by askorikov** [comment]
Hi @RadouaneBjm, did it work in the end?

**Comment by RadouaneBjm** [comment]
Hi @askorikov, sorry for my late reply. 
I can clearly see the smoothing effect when applying ram-lak filter with a lower frequency ( 0.2 or 0.3) so I guess it works.
