### ISSUE TITLE
Issue of generating projection matrix

### ISSUE THREAD

**Issue by Olin1461** [astra-toolbox/astra-toolbox#370]
Hi,

When I try to generate projection matrix using astra.create_proj_geom('cone_vec', det_row, det_col, vectors) and astra.OpTomo(proj_id).

 I got the error said ValueError: expected 1-d or 2-d array or matrix, got array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],)

This happen when I try to use parallel beam and cone beam but this error is gone when I decrease the det_row and det_col. Is there any corrspond realtionship between the image sizes and det_row and det_col? 

Thanks!

**Comment by Olin1461** [comment]
This error can be solved by changing number of voxel along x/y/z axis. But I get the blurry projection with too much noise. I am curious that if I change the size of the object (using cone beam), should I change other parameters too (such as pixel size along x and y axis or the distance parameters).

Thanks!

**Comment by askorikov** [comment]
Hi! I'm not sure I understand the issue. Could you provide a minimal reproducible example?
