### ISSUE TITLE
How to perform FBP when the sinogram is obtained in Fanflat mode?

### ISSUE THREAD

**Issue by Masaaki-75** [astra-toolbox/astra-toolbox#373]
I tried to wrap fanflat 2D forward projection and filtered back projection in a single Python class. But I was told that `FBP` in astra only supports `parallel` mode:
```
Error: FBP currently only supports parallel projection geometries.
```
Is it possible to perform FBP in fanflat mode?

PS. The most relevant issue may be #257; I looked it up and found:

- Adding `cfg['ProjectorId'] = proj_id` as wjp suggested doesn't seem to be working.
- For the combination of `proj_geom = astra.create_proj_geom('parallel'...` and `proj_id = astra.create_projector('line', ...)` produces no error message but results in an image with artifact.

**Comment by Masaaki-75** [comment]
And here's the minimal reproducible example code:

```Python
P = scipy.io.loadmat('phantom.mat')['phantom256']
angles = np.linspace(0, np.pi, 180, False)
source_distance = 1075
det_distance = 1075
proj_geom = astra.create_proj_geom('fanflat', 2.0, 672, angles, source_distance, det_distance)

vol_geom = astra.create_vol_geom(P.shape[-2:])
proj_id = astra.create_projector('strip_fanflat', proj_geom, vol_geom)
sinogram_id, sinogram = astra.create_sino(P, proj_id)

rec_id = astra.data2d.create('-vol', vol_geom)
cfg = astra.astra_dict('FBP')
cfg['ReconstructionDataId'] = rec_id
cfg['ProjectionDataId'] = sinogram_id
cfg['ProjectorId'] = proj_id
cfg['option'] = {'FilterType': 'Ram-Lak'}
alg_id = astra.algorithm.create(cfg)  # <-- error here
astra.algorithm.run(alg_id)
rec = astra.data2d.get(rec_id)
```

**Comment by askorikov** [comment]
Indeed, it is a missing feature at the moment. One workaround would be using the `FBP_CUDA` algorithm like in the issue you mentioned.
