### ISSUE TITLE
RuntimeError: Geometry class not initialized.

### ISSUE THREAD

**Issue by Morhafhaedar** [astra-toolbox/astra-toolbox#376]
i am facing this problem by running the following code. does anyone have a clue what is the problem and how to solve it?

import numpy as np
import astra
import glob
from   os.path import splitext, basename, join
from   imageio import imread,  imwrite

#astra.initialize()

num_images = 60
image_size = (3104, 3096)
filename = glob.glob("../Test_Input/*.png" )
image_data = np.zeros((num_images, image_size[0], image_size[1]), dtype=np.float32)
for i,image in enumerate(filename):
    pre,_   = splitext(basename(image))
    image   = imread(image)
    image   = np.array(image, dtype= np.float32)/(2**16 -1)
    image_data[i, :, :] = image  

num_angles = 60
angles = np.linspace(0, np.pi, num_angles, endpoint=False)
detector_size = 3096
detector_spacing_x = 1.0  # distance between detector pixels in the x direction
detector_spacing_y = 1.0  # distance between detector pixels in the y direction
source_origin      = 1.0
origin_det         = 1.0

# Create volume geometry
volume_geom = astra.create_vol_geom(detector_size, detector_size, detector_size)

# Create projection geometry
proj_geom = astra.create_proj_geom('cone', detector_spacing_x, detector_spacing_y, detector_size, detector_size, angles, source_origin, origin_det)

# Generate sinogram data
sinogram_id = astra.data2d.create('-sino', proj_geom, data=image_data)
sinogram = astra.data2d.get(sinogram_id)

# the error:
    sinogram_id = astra.data2d.create('-sino', proj_geom, data=image_data)
RuntimeError: Geometry class not initialized.

**Comment by wjp** [comment]
Hi,

The geometry (of type `cone`) that you're creating is a 3d geometry, so that requires using the `astra.data3d` family of data functions.
