### ISSUE TITLE
Python: Removed deprecated aliases to collections ABC in Python 3.10

### ISSUE THREAD

**Issue by paskino** [astra-toolbox/astra-toolbox#379]
From Python 3.10 deprecated aliases to [Collections Abstract Base Classes](https://docs.python.org/3.10/library/collections.abc.html#collections-abstract-base-classes) from the [collections](https://docs.python.org/3.10/library/collections.html#module-collections) module have been [removed](https://docs.python.org/3.10/whatsnew/3.10.html#removed).

Trying to set the GPU idx in astra 2.1 and python 3.10 leads to an exception:

```
File /mnt/data/edo/miniconda3/envs/cil_latest/lib/python3.10/site-packages/astra_toolbox-2.0.0-py3.10-linux-x86_64.egg/astra/astra.py:46, in set_gpu_index(idx, memory)
     40 def set_gpu_index(idx, memory=0):
     41     """Set default GPU index to use.
     42     
     43     :param idx: GPU index
     44     :type idx: :class:`int`
     45     """
---> 46     a.set_gpu_index(idx, memory)

File astra/astra_c.pyx:88, in astra.astra_c.set_gpu_index()

AttributeError: module 'collections' has no attribute 'Iterable'
```

https://github.com/astra-toolbox/astra-toolbox/blob/fa2ec619edb2994e828897e80c06e7fb35c55c44/python/astra/astra_c.pyx#L88

**Comment by wjp** [comment]
Thank you for the report. This should already be fixed in the latest conda packages (version 2.1.2). The path in your error message is referring to astra 2.0, so hopefully upgrading will fix this problem.
