### ISSUE TITLE
sinogram3d invertability

### ISSUE THREAD

**Issue by yongjinColinChoi** [astra-toolbox/astra-toolbox#386]
I have a question about sinogram3d function.

If I have a 3D Volume and project them using sinogram3d conebeam setting, and then reconstruct them using FDK algorithm, original 3D volume value and FDK output value is different. So I think FDK algorithm is not the invert function of sinogram3d. 

Then, Is there any method which is exactly inverse of sinogram3D in conebeam setting, so that if I repeat sinogram3D and inverse of it many times the end output is almost same as original 3D volume?

**Comment by askorikov** [comment]
Hi! In what way are the values different? Can you provide a minimal reproducible example? FDK is certainly not an exact inverse of the projection operation due to various factors, but maybe you mean some discrepancy beyond the expected differences.

**Comment by yongjinColinChoi** [comment]
I have a CT volume, the Min HU value is -1000, Max is 10000. After 3D Conebeam Projection and FDK reconstruction, the Min value changes to be about -1300, Max 12000. And repeat the same procedure, Min becomes about -3000, max about 15000. 
I want to repeat 3D conebeam Projection and Reconstruction many times without HU value changing alot. Is there any method I can do that?

**Comment by askorikov** [comment]
Min and max values are very sensitive to reconstruction artifacts and noise, which are expected for FDK with limited data. They cannot be eliminated, but you may obtain a closer correspondence to the original data when using iterative reconstruction algorithms like SIRT.
