### ISSUE TITLE
Inconsistent reconstructions

### ISSUE THREAD

**Issue by snipdome** [astra-toolbox/astra-toolbox#389]
# Bug description
After simulating projections with a conical projection geometry ('cone'), if you reconstruct on a volume geometry with cubic voxel size different 1, then reconstructing with FDK_CUDA or SIRT3D_CUDA lead to (significantly) different grey values. FDK is the right one in this case

# Expected behaviour
Reconstructed gray value is the same, regardless of the reconstruction algorithm or voxel size

# Since when
It was nicely working on previous versions of astra (2-3 years ago at least), not working anymore with 2.1.0

# Notes
It is not related to the iteration number or mismatching geometry

**Comment by wjp** [comment]
I don't seem to get this with current master. Do you have a script that reproduces the problem?

**Comment by snipdome** [comment]
The collegue who run into the problem is in vacation right now, so I cannot investigate further this situation. We can close this issue and we'll reopen another with a script reproducing the problem

**Comment by snipdome** [comment]
The collegue who run into the problem is in vacation right now, so I cannot investigate further this situation. We can close this issue and we'll reopen another with a script reproducing the problem
