### ISSUE TITLE
Basic functionality test error.

### ISSUE THREAD

**Issue by Knight-WP** [astra-toolbox/astra-toolbox#403]
Hello, when I run astra.test() after installing Astra, I encountered errors when attempting GPU calculations for 2D and 3D forward projection![image](https://github.com/astra-toolbox/astra-toolbox/assets/73821913/1657d261-6c36-426b-910d-5020a8e698ba)
I believe there might be an issue when executing create_sino and create_sino3d_gpu. Could you please confirm whether these two functions involve C++ code? Additionally, does this algorithm take into account the GPU's warpsize? I'm using a GPU with a warp size of 64, which is different from the more common 32.

**Comment by askorikov** [comment]
Hi! Yes, this error is from the C++ part of the code. Could you let us know the model of your GPU?

**Comment by Knight-WP** [comment]
> 你好！是的，这个错误来自代码的 C++ 部分。您能告诉我们您的 GPU 型号吗？
Sorry, I can't provide the specific GPU model, but it is very similar to AMD MI100

**Comment by Knight-WP** [comment]
> Hi! Yes, this error is from the C++ part of the code. Could you let us know the model of your GPU?
Sorry, I can't provide the specific GPU model, but it is very similar to AMD MI100

**Comment by askorikov** [comment]
It's not a Nvidia GPU then?

**Comment by Knight-WP** [comment]
> 
Yes, however, it can adapt well to applications on Nvidia GPUs, with the main difference arising from the warp size.

**Comment by askorikov** [comment]
Yeah, then it's hard for us to say what the problem might be. At the moment we don't support non-Nvidia GPUs, so I will close this issue for now. You can open a discussion instead though.

**Comment by Knight-WP** [comment]
> Yeah, then it's hard for us to say what the problem might be. At the moment we don't support non-Nvidia GPUs, so I will close this issue for now. You can open a discussion instead though.
Hello, the issue with the calculation has been resolved. The problem was in the copying process from the host to the device, where some padding data appeared on the machine I was using, affecting the correctness of the computation results.
