### ISSUE TITLE
No GPU support available after Astra installation

### ISSUE THREAD

**Issue by hrashidykanan** [astra-toolbox/astra-toolbox#407]
Hello all,

I tried to install the Astra package via Conda on our Linux server using conda install -c "astra-toolbox/label/dev" astra-toolbox command. Installation was successful. However, when I tested it using astra.test(), I got the following message:

No GPU support available
ASTRA Toolbox v2.1.3
Testing basic CPU 2D functionality... Ok

We have Tesla K80 Nvidia graphic card on our server.

I want to use GPU ability of Astra package.

Could you please assist me in this matter.
Thank you very much.

Hamidreza

**Comment by askorikov** [comment]
Hi! Can you use CUDA in any other application? Does your GPU get detected by `nvidia-smi` for example?

**Comment by hrashidykanan** [comment]
Hi,
Thank you very much for your reply.

My problem has been solved and now I get:

ASTRA Toolbox v2.1.3
Getting GPU info... GPU #0: Tesla K80, with 11441MB, CUDA compute capability 3.7
Testing basic CPU 2D functionality... Ok
Testing basic CUDA 2D functionality... Ok
Testing basic CUDA 3D functionality... Ok

Thank you again

**Comment by askorikov** [comment]
Okay, great!

**Comment by JChope** [comment]
> Hi, Thank you very much for your reply.
> 
> My problem has been solved and now I get:
> 
> ASTRA Toolbox v2.1.3 Getting GPU info... GPU #0: Tesla K80, with 11441MB, CUDA compute capability 3.7 Testing basic CPU 2D functionality... Ok Testing basic CUDA 2D functionality... Ok Testing basic CUDA 3D functionality... Ok
> 
> Thank you again

Hello, could you please show me how you solve the problem? 
Because I encounter the same problem. I'm also using Tesla K80 on a Linux server. 
Thank you very much.

**Comment by hrashidykanan** [comment]
> > Hi, Thank you very much for your reply.
> > My problem has been solved and now I get:
> > ASTRA Toolbox v2.1.3 Getting GPU info... GPU #0: Tesla K80, with 11441MB, CUDA compute capability 3.7 Testing basic CPU 2D functionality... Ok Testing basic CUDA 2D functionality... Ok Testing basic CUDA 3D functionality... Ok
> > Thank you again
> 
> Hello, could you please show me how you solve the problem? Because I encounter the same problem. I'm also using Tesla K80 on a Linux server. Thank you very much.

Hi,

In fact, my problem was that even though CUDA had already been installed on our server, I installed another CUDA again which was also incompatible with the previous one. So, after realizing, I removed the new installed CUDA and then tried to install ASTRA using "conda install -c "astra-toolbox/label/dev" astra-toolbox" command. That solved the problem. So, please make sure about CUDA installation on your server.

Good luck

**Comment by JChope** [comment]
> > > Hi, Thank you very much for your reply.
> > > My problem has been solved and now I get:
> > > ASTRA Toolbox v2.1.3 Getting GPU info... GPU #0: Tesla K80, with 11441MB, CUDA compute capability 3.7 Testing basic CPU 2D functionality... Ok Testing basic CUDA 2D functionality... Ok Testing basic CUDA 3D functionality... Ok
> > > Thank you again
> > 
> > 
> > Hello, could you please show me how you solve the problem? Because I encounter the same problem. I'm also using Tesla K80 on a Linux server. Thank you very much.
> 
> Hi,
> 
> In fact, my problem was that even though CUDA had already been installed on our server, I installed another CUDA again which was also incompatible with the previous one. So, after realizing, I removed the new installed CUDA and then tried to install ASTRA using "conda install -c "astra-toolbox/label/dev" astra-toolbox" command. That solved the problem. So, please make sure about CUDA installation on your server.
> 
> Good luck

ok, Thank you for your answer!
I'll check it.
