### ISSUE TITLE
Warning in astra.create.projection & astra.algorithm.create: "Exception: Unknown Projector2D./ Exception: Unknown Algorithm."

### ISSUE THREAD

**Issue by Cosme-liu** [astra-toolbox/astra-toolbox#434]
I am trying to run the samples in astra-toolbox (python), but when it comes to the function _astra.create_projector()_ and _astra.create_sino3d_gpu()_, an error comes out: 
(for sample 003)
Traceback (most recent call last):
  File "D:\pyCode\Reconstruction\samples\s003_gpu_reconstruction.py", line 35, in <module>
    proj_id = astra.create_projector('cuda',proj_geom,vol_geom)
  File "D:\anaconda3\envs\py39\lib\site-packages\astra\creators.py", line 567, in create_projector
    return projector.create(cfg)
  File "D:\anaconda3\envs\py39\lib\site-packages\astra\projector.py", line 36, in create
    return p.create(config)
  File "astra\\projector_c.pyx", line 63, in astra.projector_c.create
Exception: Unknown Projector2D.

(for sample 007)
Traceback (most recent call last):
  File "D:\pyCode\Reconstruction\samples\s007_3d_reconstruction.py", line 42, in <module>
    proj_id, proj_data = astra.create_sino3d_gpu(cube, proj_geom, vol_geom)
  File "D:\anaconda3\envs\py39\lib\site-packages\astra\creators.py", line 444, in create_sino3d_gpu
    alg_id = algorithm.create(cfg)
  File "D:\anaconda3\envs\py39\lib\site-packages\astra\algorithm.py", line 36, in create
    return a.create(config)
  File "astra\\algorithm_c.pyx", line 64, in astra.algorithm_c.create
Exception: Unknown Algorithm.

(Same error comes out when using the function _astra.algorithm.create()_ in another project)

However, when I use CPU reconstruction mode (e.g. sample 004), it works. It seems that something goes wrong when using CUDA/GPU for reconstruction. I'm relatively new to this and any help on this would be very welcome!
Environment: Python 3.9, Astra 2.1.2, NVIDIA RTX 3060, cudatoolkit 11.8.0

**Comment by askorikov** [comment]
Hi! Did you install Astra using conda? Can you run the following command to test the installation: `import astra; astra.test()`?

**Comment by Cosme-liu** [comment]
Hi! I did install astra using conda, and I can find the astra-toolbox (version 2.1.2) in conda list. The command returns: 
No GPU support available
ASTRA Toolbox v2.1.2
Testing basic CPU 2D functionality... Ok

**Comment by Cosme-liu** [comment]
> Hi! Did you install Astra using conda? Can you run the following command to test the installation: `import astra; astra.test()`?

Hi! I did install astra using conda, and I can find the astra-toolbox (version 2.1.2) in conda list. The command returns:
No GPU support available
ASTRA Toolbox v2.1.2
Testing basic CPU 2D functionality... Ok

**Comment by askorikov** [comment]
Can you maybe paste the entire output of `conda list 'astra-toolbox|libastra'` here?

**Comment by Cosme-liu** [comment]
> Can you maybe paste the entire output of `conda list 'astra-toolbox|libastra'` here?

The command returns:
'libastra' is not an internal or external command, nor is it a runnable program or a batch file.
It seems that 'libastra' cannot be found in astra-toolbox.

**Comment by askorikov** [comment]
Oh sorry, that's probably because this syntax does not work on Windows. Can you try `conda list libastra` separately (and also send the results of `conda list astra-toolbox`)?

**Comment by Cosme-liu** [comment]
Result 1:
# packages in environment at D:\anaconda3\envs\py39:
#
# Name                    Version                   Build  Channel
libastra                  2.1.2                hbc5358b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

Result 2:
# packages in environment at D:\anaconda3\envs\py39:
#
# Name                    Version                   Build  Channel
astra-toolbox             2.1.2            py39ha7fe896_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

**Comment by askorikov** [comment]
Then you probably have a CPU-only version of Astra from conda-forge channel (not officially supported by us). I would suggest trying to install Astra from astra-toolbox channel like `conda install astra-toolbox -c astra-toolbox`.

**Comment by Cosme-liu** [comment]
It works! Thank you so much!
