### ISSUE TITLE
Source, detector distance and reconstructed size inconsistency in fanflat and cone

### ISSUE THREAD

**Issue by feketeimre** [astra-toolbox/astra-toolbox#438]
Im not sure if this is intended or not but i find it confusing, perhaps i just misunderstood the docs.

In the case of fanflat https://github.com/astra-toolbox/astra-toolbox/blob/0d36033fa0c282dbfca7ca7011f8cdfe9575c445/python/astra/creators.py#L159-L168 and in the case of cone https://github.com/astra-toolbox/astra-toolbox/blob/0d36033fa0c282dbfca7ca7011f8cdfe9575c445/python/astra/creators.py#L191-L204 the last two parameters define the distances of source, object or origin and detector. To be explicit in case i understand something wrong: The last parameter is the distance measured from the object to the detector, the parameter before that is the distance measured from the source to the object. 

However if i set up a reconstruction according to this, i get bad reconstructed data (example 1 in code). If i swap the two parameters the reconstruction is flawless (example 2 in code). Also i found a blog post: [1](https://tomroelandts.com/articles/astra-toolbox-tutorial-reconstruction-from-projection-images-part-1), [2](https://tomroelandts.com/articles/astra-toolbox-tutorial-reconstruction-from-projection-images-part-2) where the detector is "shifted" into the object by altering the two parameters. This works for me as well (example 3 in code).

Here is my example:
```python
import numpy
import astra

projectionCount, detectorColumns = 1035, 1024
sinogram = numpy.fromfile("sinogram.raw", dtype= numpy.float16, count=projectionCount * detectorColumns).reshape(projectionCount, detectorColumns)
detectorPitch = 0.4
sourceDetectorDistance = 1248.95 / detectorPitch # distance from the source to the detector
sourceObjectDistance = 182.61 / detectorPitch # distance from the source to the object or origin
objectDetectorDistance = sourceDetectorDistance-sourceObjectDistance # distance from the object to the detector
offset = -9.680648987669935
angles = numpy.linspace(0, -numpy.pi*2, num=projectionCount, endpoint=False)

vol_geom = astra.creators.create_vol_geom(detectorColumns, detectorColumns)

# example 1: as described in docs, bad reconstructed data
#proj_geom = astra.create_proj_geom('fanflat', 1, detectorColumns,  angles, sourceObjectDistance, objectDetectorDistance)

# example 2: last two params swapped, good reconstructed data
proj_geom = astra.create_proj_geom('fanflat', 1, detectorColumns,  angles, objectDetectorDistance, sourceObjectDistance)

# example 3: shifting the detector into the origin or object, good reconstructed data
#proj_geom = astra.create_proj_geom('fanflat', 1, detectorColumns,  angles, (sourceObjectDistance + objectDetectorDistance), 0)

reconstruction_id = astra.data2d.create('-vol', vol_geom)
sinogram_id = astra.data2d.create('-sino', proj_geom, sinogram)

alg_cfg = astra.astra_dict('FBP_CUDA')
alg_cfg['ProjectionDataId'] = sinogram_id
alg_cfg['ReconstructionDataId'] = reconstruction_id

algorithm_id = astra.algorithm.create(alg_cfg)
proj_geom_cor = astra.geom_postalignment(proj_geom, [offset, offset])
astra.data2d.change_geometry(sinogram_id, proj_geom_cor)
astra.algorithm.run(algorithm_id)
reconstruction = astra.data2d.get(reconstruction_id)

import matplotlib.pyplot as plt
plt.imshow(reconstruction, cmap='gray')
plt.show()
```
sinogram.raw is in this zip: [sinogram.zip](https://github.com/astra-toolbox/astra-toolbox/files/13801824/sinogram.zip)

Also none of the working examples produce the right size of object. This pic comes from a reconstruction software that i trust provides the right results, here the object is roughly 600 voxel in size: ![vg](https://github.com/astra-toolbox/astra-toolbox/assets/15861028/e186da28-4ff9-44c4-9f80-978d39c4b936)
This is example 2 where i swapped the parameters, the object is roughly 502 voxel in size: ![example2](https://github.com/astra-toolbox/astra-toolbox/assets/15861028/ecca3ba7-6af9-4905-8d3f-043167580f06)
This is example 3 where the detector is "shifted" into the origin, the object is roughly 588 voxel in size.
![example3](https://github.com/astra-toolbox/astra-toolbox/assets/15861028/7761f6c4-6db1-4c83-9730-5663d33f1dd2)

I am unsure whats up with the incorrect size or how to provide astra with the correct distances.
This might not be an issue, if so i can move this into a discussion.

Thank you for the help in advance, 
Imre

**Comment by askorikov** [comment]
Hi! I think it comes from the fact that with your source-object and source-detector distances you have approximately 7 times magnification, so the voxel size should be `detectorPitch / magnification ≈ 0.06`, whereas the default in Astra is 1.0. One trick to solve it is to rescale all the distances like described in the blog you linked, another one is to set the desired voxel size in the volume geometry using [`minx`/`maxx`... options](https://astra-toolbox.com/apiref/creators.html#astra.creators.create_vol_geom). Here is an example of the latter approach:
```python
detectorPitch = 0.4
sourceDetectorDistance = 1248.95 # distance from the source to the detector
sourceObjectDistance = 182.61 # distance from the source to the object or origin
objectDetectorDistance = sourceDetectorDistance-sourceObjectDistance # distance from the object to the detector
offset = -9.680648987669935
angles = numpy.linspace(0, -numpy.pi*2, num=projectionCount, endpoint=False)

magnification = sourceDetectorDistance / sourceObjectDistance
min_x = -(detectorColumns / 2) * detectorPitch / magnification
max_x = (detectorColumns / 2) * detectorPitch / magnification
min_y = -(detectorColumns / 2) * detectorPitch / magnification
max_y = (detectorColumns / 2) * detectorPitch / magnification
vol_geom = astra.creators.create_vol_geom(detectorColumns, detectorColumns, min_x, max_x, min_y, max_y)

proj_geom = astra.create_proj_geom('fanflat', detectorPitch, detectorColumns, angles, sourceObjectDistance, objectDetectorDistance)
```
The remaining difference in the reconstructed size is more difficult to understand. I would suggest double-checking that all geometry parameters (including number of voxels and voxel sizes) are identical. Also, it's quite small at about 2% difference, so it can be just an imprecision of the manual measurement.

P.S. Can it be that your input intensities in the Astra case are not converted to absorption like `-np.log(sinogram / flatfield)`? Otherwise I'm not sure why contrast is so much worse than for external software.

**Comment by feketeimre** [comment]
Thank you for your reply. 

Your suggestions fixed the problem i had with the parameters.
The size difference problem was my fault in some ways. The external program exported the slices with different indexing. So the original image was not even at the same location where i was reconstructing the slices with Astra.
With logarithmization and padding i get the same contrast (did not include it in the original code):
![recon](https://github.com/astra-toolbox/astra-toolbox/assets/15861028/bd581d29-62fe-4d57-af85-ea7e831762b8)

Now the reconstructed data looks the same, except some tiny difference in voxel values which is acceptable. It is probably due to differences in implementations.

Thank you again for your help!
