### ISSUE TITLE
Python geom_postalignment factor only accepts tuple for 3D geoms

### ISSUE THREAD

**Issue by csparker247** [astra-toolbox/astra-toolbox#439]
The Python documentation for `functions.geom_postalignment` implies that you can pass a single float for 3D geometries:

> For 3D geometries, factor can be a pair of floats specifying the horizontal resp. vertical distances to shift the detector. If only a single floatis specified, this is treated as a horizontal shift.

However, the code is written to require a subscriptable object, and will throw `TypeError: 'float' object is not subscriptable` if passed a float:

https://github.com/astra-toolbox/astra-toolbox/blob/58622fd60305964abb255583e936ba62f6d96903/python/astra/functions.py#L303-L307

Probably fixable with a fairly simple `isinstance` check or something to that effect:
```python
if isinstance(factor, float):
  factor = (factor,)
```

**Comment by askorikov** [comment]
Hi, thanks for reporting this! It should get fixed by f6b357de416bf025b1d6d4defd3900a15ee4fb13 in the next release.
