### ISSUE TITLE
Support for `torch.Tensor` input (or any other tensor-type input)

### ISSUE THREAD

**Issue by Masaaki-75** [astra-toolbox/astra-toolbox#442]
**Is ASTRA going to support `torch.Tensor` input in the forward/backward projection function in the future?**

It seems that the forward/backward projection function in current ASTRA (Python) only supports `np.ndarray` input, rather than `torch.Tensor`, which makes it difficult to integrate within a deep-learning network for tomography, since converting a `torch.Tensor` to `np.ndarray` will drop all the computational graph and gradient information, preventing these tensors from benefiting from Pytorch's (or any other deep-learning framework like TensorFlow) automatic differentiation mechanism.

BTW, when given a `torch.Tensor` input, functions like `astra.create_sino` will raise the following error:
```bash
Configuration Error in FP_CUDA: No valid volume data object found.
Traceback (most recent call last):
  File "/home/clma/projects/mar/RIL/recon_astra.py", line 170, in <module>
    s_fan = recon_tools.fan_proj_torch(x, angles, use_gpu=True)
  File "/home/clma/projects/mar/RIL/recon_astra.py", line 85, in fan_proj_torch
    sinogram_id, sinogram = astra.create_sino(ct_image, proj_id)
  File "/home/clma/miniconda3/envs/carter/lib/python3.9/site-packages/astra/creators.py", line 403, in create_sino
    alg_id = algorithm.create(cfg)
  File "/home/clma/miniconda3/envs/carter/lib/python3.9/site-packages/astra/algorithm.py", line 36, in create
    return a.create(config)
  File "astra/algorithm_c.pyx", line 68, in astra.algorithm_c.create
Exception: Unable to initialize Algorithm.
```

**Comment by askorikov** [comment]
Hi! This can be achieved via the `GPUlink` functionality and you can use the [Tomosipo library](https://github.com/ahendriksen/tomosipo) that implements that based on Astra. We don't plan to add support for that to the main Astra library though.

**Comment by Masaaki-75** [comment]
Sounds great! And is there any doc/example on using `GPUlink`? I didn't find it at https://astra-toolbox.com/index.html

**Comment by askorikov** [comment]
We have an example here: https://github.com/astra-toolbox/astra-toolbox/blob/master/samples/python/s021_pygpu.py, but for PyTorch tensors the easiest would probably be to use Tomosipo implementation as it also provides integration with autodiff engine.
