### ISSUE TITLE
A Question about creating the projector

### ISSUE THREAD

**Issue by daanwilltell** [astra-toolbox/astra-toolbox#453]
I am using Astra on Google Colab, with the astra-toolbox version being 2.0.0. I encountered the following issue when trying to create a projector:

START_ANGLE = 0
END_ANGLE   = 180
STEP_ANGLE  = 3

m, n = 64, 64
# create geometries and projector
proj_geom = astra.create_proj_geom('fanflat', 1.0, 1024, np.linspace(np.deg2rad(START_ANGLE), np.deg2rad(END_ANGLE), (END_ANGLE - START_ANGLE) // STEP_ANGLE), 1800, 500)
vol_geom = astra.create_vol_geom(m, n)

**proj_id = astra.create_projector('cuda', proj_geom, vol_geom)**

The error occurred in astra/projector_c.pyx within astra.projector_c.create()

Exception: Error in creating the projector.

**Comment by wjp** [comment]
What does `astra.test()` report?
