### ISSUE TITLE
RTX 4090 supported?

### ISSUE THREAD

**Issue by themowhite** [astra-toolbox/astra-toolbox#464]
Hello (world),

I am currently trying to run the ASTRA Toolbox on an Ubuntu machine with an RTX 4090.

Astra version 2.1.2.
Cudatoolkit 11.3.1

```
import numpy as np
import astra

n_angles = 1000
angles = np.linspace(0, 2.0*np.pi, n_angles)
det_spacing_x = 0.1
det_spacing_y = 0.1
det_row_count = 1
det_col_count = 1000
source_origin, origin_det = 500, 500

vol_geom = astra.create_vol_geom(1000, 1000, 1)
proj_geom = astra.create_proj_geom('cone',  det_spacing_x, det_spacing_y, det_row_count, det_col_count, angles, source_origin, origin_det)

sino = np.random.random((det_row_count, n_angles, det_col_count)).astype(np.float32)

sino_id = astra.data3d.create('-sino', proj_geom, sino)
rec_id = astra.data3d.create('-vol',vol_geom)

cfg = astra.creators.astra_dict('FDK_CUDA')
cfg['ReconstructionDataId'] = rec_id
cfg['ProjectionDataId'] = sino_id

alg_id = astra.algorithm.create(cfg)

astra.algorithm.run(alg_id)
```

This code raises:
Warning: Unable to get available GPU memory. Defaulting to 1GB.
Error: maxBlockDimension getDevice: CUDA error 804: forward compatibility was attempted on non supported HW.
Warning: Error querying device

Is it an Astra-related problem? I was digging through the repo and were not able to trace down the exact call to cpp, where the error might originate from.

Thanks in advance
Moritz

EDIT: an even shorter example:
Running
```
import astra
astra.test()
```
yields 

No GPU support available
ASTRA Toolbox v2.1.2
Testing basic CPU 2D functionality... Ok

**Comment by themowhite** [comment]
Hi, 
thank you for your feedback :)

I started a new conda env and installed cudatoolkit 12.4.
Then i installed astra, which overwrites the cudatoolkit to 11.3 and the problem occurs again.

The interesting part is, that pytorch seems to work with this cuda version, but they are also shipping their own cuda binaries (I think) so the conflict may not occur.

**Comment by askorikov** [comment]
Oh, I see. Can you post the output of running `conda list 'astra|cuda'` in your environment? Currently, the recommended way to install Astra is `conda install astra-toolbox -c astra-toolbox -c nvidia`. This should use the same CUDA binaries as PyTorch, but maybe something went wrong.

**Comment by askorikov** [comment]
In the meantime, I will update installation instructions. I realized that they are outdated at the moment.

**Comment by themowhite** [comment]
In my current env:
```
conda list 'astra|cuda'
```

astra-toolbox             2.1.2           py310hb150abf_0    astra-toolbox
cuda-cccl                 12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-command-line-tools   12.4.1                        0    nvidia/label/cuda-12.4.1
cuda-compiler             12.4.1                        0    nvidia/label/cuda-12.4.1
cuda-cudart               12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-cudart-dev           12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-cudart-static        12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-cuobjdump            12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-cupti                12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-cupti-static         12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-cuxxfilt             12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-documentation        12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-driver-dev           12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-gdb                  12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-libraries            12.4.1                        0    nvidia/label/cuda-12.4.1
cuda-libraries-dev        12.4.1                        0    nvidia/label/cuda-12.4.1
cuda-libraries-static     12.4.1                        0    nvidia/label/cuda-12.4.1
cuda-nsight               12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-nsight-compute       12.4.1                        0    nvidia/label/cuda-12.4.1
cuda-nvcc                 12.4.131                      0    nvidia/label/cuda-12.4.1
cuda-nvdisasm             12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-nvml-dev             12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-nvprof               12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-nvprune              12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-nvrtc                12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-nvrtc-dev            12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-nvrtc-static         12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-nvtx                 12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-nvvp                 12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-opencl               12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-opencl-dev           12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-profiler-api         12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-python               12.4.0                   pypi_0    pypi
cuda-sanitizer-api        12.4.127                      0    nvidia/label/cuda-12.4.1
cuda-toolkit              12.4.1                        0    nvidia/label/cuda-12.4.1
cuda-tools                12.4.1                        0    nvidia/label/cuda-12.4.1
cuda-visual-tools         12.4.1                        0    nvidia/label/cuda-12.4.1
cudatoolkit               11.3.1               h2bc3f7f_2                                                    <-- this seems to be the problem?
libastra                  2.1.2               cuda_11.3_0    astra-toolbox


In a fresh environment (py 3.10) using ``` conda install astra-toolbox -c astra-toolbox -c nvidia ```:
```
conda list 'astra|cuda'
```
astra-toolbox             2.1.3           py310hb150abf_0    astra-toolbox
cudatoolkit               11.0.221             h6bb024c_0    nvidia
libastra                  2.1.3               cuda_11.0_0    astra-toolbox

but still
```
>>> import astra
>>> astra.test()
No GPU support available
ASTRA Toolbox v2.1.3
Testing basic CPU 2D functionality... Ok
```

**Comment by themowhite** [comment]
I don't know why, but a sudo reboot fixed it...
The torch environment, with almost the exact same packages was running like a charm.

I can confirm, that your new installation instruction with the nvidia channel works on RTX4090.

Thank you for your support :) 

```
conda install astra-toolbox -c astra-toolbox -c nvidia
```

**Comment by askorikov** [comment]
Sure!
