### ISSUE TITLE
Unable to install with Python 3.11

### ISSUE THREAD

**Issue by devangelista2** [astra-toolbox/astra-toolbox#472]
I was trying to install ASTRA Toolbox on Python version 3.11. Even if it is declared on the README.md that ASTRA is compatible with Python 3.7-3.11, in the installing specifications of the library, version 3.11 is excluded. I attach the error message down below:

`- astra-toolbox -> python[version='2.7.*|3.5.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.
8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.6.*']`

**Comment by askorikov** [comment]
Indeed, currently there are no conda builds of ASTRA for Python 3.11 on Windows (which I guess is your platform). We are working on it at the moment, but you can try installing from conda-forge channel with `conda install astra-toolbox -c conda-forge` for the time being.
