### ISSUE TITLE
why the projection data transform from width*height*deep to width*deep*height?

### ISSUE THREAD

**Issue by dyxer** [astra-toolbox/astra-toolbox#484]
Hi askorikov!
when I red the code of bool CFloat32ProjectionData3DMemory::initialize(CProjectionGeometry3D* _pGeometry, const float32* _pfData){ m_pGeometry = _pGeometry->clone();
m_bInitialized = _initialize(m_pGeometry->getDetectorColCount(), // width
m_pGeometry->getProjectionCount(), // height
m_pGeometry->getDetectorRowCount(), // depth
_pfData);
return m_bInitialized;
} in the Float32ProjectionData3DMemory.cpp
i have a question that why are the number of projections set the height ?
i have 360 projections ,which per projection's size is 972 * 768, the data size are 972 * 768*  360.But the return data of CFloat32ProjectionData3DMemory are 972 * 360*768.

**Comment by leekunpeng** [comment]
The projection dimension in astra is [detU angle devV]. I think you can try permute the projection and make it fit astra.
Hope it works.

**Comment by dyxer** [comment]
thank you,i got it.
