### ISSUE TITLE
osx-arm64 binaries for recent releases

### ISSUE THREAD

**Issue by fvanmaele** [astra-toolbox/astra-toolbox#488]
Currently the `conda-forge` channel has astra-toolbox `2.1.2` which does not work with newer numpy versions (#396, #428). The `astra-toolbox` channel has an even older version (`2.0.0`) and only for Intel macs.

**Comment by wjp** [comment]
conda-forge coincidentally just updated astra to 2.2.0 an hour ago, so that may be your best option currently.
