### ISSUE TITLE
Windows installer on conda

### ISSUE THREAD

**Issue by adler-j** [astra-toolbox/astra-toolbox#52]
You already have a quite simple windows installer, but it would be nice to be able to download astra with conda, which is kindoff the "standard" way of installing compiled libraries on windows with python.

Since you already have [an account at conda](https://conda.anaconda.org/astra-toolbox), I suppose it wouldn't be very complicated to add windows binaries as well.

**Comment by wjp** [comment]
For astra-toolbox==1.8, there is now a win-64/py3.5 package on conda. I haven't been able to trick conda-build into accepting our build system for py2.7 yet.

**Comment by adler-j** [comment]
Great progress! Any update on what is failing with py2?

**Comment by wjp** [comment]
We want to build python 2.7 extension modules with vc14, but I can't figure out how to make conda-build install the vc14 version of boost. (It uses the vc9 one.)

I'll probably just work around it by requiring a local copy of boost with vc14 .lib files, which we already do for the manual msvc build anyway.

**Comment by wjp** [comment]
That seems to be working, and there are now py35 and py27 packages for win-64 for conda.
