### ISSUE TITLE
Hope to provide iterative FDK algorithm

### ISSUE THREAD

**Issue by LANGZHIZHEN** [astra-toolbox/astra-toolbox#532]
Hello, the algorithm you provide is very simple and efficient. I hope you can provide the iterative FDK algorithm to further improve the effect.

**Comment by askorikov** [comment]
We already have SIRT and CGLS iterative algorithms available for 3D reconstruction, see https://astra-toolbox.com/docs/algs/index.html#id1. Adding any more algorithms is not in our roadmap at the moment.
