### ISSUE TITLE
Parallel 2d vector geometry

### ISSUE THREAD

**Issue by adler-j** [astra-toolbox/astra-toolbox#54]
You currently have `vec` style geometries for 2d fan beam, 3d parallel and 3d cone beam. However, you do not have it for 2d parallel beam.

While it is easy to emulate, it would be nice to have for purposes of symmetry.

**Comment by wjp** [comment]
Yes, this is definitely a gap in our feature set. @wvaarle actually implemented most of this last year already, but I've been a bit slow in getting the GPU code compatible with it. I hope to have the last few bugs in there fixed this month.
