### ISSUE TITLE
Installing ASTRA on Linux

### ISSUE THREAD

**Issue by PhysikerErlangen** [astra-toolbox/astra-toolbox#57]
Hello,
I try to install Astra on one of the LINUX HPC Clusters of my universitiy.

Since I don't have sudo rights and the directories for BOOST, CUDA, PYTHON are located rather arbitrarily over the system, I struggle compiling the libraries using the configure script. Especially linking to the BOOST libraries and libs.

```
Boost is installed here: setenv  BOOST_ROOT      /apps/boost/1.54.0-sysgcc
Cuda is installed here: setenv  CUDA_HOME       /apps/CUDA/5.0/cuda
Python is installed here: /usr/bin/python
GCC is installed here:   /apps/gcc/gcc-4.8.1-x86_64/
```
Running the configure script with the following input doesn't work:
```
./configure --with-cuda --with-python --prefix=/home/astra-toolbox/bin
```

I receive following error message:
```
checking for boost-unit-test-framework... no
checking boost/any.hpp usability... no
checking boost/any.hpp presence... no
checking for boost/any.hpp... no
checking boost/static_assert.hpp usability... no
checking boost/static_assert.hpp presence... no
checking for boost/static_assert.hpp... no
checking boost/throw_exception.hpp usability... no
checking boost/throw_exception.hpp presence... no
checking for boost/throw_exception.hpp... no
configure: error: boost not found
```

Do you have any idea how my .configure needs to look like to make it work?

Best,
Florian

**Comment by wjp** [comment]
Hi,

We don't have an explicit way of passing the location where boost is installed, but you should be able to use the following:

    CPPFLAGS="-I/apps/boost/1.54.0-sysgcc/include" ./configure --with-cuda --with-python --prefix=/home/astra-toolbox/bin

Best regards,
Willem Jan

**Comment by wjp** [comment]
You're welcome. I'm glad that worked.

**Comment by PhysikerErlangen** [comment]
Hello,
after dealing with some other problems (dealing with the right python...) I finally made it to "make".
Now I have another boost problem:
```
/2d/.libs/astra.o
In file included from ./../../cuda/2d/../../include/astra/VolumeGeometry2D.h:32,
                 from ./../../cuda/2d/astra.cu:45:
./../../cuda/2d/../../include/astra/Globals.h:57:35: error: boost/static_assert.hpp: No such file or directory
./../../cuda/2d/../../include/astra/Globals.h:58:37: error: boost/throw_exception.hpp: No such file or directory
make: *** [cuda/2d/astra.lo] Error 1
```
My configure line is the following:
```
CPPFLAGS="-I/apps/boost/1.54.0-sysgcc/include" ./configure --with-cuda=/apps/NVIDIA/cudatoolkit-7.0 --with-python --prefix=/home/masterThesis/astra-toolbox/bin
```
Boost should be linked correctly? Why is make not able to find it correctly? I made sure that boost/static_assert.hpp exists in the boost.

Best,
Florian

**Comment by wjp** [comment]
Ah... maybe we should add CPPFLAGS to the CUDA compilation too automatically. I'll have to think if that has any adverse side effects. But for now, this should be a workaround:

    CPPFLAGS="-I/apps/boost/1.54.0-sysgcc/include" NVCCFLAGS="-I/apps/boost/1.54.0-sysgcc/include" ./configure --with-cuda=/apps/NVIDIA/cudatoolkit-7.0 --with-python --prefix=/home/masterThesis/astra-toolbox/bin

**Comment by PhysikerErlangen** [comment]
Hello,

this worked. I was able to run make and make install.

Now I wanted to run some of the Python example. Before doing so I tested if import astra workes.
```
In [3]: import astra
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-dd583ecd89eb> in <module>()
----> 1 import astra

/home/hpc/capm/mppi006h/masterThesis/astra-toolbox/bin/python/astra/__init__.py in <module>()
     24 #
     25 #-----------------------------------------------------------------------
---> 26 from . import matlab as m
     27 from .creators import astra_dict,create_vol_geom, create_proj_geom, create_backprojection, create_sino, create_reconstruction, create_projector,create_sino3d_gpu, create_backprojection3d_gpu
     28 from .functions import data_op, add_noise_to_sino, clear, move_vol_geom

/home/hpc/capm/mppi006h/masterThesis/astra-toolbox/bin/python/astra/matlab.py in <module>()
     36 """
     37
---> 38 from . import astra_c
     39 from . import data2d_c
     40 from . import data3d_c

ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory

```

I have set the environment variables as requested:
PYTHONPATH=/home/astra-toolbox/bin/python/
and 
LD_LIBRARY_PATH=/home/astra-toolbox/bin/lib

Do you know what could have gone wrong?

Best,
Florian

**Comment by wjp** [comment]
Your LD_LIBRARY_PATH should probably also include `/apps/CUDA/5.0/cuda/lib64`, so

    export LD_LIBRARY_PATH=/apps/CUDA/5.0/cuda/lib64:/home/astra-toolbox/bin/lib

You may also want to check if your system has a default LD_LIBRARY_PATH set already with other paths maybe.

**Comment by PhysikerErlangen** [comment]
Wow, perfect :)
Thank you so much! 

Ahh, that was a very stupid mistake from me... I forgot to actually load the module CUDA, since I was working with with absolute paths in the configure script.
 
I'm (pretty) new to Linux and especially autoconf... This gave me a really hard time.

I was thinking if it were possible to adapt the installation instruction for Linux a bit, since there are different obstacles to overcome if the linux machine varies a bit and additonal parameters have to be set.
Since Astra seems to offer many cool things with a nicely wrapped python/ matlab wrapping, an easy installation of the toolbox would be awesome. I guess I'm not the only who experienced problems during installation/ compilation on linux.
