### ISSUE TITLE
Astra with Julia

### ISSUE THREAD

**Issue by josh-gree** [astra-toolbox/astra-toolbox#61]
I would like to start doing some work using Julia with Astra. Although it may be possible to use functions from astra via julia's PyCall library, I think it would be more useful to use julia's CUDA libraries to call the .cu files directly. Can anyone give me some pointers to the places in the source that I should be looking in order to just initially implement a forward projection operator? 

Also is this something that may be useful more widely?

**Comment by wjp** [comment]
I'm not familiar with interfacing Julia and CUDA, but from looking around online a bit, it seems this interface is limited to calling CUDA kernels directly. The ASTRA CUDA code doesn't consist of only kernels that can be directly called; they quite essentially need the C++ code around the CUDA kernels, so this might be problematic. (But possibly you're thinking of something else.)

Would it be possible to call ASTRA C++ functions (bypassing Python)?
