### ISSUE TITLE
Different filters in FBP on CPU?

### ISSUE THREAD

**Issue by jakobsj** [astra-toolbox/astra-toolbox#63]
Is it possible to use different filters than the default Ram-Lak in the CPU version of FBP? 

For the GPU-version this is achieved by setting FilterType, but the documentation does not say that that is possible in the CPU-version, and running the code below (modified from s014_FBP.m for CPU, change to fanflat geometry and add noise) yields identical results no matter what FilterType is set to. But since the documentation also only says the CPU FBP should work for parallel geometry, but seems to work fine for fanflat as well, I wondered if different filters would somehow be possible as well. Astra version 1.7.1 on linux.

``` matlab
vol_geom = astra_create_vol_geom(256, 256);
proj_geom = astra_create_proj_geom('fanflat', 1.0, 384, linspace2(0,2*pi,360),1000,0);

proj_id = astra_create_projector('line_fanflat',proj_geom,vol_geom);

% As before, create a sinogram from a phantom
P = phantom(256);
[sinogram_id, sinogram] = astra_create_sino_gpu(P, proj_geom, vol_geom);

% Add some noise
astra_add_noise_to_sino(sinogram_id,1e4);

% Create a data object for the reconstruction
rec_id = astra_mex_data2d('create', '-vol', vol_geom);

% create configuration 
cfg = astra_struct('FBP');
cfg.ReconstructionDataId = rec_id;
cfg.ProjectionDataId = sinogram_id;
cfg.ProjectorId = proj_id;
cfg.FilterType = 'Hann';

% possible values for FilterType:
% none, ram-lak, shepp-logan, cosine, hamming, hann, tukey, lanczos,
% triangular, gaussian, barlett-hann, blackman, nuttall, blackman-harris,
% blackman-nuttall, flat-top, kaiser, parzen


% Create and run the algorithm object from the configuration structure
alg_id = astra_mex_algorithm('create', cfg);
astra_mex_algorithm('run', alg_id);

% Get the result
rec = astra_mex_data2d('get', rec_id);
figure(3); imshow(rec, []);

% Clean up. Note that GPU memory is tied up in the algorithm object,
% and main RAM in the data objects.
astra_mex_algorithm('delete', alg_id);
astra_mex_data2d('delete', rec_id);
astra_mex_data2d('delete', sinogram_id);
```

**Comment by jakobsj** [comment]
Just noticed I did not change the astra_create_sino_gpu to the cpu version, but just to clarify that replacing that line to
```matlab
[sinogram_id, sinogram] = astra_create_sino(P, proj_id);
```
does not change the behavior, ie, FilterType still seems to have no effect.

**Comment by maximka48** [comment]
I have the same question. jakobsj, did you manage to find the answer?

**Comment by wjp** [comment]
`FilterType` is indeed currently not implemented in our CPU FBP. I'll add this to my to-do list.

**Comment by maximka48** [comment]
wjp, thank you! Could you please notify me somehow when you'll manage to do this.
