### ISSUE TITLE
Link GPU memory

### ISSUE THREAD

**Issue by adler-j** [astra-toolbox/astra-toolbox#65]
It is currently possible to link with numpy arrays. Would it be possible to pass an external GPU memory pointer to astra and use it with the astra algorithms? This would significantly reduce overhead when calling astra from e.g. python.

**Comment by wjp** [comment]
This is getting closer to being mergable: https://github.com/wjp/astra-toolbox/commits/GPULink

The idea is to fill a `GPULink` struct with the pointer and dimensions, and pass that to the data3d.link call.

**Comment by adler-j** [comment]
Looking like a great compromise, looking forward to it.

**Comment by wjp** [comment]
This is now merged into master from PR #93.
