### ISSUE TITLE
Cannot get version of astra in python

### ISSUE THREAD

**Issue by adler-j** [astra-toolbox/astra-toolbox#68]
Most packages provide `__version__`, obtained from `setup()`:

``` python
>>> import odl; odl.__version__
'0.4.0'
>>> import numpy; numpy.__version__
'1.10.2'
>>> import pytest; pytest.__version__
'3.0.0'
```

etc.

Astra however does not.

``` python
>>> import astra; astra.__version__
AttributeError: 'module' object has no attribute '__version__'
```

This would be a great addition since it would allow checking if some functionality is currently available or not.

Disclaimer: This may have been added since my last install of ASTRA.

**Comment by kohr-h** [comment]
There is the tool
```python
>>> import astra
>>> astra.astra.version(printToScreen=True)  # of course!?
1.7.1
```
But agreed, this should be in the `__version__` attribute.

**Comment by dmpelt** [comment]
Agreed on all points. I think I included the extremely weird existing code to match an existing Matlab script, but I should have included `__version__` as well. As noted in  https://github.com/odlgroup/odl/issues/724 however, we will also have to update the version to some intermediate value between 1.7.1 and the next release for it to make sense... I will try to write up a PR for this soon.

**Comment by wjp** [comment]
#82 has added this.
