### ISSUE TITLE
Astra with OpTomo using Python for 3D datasets

### ISSUE THREAD

**Issue by arbrefleur** [astra-toolbox/astra-toolbox#70]
Dear All, 

I am trying to use Astra with OpTomo operators to deal with 3D datasets using the Python back-end (v1.7.1beta). However, I am currently facing what might be a trivial problem, but I could not find a solution towards a correct behavior. 

I am starting with the following typical cone-beam code :
'''python
import astra
import numpy as np
angles = np.linspace(0,2*np.pi,360)
proj_geom = astra.create_proj_geom('cone', 1.0, 1.0,50,50, angles,1,0)
vol_geom = astra.create_vol_geom((128,128,128))
'''
And then I would like to recover the OpTomo operator W. But I could not find a way to define the proj_id from the previous piece of code. 

'''python
W = astra.OpTomo(proj_id)
fp = W*image
bp = W.T*sinogram
'''

I tried the astra.create_sino3d_gpu function but failed with a 'Algorithm not initialized' error.
I also tried the astra.creators.projector3d.create function but could not find what to include in the configuration structure. The astra.create_projector() sounds to be only for 2D geometries. And the matlab-like initialization "W = astra.opTomo('cuda', proj_geom, vol_geom);" does not seem to have a corresponding python implementation. 

Any help would be very appreciated.

**Comment by wjp** [comment]
You should be able to use `astra.create_projector()` for a 3D projector (with type `cuda3d`). Our documentation for that function is indeed wrong.

**Comment by wjp** [comment]
Updated docstring in 9a4372d61fc3c2c0661d479ffe4a13193c7f8862. Thanks for the report.

**Comment by arbrefleur** [comment]
Thanks a lot for the help. I missed the 'cuda3d' type .
