### ISSUE TITLE
ImportError after conda install

### ISSUE THREAD

**Issue by adler-j** [astra-toolbox/astra-toolbox#86]
After installing astra via:

`conda install -c astra-toolbox astra-toolbox=1.8`

I try importing astra and it fails

```python
>>> import astra
Traceback (most recent call last):

  File "<ipython-input-1-dd583ecd89eb>", line 1, in <module>
    import astra

  File "c:\anaconda\lib\site-packages\astra\__init__.py", line 26, in <module>
    from . import matlab as m

  File "c:\anaconda\lib\site-packages\astra\matlab.py", line 38, in <module>
    from . import astra_c

ImportError: DLL load failed: The specified procedure could not be found.
```

It seems you are missing a DLL in the release. At the very least you should mention somewhere what else I need installed to run astra.

**Comment by adler-j** [comment]
It seems I needed to install a specific version of boost, namely one built with MSVC 14. I also needed to manually remove my old ASTRA installation, since it was silently interfering.

For anyone who finds this (and perhaps the doc?) you can find prebuilt boost that works with ASTRA here:

https://netix.dl.sourceforge.net/project/boost/boost-binaries/1.62.0/boost_1_62_0-msvc-14.0-64.exe

**Comment by wjp** [comment]
I wasn't aware we had any run-time boost dependencies (and we don't on linux). I'll check in Windows tomorrow.

**Comment by wjp** [comment]
Actually, I was too curious, so booted up Windows anyway. Using depends.exe I don't see any dependencies on boost DLLs. Just on the VS2015 (vc14) redistributables and CUDA 8.0. We ship the latter, and for the former we have this in libastra's meta.yaml:

```
requirements:
  run:
  - vs2015_runtime # [win]
```

I wonder why this is not working correctly for you. Any ideas?

I've just tried on my laptop (64 bit Win10, with a fresh Miniconda with both py27 and py35 environments. No global boost of VS2015 redistributables installed.), and `import astra` works ok here.

**Comment by adler-j** [comment]
This may have been a collision of dependencies since I reinstalled boost and then removed the old installation. Perhaps boost was not needed, I'll test it.

**Comment by adler-j** [comment]
Confirmed that the conda install works out of the box on another machine. It seems this has to do with collisions between astra installations, but simply removing the old "copy-paste dll" style installation solved this nicely.

**Comment by wjp** [comment]
Great, thanks for verifying.
