### ISSUE TITLE
DART in Python

### ISSUE THREAD

**Issue by PauTorru** [astra-toolbox/astra-toolbox#88]
Hi!

I am trying to perform DART tomography in python. So far I've seen the examples in Matlab, which resort to a class called DARTalgorithm but don't know how to call it or how to proceed in python. Is it possible? What am I missing?

**Comment by wjp** [comment]
Hi,

Unfortunately the DART implementation included in ASTRA is written in Matlab, and can therefore not be called from Python. (The code is in the directory matlab/algorithms/DART.)
