### ISSUE TITLE
Conda package with numpy 1.12

### ISSUE THREAD

**Issue by adler-j** [astra-toolbox/astra-toolbox#98]
When installing astra, numpy 1.11 is currently a requirement, but 1.12 has been out for a while. It would be nice if you provided conda packages for 1.12 as well.

**Comment by wjp** [comment]
I've created and uploaded additional conda packages for { win-64, linux-64 } x { py27, py35, py36 } x { np112 }.

**Comment by adler-j** [comment]
Great, thanks!
